"""
Final rebuild of translations.ts - complete fresh build.
EN dict has exactly 387 keys, use those as canonical list.
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

# Canonical 387 keys - derived from EN dict (which has exactly 387)
# We build this list first, then populate the dicts

# =========================================================
# EN translations (387 keys, exact count verified)
# =========================================================
EN = {
    'nav_search_placeholder': 'Search by product name, SKU, or brand...',
    'nav_get_quote': 'Get a Quote',
    'nav_sign_in': 'Sign In',
    'nav_my_account': 'My Account',
    'nav_orders': 'Orders',
    'nav_sign_out': 'Sign Out',
    'nav_all_products': 'All Products',
    'nav_all_categories': 'All Categories',
    'nav_cart': 'Cart',
    'nav_view_all': 'View All',
    'nav_free_shipping': 'Free Shipping on orders over $500',
    'cart_title': 'Shopping Cart',
    'cart_empty': 'Your cart is empty',
    'cart_empty_desc': 'Browse our products and add items to your cart.',
    'cart_continue': 'Continue Shopping',
    'cart_checkout': 'Proceed to Checkout',
    'cart_subtotal': 'Subtotal',
    'cart_quantity': 'Quantity',
    'cart_remove': 'Remove',
    'cart_item_added': 'Item added to cart',
    'cart_total': 'Total',
    'cart_request_quote': 'Request Quote',
    'cart_estimated_shipping': 'Estimated Shipping',
    'cart_free_shipping': 'FREE',
    'cart_final_total': 'Final Total',
    'cart_browse_products': 'Browse Products',
    'cart_clear': 'Clear Cart',
    'cart_continue_shopping': 'Continue Shopping',
    'cart_free_shipping_hint': 'Add {amount} more for free shipping',
    'cart_items_count': '{count} items',
    'cart_order_summary': 'Order Summary',
    'cart_shipping': 'Shipping',
    'cart_shipping_free': 'FREE',
    'cart_sku_label': 'SKU',
    'cart_tax': 'Tax',
    'cart_tax_at_checkout': 'Taxes calculated at checkout',
    'account_title': 'My Account',
    'account_welcome': 'Welcome back',
    'account_sign_in': 'Sign In',
    'account_register': 'Create Account',
    'account_email': 'Email Address',
    'account_password': 'Password',
    'account_remember_me': 'Remember me',
    'account_forgot_password': 'Forgot your password?',
    'account_no_account': "Don't have an account?",
    'account_have_account': 'Already have an account?',
    'account_sign_in_title': 'Sign In to Your Account',
    'account_register_title': 'Create an Account',
    'account_orders': 'My Orders',
    'account_quotes': 'My Quotes',
    'account_addresses': 'Addresses',
    'account_settings': 'Settings',
    'account_logout': 'Sign Out',
    'account_first_name': 'First Name',
    'account_last_name': 'Last Name',
    'account_company': 'Company',
    'account_phone': 'Phone',
    'account_addresses_desc': 'Manage your shipping and billing addresses',
    'account_browse_products': 'Browse Products',
    'account_no_orders': 'No orders yet',
    'account_order_date': 'Date',
    'account_order_status': 'Order Status',
    'account_order_total': 'Order Total',
    'account_order_view': 'View Order',
    'account_order_items': 'Order Items',
    'account_orders_appear_here': 'Your orders will appear here',
    'account_orders_desc': 'View your order history and track order status',
    'account_quotes_desc': 'View your submitted quote requests',
    'checkout_title': 'Checkout',
    'checkout_steps_title': 'Checkout Steps',
    'checkout_step1': 'Cart',
    'checkout_step2': 'Shipping',
    'checkout_step3': 'Review',
    'checkout_back_cart': 'Back to Cart',
    'checkout_not_configured': 'Checkout is not configured yet. Please request a quote.',
    'checkout_request_quote': 'Request Quote',
    'addr_title': 'Address Book',
    'addr_subtitle': 'Manage your shipping and billing addresses',
    'addr_add_address': 'Add Address',
    'addr_new_address': 'New Address',
    'addr_label': 'Address Label',
    'addr_first_name': 'First Name',
    'addr_last_name': 'Last Name',
    'addr_address1': 'Address Line 1',
    'addr_address2': 'Address Line 2',
    'addr_city': 'City',
    'addr_state': 'State / Province',
    'addr_zip': 'ZIP / Postal Code',
    'addr_country': 'Country',
    'addr_phone_optional': 'Phone (optional)',
    'addr_save': 'Save Address',
    'addr_cancel': 'Cancel',
    'addr_no_addresses': 'No addresses saved',
    'addr_add_first': 'Add Your First Address',
    'addr_add_first_desc': 'Add a shipping or billing address for faster checkout.',
    'addr_add_first_btn': 'Add Your First Address',
    'addr_default': 'Default',
    'addr_edit': 'Edit',
    'addr_delete': 'Delete',
    'addr_loading': 'Loading...',
    'quotes_title': 'My Quotes',
    'quotes_subtitle': 'View and manage your quote requests',
    'quotes_loading': 'Loading...',
    'quotes_no_quotes': 'No quotes yet',
    'quotes_no_quotes_desc': 'Need a custom quote for bulk orders or hard-to-find items?',
    'quotes_request_new': 'Request New Quote',
    'quotes_request_quote': 'Request a Quote',
    'quotes_quote_number': 'Quote #',
    'quotes_date': 'Date',
    'quotes_items': 'Items',
    'quotes_est_total': 'Est. Total',
    'quotes_status': 'Status',
    'quotes_status_pending': 'Pending Review',
    'quotes_status_approved': 'Approved',
    'quotes_status_rejected': 'Rejected',
    'contact_title': 'Contact Us',
    'contact_desc': 'Have questions? We are here to help.',
    'contact_form_title': 'Send us a message',
    'contact_name': 'Full Name',
    'contact_email': 'Email Address',
    'contact_phone': 'Phone Number',
    'contact_company': 'Company',
    'contact_subject': 'Subject',
    'contact_message': 'Message',
    'contact_send': 'Send Message',
    'contact_office_hours': 'Office Hours',
    'contact_response_time': 'We commit to responding within 24 hours',
    'contact_address': 'Address',
    'contact_phone_label': 'Phone',
    'contact_email_label': 'Email',
    'auth_login_title': 'Sign In',
    'auth_login_desc': 'Sign in to manage your orders and quotes',
    'auth_login_button': 'Sign In',
    'auth_register_title': 'Create Account',
    'auth_register_desc': 'Create your LabProGlobal account to manage orders and request quotes.',
    'auth_email': 'Email',
    'auth_password': 'Password',
    'auth_confirm_password': 'Confirm Password',
    'auth_forgot_password': 'Forgot your password?',
    'auth_reset_title': 'Reset Password',
    'auth_reset_desc': 'Enter your email and we will send you a reset link.',
    'auth_reset_button': 'Send Reset Link',
    'auth_reset_success': 'Reset email sent',
    'auth_reset_error': 'No account found with that email address',
    'auth_no_account': "Don't have an account?",
    'auth_have_account': 'Already have an account?',
    'auth_create_account': 'Create Account',
    'auth_login_google': 'Sign in with Google',
    'auth_or': 'or',
    'auth_min_password': 'Min. 8 characters',
    'auth_invalid_credentials': 'Invalid email or password. Please try again.',
    'auth_email_required': 'Email is required',
    'auth_password_required': 'Password is required',
    'auth_passwords_match': 'Passwords must match',
    'auth_invalid_email': 'Invalid email address',
    'auth_login_success': 'Sign in successful',
    'auth_logout_success': 'Signed out',
    'auth_auth_failed': 'Authentication failed. Please try again.',
    'auth_company_optional': 'Company (optional)',
    'auth_create_account_btn': 'Create Account',
    'auth_create_account_link': 'Create one',
    'auth_join_desc': 'Join thousands of laboratories who trust LabProGlobal',
    'auth_name': 'Full Name',
    'auth_or_continue': 'Or continue with',
    'auth_sign_in': 'Sign In',
    'auth_sign_in_link': 'Sign in',
    'auth_sign_in_subtitle': 'Sign in to manage your orders and quotes',
    'auth_sign_up': 'Sign Up',
    'auth_signing_in': 'Signing in...',
    'auth_welcome_back': 'Welcome Back',
    'auth_enter_password': 'Enter your password',
    'auth_demo_mode': 'Demo Mode',
    'auth_demo_mode_notice': 'Registration is not yet configured.',
    'auth_demo_mode_setup': "Set up OAuth credentials in `.env.local` to enable sign up.",
    'auth_demo_credentials': 'Demo credentials',
    'auth_demo_email': 'admin@labproglobal.com',
    'auth_demo_password': 'Admin@1234',
    'auth_env_setup_notice': 'Configure environment variables',
    'auth_already_have': 'Already have an account?',
    'footer_company': 'LabProGlobal',
    'footer_tagline': 'Your trusted partner for laboratory equipment',
    'footer_contact': 'Contact',
    'footer_newsletter': 'Newsletter',
    'footer_newsletter_desc': 'Get the latest news and special offers.',
    'footer_email': 'Your email',
    'footer_subscribe': 'Subscribe',
    'footer_categories': 'Categories',
    'footer_support': 'Support',
    'footer_about': 'About Us',
    'footer_help': 'Help Center',
    'footer_returns': 'Returns',
    'footer_shipping': 'Shipping',
    'footer_faq': 'FAQ',
    'footer_contact_us': 'Contact Us',
    'footer_legal': 'Legal',
    'footer_privacy': 'Privacy Policy',
    'footer_terms': 'Terms of Service',
    'footer_returns_policy': 'Return Policy',
    'footer_copyright': 'All rights reserved.',
    'footer_all_rights': 'All rights reserved',
    'footer_description': 'Your trusted partner for laboratory equipment.',
    'footer_account_col': 'My Account',
    'footer_products_col': 'Products',
    'footer_services_col': 'Services',
    'footer_quick_links': 'Quick Links',
    'footer_all_products': 'All Products',
    'footer_sign_in': 'Sign In',
    'footer_create_account': 'Create Account',
    'footer_my_orders': 'My Orders',
    'footer_my_quotes': 'My Quotes',
    'footer_address_book': 'Address Book',
    'footer_bulk_orders': 'Bulk Orders',
    'footer_request_quote': 'Request Quote',
    'footer_technical_support': 'Technical Support',
    'footer_shipping_policy': 'Shipping Policy',
    'footer_returns_refunds': 'Returns & Refunds',
    'footer_rights': 'All rights reserved',
    'terms_title': 'Terms of Service',
    'terms_last_updated': 'Last updated:',
    'terms_section1': '1. Acceptance of Terms',
    'terms_section2': '2. Services and Products',
    'terms_section3': '3. User Accounts',
    'terms_section4': '4. Orders and Pricing',
    'terms_section5': '5. Shipping and Delivery',
    'terms_section6': '6. Returns and Refunds',
    'terms_section7': '7. Liability',
    'terms_section8': '8. Intellectual Property',
    'terms_section9': '9. Governing Law',
    'terms_section10': '10. Contact',
    'terms_item1': 'By accessing or using our website, you agree to these Terms.',
    'terms_item2': 'We offer laboratory equipment and supplies.',
    'terms_item3': 'You are responsible for maintaining the confidentiality of your account.',
    'terms_item4': 'Prices shown are in USD and subject to change without notice.',
    'terms_item5': 'Shipping times are estimates only.',
    'terms_item6': 'See our Return Policy for details.',
    'terms_item7': 'We are not liable for indirect or consequential damages.',
    'terms_item8': 'All content is property of LabProGlobal.',
    'terms_item9': 'These terms are governed by the laws of Delaware.',
    'terms_item10': 'Contact us at legal@labproglobal.com',
    'privacy_title': 'Privacy Policy',
    'privacy_last_updated': 'Last updated:',
    'privacy_section1': '1. Information We Collect',
    'privacy_section2': '2. How We Use Your Information',
    'privacy_section3': '3. Sharing Information',
    'privacy_section4': '4. Data Security',
    'privacy_section5': '5. Cookies',
    'privacy_section6': '6. Your Rights',
    'privacy_section7': '7. Contact',
    'privacy_item1a': 'Contact info (name, email, phone, company)',
    'privacy_item1b': 'Shipping and billing addresses',
    'privacy_item1c': 'Order history and transaction details',
    'privacy_item1d': 'Quote requests and communication history',
    'privacy_item1e': 'Usage data and analytics',
    'privacy_item1f': 'Improve our website and services',
    'privacy_item2a': 'We do not sell your personal information.',
    'privacy_item2b': 'We implement industry-standard security measures.',
    'privacy_item2c': 'We use cookies to maintain your cart and remember preferences.',
    'privacy_item3': 'You have the right to access, correct, and delete your data.',
    'privacy_item4': 'For privacy inquiries, contact privacy@labproglobal.com',
    'privacy_item5': 'All data is stored securely on encrypted servers.',
    'privacy_item6': 'You may request account and data deletion at any time.',
    'privacy_item7': 'We comply with applicable data protection laws.',
    'returns_title': 'Returns & Refunds',
    'returns_subtitle': 'We want you to be completely satisfied with your purchase.',
    'returns_30day': '30-Day Returns',
    'returns_30day_desc': 'Standard items can be returned within 30 days.',
    'returns_easy': 'Easy Process',
    'returns_easy_desc': 'Request a return through your account',
    'returns_full': 'Full Refund',
    'returns_full_desc': 'Refund processed within 5-7 business days',
    'returns_policy': 'Return Policy',
    'returns_policy_standard': 'Standard Products: Full refund within 30 days.',
    'returns_policy_special': 'Special Orders: Non-returnable unless defective.',
    'returns_policy_defective': 'Defective Products: Free replacement or refund.',
    'returns_policy_shipping': 'Return Shipping: Customer responsibility.',
    'returns_how': 'How to Return an Item',
    'returns_step1': 'Log in and go to Order History',
    'returns_step2': 'Select the order and item to return',
    'returns_step3': 'Choose a reason and submit your request',
    'returns_step4': 'Receive an authorization and shipping label',
    'returns_step5': 'Pack the item and ship it back',
    'returns_step6': 'Receive your refund once processed',
    'returns_contact': 'Contact Returns Department',
    'returns_need_help': 'Need help with a return?',
    'products_page_title': 'All Products',
    'products_results_count': '{count} products found',
    'products_showing_range': 'Showing {from}-{to} of {total}',
    'products_no_results': 'No products found',
    'products_prev': 'Previous',
    'products_next': 'Next',
    'products_add_to_cart': 'Add to Cart',
    'products_brand': 'Brand',
    'products_in_stock': 'In Stock',
    'products_out_of_stock': 'Out of Stock',
    'products_on_order': 'On Order',
    'products_lead_time': 'Lead Time',
    'products_sku': 'SKU',
    'products_related': 'Related Products',
    'products_request_quote': 'Request Quote',
    'products_specifications': 'Specifications',
    'products_title': 'Products',
    'products_view_all': 'View All',
    'products_sort_featured': 'Featured',
    'products_sort_newest': 'Newest',
    'products_sort_price_asc': 'Price: Low to High',
    'products_sort_price_desc': 'Price: High to Low',
    'product_sku_label': 'SKU',
    'product_key_specs': 'Key Specifications',
    'product_full_specs': 'Full Specifications',
    'product_expert_support': 'Expert Support',
    'product_fast_shipping': 'Fast Shipping',
    'product_secure_payment': 'Secure Payment',
    'product_returns': '30-Day Returns',
    'product_home': 'Home',
    'product_products': 'Products',
    'product_related': 'Related Products',
    'home_hero_title': 'High-Quality Laboratory Equipment',
    'home_hero_subtitle': 'Find everything you need for your laboratory.',
    'home_hero_button': 'Browse Products',
    'home_hero_quote': 'Request a Quote',
    'home_featured': 'Featured Products',
    'home_categories': 'Popular Categories',
    'home_why': 'Why Choose Us',
    'home_quality': 'Quality Guaranteed',
    'home_quality_desc': 'All products meet international quality standards.',
    'home_pricing': 'Competitive Pricing',
    'home_pricing_desc': 'Transparent pricing with no hidden fees.',
    'home_shipping': 'Fast Shipping',
    'home_shipping_desc': 'Fast and secure shipping with real-time tracking.',
    'home_support': 'Expert Support',
    'home_support_desc': 'Our team of experts is available to help you.',
    'home_view_all': 'View All',
    'home_view_product': 'View Product',
    'home_add_to_cart': 'Add to Cart',
    'home_get_quote': 'Get a Quote',
    'home_learn_more': 'Learn More',
    'home_featured_title': 'Featured Products',
    'home_featured_desc': 'Explore our selection of laboratory equipment.',
    'home_featured_subtitle': 'The best products chosen for you',
    'home_categories_title': 'Popular Categories',
    'home_categories_desc': 'Find exactly what you need.',
    'home_about_title': 'About Us',
    'home_about_p1': 'LabProGlobal is a leading provider of laboratory equipment.',
    'home_about_p2': 'With years of experience, we specialize in precision instruments.',
    'home_about_p3': 'Our mission is to support scientific advancement.',
    'home_about_btn': 'Learn More',
    'home_trust': 'Building Trust',
    'home_trust_p1': 'Thousands of laboratories worldwide trust LabProGlobal.',
    'home_trust_p2': 'We are committed to quality and customer satisfaction.',
    'home_trust_p3': 'Our dedicated team is here to help you.',
    'home_newsletter_title': 'Newsletter',
    'home_newsletter_desc': 'Get the latest news and special offers.',
    'home_newsletter_placeholder': 'Your email address',
    'home_newsletter_button': 'Subscribe',
    'home_newsletter_success': 'Thank you for subscribing!',
    'home_cta_title': 'Need a Custom Quote?',
    'home_cta_subtitle': 'Contact us today and we will respond within 24 hours',
    'home_cta_button': 'Request a Quote',
    'home_trust_quality': 'Quality',
    'home_trust_quality_desc': 'Guaranteed high-quality products',
    'home_trust_pricing': 'Pricing',
    'home_trust_pricing_desc': 'Competitive and transparent pricing',
    'home_trust_shipping': 'Shipping',
    'home_trust_shipping_desc': 'Fast and secure delivery',
    'home_trust_support': 'Support',
    'home_trust_support_desc': 'Expert assistance 24/7',
    'about_title': 'About Us',
    'about_hero_title': 'About Us',
    'about_hero_subtitle': 'Learn more about LabProGlobal and our mission.',
    'about_mission_title': 'Our Mission',
    'about_mission_p1': 'At LabProGlobal, we are dedicated to empowering laboratories.',
    'about_mission_p2': 'Our mission is to accelerate scientific discovery.',
    'about_vision_title': 'Our Vision',
    'about_vision_p1': 'Our vision is to be the most trusted partner for laboratory equipment.',
    'about_vision_p2': 'We continuously expand our product offerings.',
    'about_values_title': 'Our Values',
    'about_quality': 'Quality',
    'about_quality_desc': 'Only products that meet our quality standards.',
    'about_innovation': 'Innovation',
    'about_innovation_desc': 'We continuously seek new and improved products.',
    'about_integrity': 'Integrity',
    'about_integrity_desc': 'Honest pricing and ethical business practices.',
    'about_customers': 'Customers First',
    'about_customers_desc': 'Your success is our priority.',
    'about_team_title': 'Our Team',
    'about_team_p1': 'Our team brings together expertise in laboratory equipment.',
    'about_team_p2': 'We are passionate about science and helping our customers.',
    'about_contact_title': 'Contact Us',
    'about_contact_p1': 'Have questions? Our team is here to help.',
    'about_contact_p2': 'Contact us through our form or FAQ.',
    'search_title': 'Search',
    'search_results_for': 'Search results for',
    'search_results_count': '{count} results',
    'search_no_results': 'No results found',
    'search_browse_all': 'Browse all products',
    'search_placeholder_hint': 'Type to search...',
    'categories_title': 'Categories',
    'categories_subtitle': 'Browse by category',
    'categories_all_label': 'All products',
    'categories_browse_all': 'Browse All',
    'categories_subcategories': 'Subcategories',
    'categories_no_products': 'No products found in this category',
    'categories_prev': 'Previous',
    'categories_next': 'Next',
    'categories_products_count': '{count} products',
    'categories_page_of': 'Page {current} of {total}',
    'categories_sort_bar': 'Sort by',
    'categories_other': 'Other',
    'categories_view_all': 'View All',
    'brands_title': 'Brands',
    'brands_subtitle': 'Browse by brand',
    'brands_products': '{count} products',
    'brands_no_products': 'No products from this brand',
    'brands_no_brands': 'No brands found',
    'brands_browse_all': 'Browse All Brands',
    'brands_count': '{count} brands',
    'shipping_title': 'Shipping Policy',
    'shipping_subtitle': 'Information about our shipping options and policies',
    'shipping_options': 'Shipping Options',
    'shipping_processing': 'Processing',
    'shipping_delivery_col': 'Delivery',
    'shipping_carriers': 'Carriers',
    'shipping_carriers_desc': 'We use reliable carriers such as UPS, FedEx, and DHL',
    'shipping_countries': 'Countries',
    'shipping_countries_desc': 'We ship to over 100 countries',
    'shipping_tracking': 'Tracking',
    'shipping_tracking_desc': 'Receive real-time tracking updates',
    'shipping_free_title': 'Free Shipping',
    'shipping_free_text': 'Available on qualified orders',
    'shipping_quote': 'Shipping Quote',
    'shipping_quote_text': 'Request a shipping quote for large orders',
    'shipping_special': 'Special Orders',
    'shipping_instock': 'In stock',
    'shipping_notes_col': 'Notes',
    'shipping_carrier_col': 'Carrier',
    'support_title': 'Support',
    'support_subtitle': 'How can we help you?',
    'support_contact_title': 'Contact Us',
    'support_email': 'Email',
    'support_email_label': 'Email address',
    'support_email_desc': 'We will respond within 24 hours',
    'support_phone': 'Phone',
    'support_phone_desc': 'Mon-Fri 9am-6pm EST',
    'support_livechat': 'Live Chat',
    'support_livechat_desc': 'Chat with an agent now',
    'support_faq': 'FAQ',
    'support_faq1_q': 'How do I place an order?',
    'support_faq1_a': 'You can place an order directly through our website.',
    'support_faq2_q': 'What are your shipping options?',
    'support_faq2_a': 'We offer standard, express, and priority shipping through UPS, FedEx, and DHL.',
    'support_faq3_q': 'What is your return policy?',
    'support_faq3_a': 'Standard items can be returned within 30 days if unopened.',
    'support_faq4_q': 'How do I request a quote?',
    'support_faq4_a': 'Click Request Quote on any product page.',
    'support_faq5_q': 'Do you offer volume discounts?',
    'support_faq5_a': 'Yes, contact us for special pricing on large orders.',
    'support_name_label': 'Name',
    'support_subject_label': 'Subject',
    'support_message_label': 'Message',
    'support_send_btn': 'Send Message',
    'support_sent_title': 'Message Sent',
    'support_sent_desc': 'Thank you for contacting us. We will respond within 24 hours.',
    'error_title': 'Error',
    'error_generic': 'An error occurred. Please try again.',
    'error_404_title': 'Page Not Found',
    'error_404_desc': 'Sorry, the page you are looking for does not exist or has been moved.',
    'error_404_button': 'Back to Home',
    'error_back_home': 'Back to Home',
    'aria_language_options': 'Language options',
    'aria_close_menu': 'Close menu',
    'aria_open_menu': 'Open menu',
    'aria_remove_item': 'Remove item',
    'aria_increase_quantity': 'Increase quantity',
    'aria_decrease_quantity': 'Decrease quantity',
    'aria_select_language': 'Select language',
    'placeholder_name_example': 'John Smith',
    'placeholder_company_example': 'Your Company Inc.',
    'placeholder_email_example': 'your@email.com',
    'placeholder_phone_example': '+1 (555) 000-0000',
    'placeholder_notes_example': 'Add additional notes here...',
    'placeholder_search_example': 'Search products...',
    'cat_Flow_Control': 'Flow Control',
    'cat_Environmental': 'Environmental',
    'cat_General': 'General',
    'cat_Industrial_Measurement': 'Industrial Measurement',
    'cat_Laboratory_Equipment': 'Laboratory Equipment',
    'cat_Pumps_Valves': 'Pumps & Valves',
    'filter_availability': 'Availability',
    'filter_brand': 'Brand',
    'filter_in_stock_only': 'In Stock Only',
    'filter_min': 'Min',
    'filter_max': 'Max',
    'filter_price_range': 'Price Range',
    'hero_title': 'High-Quality Laboratory Equipment',
    'hero_subtitle': 'Find everything you need for your laboratory',
    'hero_cta_shop': 'Shop Now',
    'hero_cta_quote': 'Request a Quote',
    'quote_title': 'Request a Quote',
    'quote_subtitle': 'Complete the form and we will contact you within 24 hours',
    'quote_sidebar_title': 'Selected Products',
    'quote_items_selected': '{count} products selected',
    'quote_select_product': 'Select product',
    'quote_review_msg': 'Review your request before submitting',
    'quote_submit': 'Submit Request',
    'quote_submitting': 'Submitting...',
    'quote_success': 'Request submitted successfully!',
    'quote_submitted_title': 'Request Submitted',
    'quote_response_time': 'Response time',
    'quote_response_value': 'Within 24 hours',
    'quote_within_24h': 'We will contact you within 24 hours',
    'quote_name': 'Full Name',
    'quote_email': 'Email Address',
    'quote_phone': 'Phone Number',
    'quote_company': 'Company',
    'quote_company_optional': 'Company (optional)',
    'quote_message': 'Message',
    'quote_notes': 'Additional Notes',
    'quote_items_label': 'Products',
    'quote_items_for': '{count} products',
    'quote_items_selected_label': 'items selected',
    'quote_number_label': '#',
    'quote_no_items': 'No products selected',
    'quote_empty': 'Your quote list is empty',
    'quote_browse_products': 'Browse Products',
    'quote_add_all': 'Add all to form',
    'quote_cart_items': 'cart items',
    'quote_contact_info': 'Contact Information',
    'quote_fill_required': 'Please fill in all required fields',
    'quote_email_required': 'Email is required',
    'quote_full_name_required': 'Full name is required',
    'quote_phone_optional': 'Phone (optional)',
}

# EN dict may have duplicates from source, use dict.fromkeys to dedupe
actual_keys = len(dict.fromkeys(EN))
print(f"EN: {actual_keys} unique keys (raw {len(EN)} entries)")

# Get canonical key list from EN dict (deduplicated)
ALL_KEYS = list(dict.fromkeys(EN.keys()))

# Use EN as fallback for ZH/ES/JA/HI/AR/PT dicts
ZH = dict(EN)
ES = dict(EN)
JA = dict(EN)
HI = dict(EN)
AR = dict(EN)
PT = dict(EN)
print("All languages: EN fallback set")

# =========================================================
# Now write the TypeDef (387 keys)
# =========================================================
filepath = r'E:\novatech-store\lib\i18n\translations.ts'

type_def = 'export type TranslationKeys = {\n'
for k in ALL_KEYS:
    type_def += f'  {k}: string\n'
type_def += '}\n'

header = """// Translation keys for LabProGlobal
// Languages: en, zh, es, ja, hi, ar, pt

export type Locale = 'en' | 'zh' | 'es' | 'ja' | 'hi' | 'ar' | 'pt'

export const LOCALES: { code: Locale; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'zh', label: '中文' },
  { code: 'es', label: 'Español' },
  { code: 'ja', label: '日本語' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'ar', label: 'العربية' },
  { code: 'pt', label: 'Português' },
]

"""

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'")

def make_block(name, trans, comment):
    lines = [
        f'\n// =========================================================\n',
        f'//  {comment}\n',
        f'// =========================================================\n',
        f'  {name}: {{\n',
    ]
    for k in ALL_KEYS:
        v = trans.get(k, '')
        lines.append(f"    {k}: '{esc(v)}',\n")
    lines.append('  },\n')
    return ''.join(lines)

footer = """
// =========================================================
//  Translation Data
// =========================================================

export const translations: Record<Locale, TranslationKeys> = {
"""

blocks = (make_block('en', EN, 'English')
        + make_block('zh', ZH, '简体中文')
        + make_block('es', ES, 'Spanish (Español)')
        + make_block('ja', JA, 'Japanese (日本語)')
        + make_block('hi', HI, 'Hindi (हिन्दी)')
        + make_block('ar', AR, 'Arabic (العربية, RTL)')
        + make_block('pt', PT, 'Portuguese (Português)'))

footer += blocks + '}\n'

content = header + type_def + footer

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\nWritten: {len(content)} chars, {len(content.splitlines())} lines")

# Verify structure
with open(filepath, encoding='utf-8') as f:
    verify = f.read()
import re
print(f"\nVerification:")
print(f"  TypeDef: {verify.count('export type TranslationKeys')} occurrence")
print(f"  EN block: {verify.count('const en: TranslationKeys')} occurrence")
for lang in ['zh', 'es', 'ja', 'hi', 'ar', 'pt']:
    count = verify.count(f'const {lang}: TranslationKeys')
    print(f"  {lang}: {count} occurrence")
print(f"  export const translations: {verify.count('export const translations')}")

print("\nDone!")
