"""Fix ES (9 missing keys) and JA (179 missing keys)."""
import sys
sys.stdout.reconfigure(encoding='utf-8')
import re

ES_MISSING = {
    'categories_other': 'Otros',
    'categories_view_all': 'Ver Todo',
    'filter_availability': 'Disponibilidad',
    'filter_brand': 'Marca',
    'filter_in_stock_only': 'Solo en Stock',
    'filter_min': 'Mín',
    'filter_max': 'Máx',
    'filter_price_range': 'Rango de Precio',
    'quote_phone_optional': 'Teléfono (opcional)',
}

JA_MISSING = {
    'addr_title': '住所簿',
    'addr_subtitle': '配送先と請求先住所の管理',
    'addr_add_address': '住所を追加',
    'addr_new_address': '新しい住所',
    'addr_label': '住所ラベル',
    'addr_first_name': '名',
    'addr_last_name': '姓',
    'addr_address1': '住所1',
    'addr_address2': '住所2',
    'addr_city': '市区町村',
    'addr_state': '都道府県',
    'addr_zip': '郵便番号',
    'addr_country': '国',
    'addr_phone_optional': '電話番号（任意）',
    'addr_save': '住所を保存',
    'addr_cancel': 'キャンセル',
    'addr_no_addresses': '保存された住所はありません',
    'addr_add_first': '最初の住所を追加',
    'addr_add_first_desc': '配送先または請求先住所を追加して、より迅速にチェックアウトしましょう。',
    'addr_add_first_btn': '住所を追加',
    'addr_default': 'デフォルト',
    'addr_edit': '編集',
    'addr_delete': '削除',
    'addr_loading': '住所を読み込み中...',
    'quotes_title': 'マイ見積',
    'quotes_subtitle': '提交した見積依頼を確認',
    'quotes_loading': '見積を読み込み中...',
    'quotes_no_quotes': '見積はまだありません',
    'quotes_no_quotes_desc': '見積を依頼すると、ここに表示されます。',
    'quotes_request_new': '見積を依頼',
    'quotes_request_quote': '見積を依頼',
    'quotes_quote_number': '見積番号',
    'quotes_date': '日付',
    'quotes_items': '商品数',
    'quotes_est_total': '見積合計',
    'quotes_status': 'ステータス',
    'quotes_status_pending': '保留中',
    'quotes_status_approved': '承認済み',
    'quotes_status_rejected': '却下',
    'account_order_items': '注文商品',
    'account_orders_appear_here': '注文履歴がここに表示されます',
    'account_orders_desc': '注文履歴と状況を確認する',
    'account_quotes_desc': '提交した見積依頼を確認する',
    'aria_select_language': '言語を選択',
    'auth_already_have': 'アカウントをお持ちの方',
    'auth_auth_failed': '認証に失敗しました',
    'auth_company_optional': '会社名（任意）',
    'auth_create_account_btn': 'アカウント作成',
    'auth_create_account_link': 'アカウント作成',
    'auth_demo_credentials': 'デモ資格情報',
    'auth_demo_email': 'demo@labproglobal.com',
    'auth_demo_mode': 'デモモード',
    'auth_demo_mode_notice': 'デモ資格情報を使用しています',
    'auth_demo_mode_setup': 'DATABASE_URL と NEXTAUTH_SECRET を設定して本格的な認証を有効にする',
    'auth_demo_password': 'demo123',
    'auth_env_setup_notice': '環境変数を設定して認証を有効にしてください',
    'auth_join_desc': 'LabProGlobal を信頼する何千ものラボに参加しましょう',
    'auth_name': '名前',
    'auth_or_continue': 'または次で続行',
    'auth_sign_in': 'ログイン',
    'auth_sign_in_link': 'ログイン',
    'auth_sign_in_subtitle': 'アカウントにログイン',
    'auth_sign_up': '新規登録',
    'auth_signing_in': 'ログイン中...',
    'auth_welcome_back': 'おかえりなさい',
    'auth_enter_password': 'パスワードを入力',
    'brands_browse_all': 'すべてのブランドを見る',
    'brands_count': '{count}ブランド',
    'brands_no_brands': 'ブランドが見つかりません',
    'brands_no_products': 'このブランドの製品がありません',
    'brands_products': '{count}製品',
    'brands_subtitle': 'ブランドで絞り込む',
    'brands_title': 'ブランド',
    'cart_browse_products': '製品を探す',
    'cart_clear': 'カートを空にする',
    'cart_continue_shopping': '買い物を続ける',
    'cart_free_shipping_hint': 'あと{amount}で送料無料',
    'cart_items_count': '{count}点',
    'cart_order_summary': '注文概要',
    'cart_shipping': '配送料',
    'cart_shipping_free': '無料',
    'cart_sku_label': 'SKU',
    'cart_tax': '税金',
    'cart_tax_at_checkout': 'チェックアウト時に計算',
    'cat_Environmental': '環境',
    'cat_Flow_Control': '流量制御',
    'cat_General': '一般',
    'cat_Industrial_Measurement': '工業計測',
    'cat_Laboratory_Equipment': '実験機器',
    'cat_Pumps_Valves': 'ポンプ・バルブ',
    'categories_all_label': 'すべての製品',
    'categories_browse_all': 'すべて見る',
    'categories_next': '次へ',
    'categories_no_products': 'このカテゴリに製品がありません',
    'categories_other': 'その他',
    'categories_page_of': '{total}ページ中{current}ページ',
    'categories_prev': '前へ',
    'categories_products_count': '{count}製品',
    'categories_sort_bar': '並び替え',
    'categories_subcategories': 'サブカテゴリ',
    'categories_subtitle': 'カテゴリで絞り込む',
    'categories_title': 'カテゴリ',
    'categories_view_all': 'すべて見る',
    'filter_availability': '在庫状況',
    'filter_brand': 'ブランド',
    'filter_in_stock_only': '在庫のみ',
    'filter_max': '最大',
    'filter_min': '最小',
    'filter_price_range': '価格帯',
    'footer_account_col': 'マイアカウント',
    'footer_address_book': '住所簿',
    'footer_all_products': 'すべての製品',
    'footer_bulk_orders': '大口注文',
    'footer_create_account': 'アカウント作成',
    'footer_description': '高品質な実験機器をお届けする信頼できるパートナー',
    'footer_my_orders': '注文履歴',
    'footer_my_quotes': '見積履歴',
    'footer_products_col': '製品',
    'footer_quick_links': 'クイックリンク',
    'footer_request_quote': '見積を依頼',
    'footer_returns_refunds': '返品・返金',
    'footer_rights': '全著作権所有',
    'footer_services_col': 'サービス',
    'footer_shipping_policy': '配送ポリシー',
    'footer_sign_in': 'ログイン',
    'footer_technical_support': '技術サポート',
    'hero_cta_quote': '見積を依頼',
    'hero_cta_shop': '製品を見る',
    'hero_subtitle': 'ラボに必要なすべてが見つかる',
    'hero_title': '高品質実験機器',
    'home_cta_button': '見積を依頼',
    'home_cta_subtitle': '24時間以内にご連絡いたします',
    'home_cta_title': 'カスタム見積が必要ですか？',
    'home_featured_subtitle': '厳選された最高品質製品',
    'home_trust_pricing': '価格',
    'home_trust_pricing_desc': '競争力のある透明な価格',
    'home_trust_quality': '品質',
    'home_trust_quality_desc': '高品質保証の製品',
    'home_trust_shipping': '配送',
    'home_trust_shipping_desc': '迅速で安全な配送',
    'home_trust_support': 'サポート',
    'home_trust_support_desc': '24時間365日の専門サポート',
    'nav_free_shipping': '送料無料',
    'product_expert_support': '専門サポート',
    'product_fast_shipping': '迅速配送',
    'product_full_specs': '完全な仕様',
    'product_home': 'ホーム',
    'product_key_specs': '主要仕様',
    'product_products': '製品',
    'product_related': '関連製品',
    'product_returns': '30日間返品可',
    'product_secure_payment': '安全な決済',
    'product_sku_label': 'SKU',
    'products_add_to_cart': 'カートに追加',
    'products_brand': 'ブランド',
    'products_in_stock': '在庫あり',
    'products_lead_time': 'リードタイム',
    'products_on_order': '受注生産',
    'products_out_of_stock': '在庫切れ',
    'products_related': '関連製品',
    'products_request_quote': '見積を依頼',
    'products_sku': 'SKU',
    'products_sort_featured': 'おすすめ',
    'products_sort_newest': '新着順',
    'products_sort_price_asc': '価格：安い順',
    'products_sort_price_desc': '価格：高い順',
    'products_specifications': '仕様',
    'products_title': '製品',
    'products_view_all': 'すべて見る',
    'quote_add_all': 'すべてフォームに追加',
    'quote_browse_products': '製品を探す',
    'quote_cart_items': 'カート内商品',
    'quote_company': '会社名',
    'quote_company_optional': '会社名（任意）',
    'quote_contact_info': '連絡先情報',
    'quote_email': 'メールアドレス',
    'quote_email_required': 'メールアドレスは必須',
    'quote_empty': '見積リストは空です',
    'quote_fill_required': '必須項目をすべて入力してください',
    'quote_full_name_required': '氏名は必須',
    'quote_items_for': '{count}製品',
    'quote_items_label': '製品',
    'quote_items_selected': '{count}製品選択済み',
    'quote_items_selected_label': '件選択中',
    'quote_message': 'メッセージ',
    'quote_name': '氏名',
    'quote_no_items': '製品が選択されていません',
    'quote_notes': '備考',
    'quote_number_label': '#',
    'quote_phone': '電話番号',
    'quote_phone_optional': '電話番号（任意）',
    'quote_response_time': '応答時間',
    'quote_response_value': '24時間以内',
    'quote_review_msg': '送信前に内容を確認',
    'quote_select_product': '製品を選択',
    'quote_sidebar_title': '選択した製品',
    'quote_submit': '送信',
    'quote_submitted_title': '送信完了',
    'quote_submitting': '送信中...',
    'quote_success': '見積依頼が正常に送信されました！',
    'quote_subtitle': 'フォームを入力すると24時間以内にご連絡いたします',
    'quote_title': '見積を依頼',
    'quote_within_24h': '24時間以内にご連絡いたします',
    'search_browse_all': 'すべての製品を見る',
    'search_no_results': '検索結果が見つかりません',
    'search_placeholder_hint': '検索語句を入力...',
    'search_results_count': '{count}件の結果',
    'search_results_for': '検索結果',
    'search_title': '検索',
    'shipping_carrier_col': '運送会社',
    'shipping_carriers': '運送会社',
    'shipping_carriers_desc': 'UPS、FedEx、DHLなどの信頼できる運送会社を使用',
    'shipping_countries': '対応国',
    'shipping_countries_desc': '100カ国以上に配送可能',
    'shipping_delivery_col': 'お届け',
    'shipping_free_text': '条件を満たした注文は送料無料',
    'shipping_free_title': '送料無料',
    'shipping_instock': '在庫あり',
    'shipping_notes_col': '備考',
    'shipping_options': '配送オプション',
    'shipping_processing': '処理中',
    'shipping_quote': '配送見積',
    'shipping_quote_text': '大口注文の配送見積りは別途お問い合わせ',
    'shipping_special': '特別注文',
    'shipping_subtitle': '配送オプションとポリシーについて',
    'shipping_title': '配送ポリシー',
    'shipping_tracking': '追跡',
    'shipping_tracking_desc': 'リアルタイムで追跡情報を提供',
    'support_contact_title': 'お問い合わせ',
    'support_email': 'メール',
    'support_email_desc': '24時間以内にご返信',
    'support_email_label': 'メールアドレス',
    'support_faq': 'よくある質問',
    'support_faq1_a': '当社のウェブサイトから直接ご注文いただけます。製品をカートに追加してチェックアウトに進んでください。',
    'support_faq1_q': '注文の方法を教えてください',
    'support_faq2_a': 'UPS、FedEx、DHLによる通常配送、迅速配送、お急ぎ配送を提供しています。',
    'support_faq2_q': '配送オプションは？',
    'support_faq3_a': '標準 商品您可以在庫urangで開封されていない状態で30日以内に返品できます。詳細については返品ページをご覧ください。',
    'support_faq3_q': '返品ポリシーについて教えてください',
    'support_faq4_a': '製品ページの「見積を依頼」をクリックするか、お問い合わせください。',
    'support_faq4_q': '見積りを依頼するには？',
    'support_faq5_a': 'はい、大口注文には別途お問い合わせください。',
    'support_faq5_q': '大量注文の割引はありますか？',
    'support_livechat': 'ライブチャット',
    'support_livechat_desc': '今すぐエージェントとお話ください',
    'support_message_label': 'メッセージ',
    'support_name_label': 'お名前',
    'support_phone': '電話番号',
    'support_phone_desc': '平日 9:00-18:00',
    'support_send_btn': '送信',
    'support_sent_desc': 'お問い合わせありがとうございます。24時間以内にご返信いたします。',
    'support_sent_title': '送信完了',
    'support_subject_label': '件名',
    'support_subtitle': 'お問い合わせ方法',
    'support_title': 'サポート',
}

with open(r'E:\novatech-store\lib\i18n\translations.ts', encoding='utf-8') as f:
    lines = f.readlines()

def find_insert_point(lang):
    start = end = None
    for i, line in enumerate(lines):
        if re.match(f'^const {lang}:', line):
            start = i
        elif start is not None and (re.match(r'^const \w+:', line) or re.match(r'^export const', line)):
            end = i
            break
    if start is not None and end is None:
        end = len(lines)
    # Find checkout_request_quote line
    for i in range(start, end):
        if re.match(r'^\s+checkout_request_quote:', lines[i]):
            return i + 1
    return end

def add_keys(lang, translations):
    insert_idx = find_insert_point(lang)
    new_lines = []
    for key, value in translations.items():
        safe_val = value.replace("'", "\\'")
        new_lines.append(f"  {key}: '{safe_val}',\n")
    lines[insert_idx:insert_idx] = new_lines
    print(f'{lang}: inserted {len(new_lines)} keys at line {insert_idx+1}')

add_keys('es', ES_MISSING)
add_keys('ja', JA_MISSING)

with open(r'E:\novatech-store\lib\i18n\translations.ts', 'w', encoding='utf-8') as f:
    f.writelines(lines)
print('Done!')
