"""Final clean rebuild of translations.ts - all blocks with exactly 387 keys."""
import sys
sys.stdout.reconfigure(encoding='utf-8')
import re

with open(r'E:\novatech-store\lib\i18n\translations.ts', encoding='utf-8') as f:
    content = f.read()

# Extract TypeDef
tk_match = re.search(r'export type TranslationKeys = \{(.*?)\n\}', content, re.DOTALL)
type_body = tk_match.group(1)
type_keys = set(re.findall(r'^\s+(\w+):', type_body, re.MULTILINE))
print(f"TypeDef keys: {len(type_keys)}")

# Extract EN block
en_match = re.search(r'const en: TranslationKeys = \{(.*?)\n\}', content, re.DOTALL)
en_text = en_match.group(1)
en_dict = {}
for m in re.findall(r"(\w+): '((?:[^'\\]|\\.)*)',", en_text):
    en_dict[m[0]] = m[1].replace("\\'", "'")
print(f"EN keys extracted: {len(en_dict)}")

# Extract ZH block
zh_match = re.search(r'const zh: TranslationKeys = \{(.*?)\n\}', content, re.DOTALL)
zh_text = zh_match.group(1)
zh_dict = {}
for m in re.findall(r"(\w+): '((?:[^'\\]|\\.)*)',", zh_text):
    zh_dict[m[0]] = m[1].replace("\\'", "'")
print(f"ZH keys extracted: {len(zh_dict)}")

# Ensure auth_email is in ZH
if 'auth_email' not in zh_dict:
    zh_dict['auth_email'] = '电子邮箱'

# Keys from TypeDef, sorted
sorted_keys = sorted(type_keys)

def make_block(name, lang_trans, comment):
    lines = [f'\n// =========================================================\n']
    lines.append(f'//  {comment}\n')
    lines.append(f'// =========================================================\n')
    lines.append(f'const {name}: TranslationKeys = {{\n')
    for k in sorted_keys:
        v = lang_trans.get(k, en_dict.get(k, ''))
        # Escape single quotes
        v = v.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"  {k}: '{v}',\n")
    lines.append('}\n')
    return ''.join(lines)

# All translations (ES from hardcoded, JA from hardcoded, others from EN)
ES_VALS = {
    'auth_email': 'Correo electrónico',
    'addr_title': 'Direcciones',
    'addr_subtitle': 'Gestione sus direcciones de envío y facturación',
    'addr_add_address': 'Añadir dirección',
    'addr_new_address': 'Nueva dirección',
    'addr_label': 'Etiqueta de dirección',
    'addr_first_name': 'Nombre',
    'addr_last_name': 'Apellido',
    'addr_address1': 'Dirección línea 1',
    'addr_address2': 'Dirección línea 2',
    'addr_city': 'Ciudad',
    'addr_state': 'Estado / Provincia',
    'addr_zip': 'Código postal',
    'addr_country': 'País',
    'addr_phone_optional': 'Teléfono (opcional)',
    'addr_save': 'Guardar dirección',
    'addr_cancel': 'Cancelar',
    'addr_no_addresses': 'Sin direcciones guardadas',
    'addr_add_first': 'Añade tu primera dirección',
    'addr_add_first_desc': 'Añade una dirección de envío o facturación para un pago más rápido.',
    'addr_add_first_btn': 'Añadir dirección',
    'addr_default': 'Por defecto',
    'addr_edit': 'Editar',
    'addr_delete': 'Eliminar',
    'addr_loading': 'Cargando direcciones...',
    'quotes_title': 'Mis Cotizaciones',
    'quotes_subtitle': 'Ver sus solicitudes de cotización enviadas',
    'quotes_loading': 'Cargando cotizaciones...',
    'quotes_no_quotes': 'Sin cotizaciones aún',
    'quotes_no_quotes_desc': 'Cuando envíe una solicitud de cotización, aparecerá aquí.',
    'quotes_request_new': 'Solicitar cotización',
    'quotes_request_quote': 'Solicitar cotización',
    'quotes_quote_number': 'Cotización #',
    'quotes_date': 'Fecha',
    'quotes_items': 'Artículos',
    'quotes_est_total': 'Total estimado',
    'quotes_status': 'Estado',
    'quotes_status_pending': 'Pendiente',
    'quotes_status_approved': 'Aprobada',
    'quotes_status_rejected': 'Rechazada',
    'categories_other': 'Otros',
    'categories_view_all': 'Ver Todo',
    'filter_availability': 'Disponibilidad',
    'filter_brand': 'Marca',
    'filter_in_stock_only': 'Solo en Stock',
    'filter_min': 'Mín',
    'filter_max': 'Máx',
    'filter_price_range': 'Rango de Precio',
    'quote_phone_optional': 'Teléfono (opcional)',
}

# Merge EN with ES-specific
ES = dict(en_dict)
ES.update(ES_VALS)

# JA: hardcoded
JA = {
    'nav_search_placeholder': '製品名、SKU、またはブランドで検索...',
    'nav_get_quote': '見積もり依頼',
    'nav_sign_in': 'ログイン',
    'nav_my_account': 'マイアカウント',
    'nav_orders': '注文履歴',
    'nav_sign_out': 'ログアウト',
    'nav_all_products': '全製品',
    'nav_all_categories': '全カテゴリー',
    'nav_cart': 'カート',
    'nav_view_all': 'すべて表示',
    'nav_free_shipping': '送料無料（$500以上）',
    'cart_title': 'カート',
    'cart_empty': 'カートは空です',
    'cart_empty_desc': '製品をカートに追加してください',
    'cart_continue': '買い物を続ける',
    'cart_checkout': 'チェックアウト',
    'cart_subtotal': '小計',
    'cart_quantity': '数量',
    'cart_remove': '削除',
    'cart_item_added': '製品をカートに追加しました',
    'cart_total': '合計',
    'cart_request_quote': '見積を依頼',
    'cart_estimated_shipping': '配送料見込',
    'cart_free_shipping': '無料',
    'cart_final_total': '合計金額',
    'cart_browse_products': '製品を探す',
    'cart_clear': 'カートを空にする',
    'cart_continue_shopping': '買い物を続ける',
    'cart_free_shipping_hint': 'あと{amount}で送料無料',
    'cart_items_count': '{count}点',
    'cart_order_summary': '注文概要',
    'cart_shipping': '配送料',
    'cart_shipping_free': '無料',
    'cart_sku_label': 'SKU',
    'cart_tax': '税金',
    'cart_tax_at_checkout': 'チェックアウト時に計算',
    'account_title': 'マイアカウント',
    'account_welcome': 'おかえりなさい',
    'account_sign_in': 'ログイン',
    'account_register': 'アカウント作成',
    'account_email': 'メールアドレス',
    'account_password': 'パスワード',
    'account_remember_me': 'ログイン状態を保存',
    'account_forgot_password': 'パスワードをお忘れですか？',
    'account_no_account': 'アカウントをお持ちでない方',
    'account_have_account': 'すでにアカウントをお持ちの方',
    'account_sign_in_title': 'ログイン',
    'account_register_title': 'アカウント作成',
    'account_orders': '注文履歴',
    'account_quotes': '見積履歴',
    'account_addresses': '住所',
    'account_settings': '設定',
    'account_logout': 'ログアウト',
    'account_first_name': '名',
    'account_last_name': '姓',
    'account_company': '会社名',
    'account_phone': '電話番号',
    'account_addresses_desc': '住所を管理',
    'account_browse_products': '製品を探す',
    'account_no_orders': '注文履歴なし',
    'account_order_date': '注文日',
    'account_order_status': '注文状況',
    'account_order_total': '注文合計',
    'account_order_view': '詳細を見る',
    'account_order_items': '注文商品',
    'account_orders_appear_here': '注文を行うとここに表示されます',
    'account_orders_desc': '注文履歴と状況を確認',
    'account_quotes_desc': '見積依頼履歴を確認',
    'checkout_title': 'チェックアウト',
    'checkout_steps_title': 'チェックアウト手順',
    'checkout_step1': 'カート',
    'checkout_step2': '配送',
    'checkout_step3': '確認',
    'checkout_back_cart': 'カートに戻る',
    'checkout_not_configured': 'チェックアウトはまだ設定されていません。見積を依頼してください。',
    'checkout_request_quote': '見積を依頼',
    'addr_title': '住所簿',
    'addr_subtitle': '配送先と請求先住所の管理',
    'addr_add_address': '住所を追加',
    'addr_new_address': '新しい住所',
    'addr_label': '住所ラベル',
    'addr_first_name': '名',
    'addr_last_name': '姓',
    'addr_address1': '住所1',
    'addr_address2': '住所2',
    'addr_city': '市区町村',
    'addr_state': '都道府県',
    'addr_zip': '郵便番号',
    'addr_country': '国',
    'addr_phone_optional': '電話番号（任意）',
    'addr_save': '住所を保存',
    'addr_cancel': 'キャンセル',
    'addr_no_addresses': '保存された住所はありません',
    'addr_add_first': '最初の住所を追加',
    'addr_add_first_desc': '配送先または請求先住所を追加して、より迅速にチェックアウトしましょう。',
    'addr_add_first_btn': '住所を追加',
    'addr_default': 'デフォルト',
    'addr_edit': '編集',
    'addr_delete': '削除',
    'addr_loading': '住所を読み込み中...',
    'quotes_title': 'マイ見積',
    'quotes_subtitle': '見積依頼履歴を確認',
    'quotes_loading': '見積を読み込み中...',
    'quotes_no_quotes': '見積依頼履歴なし',
    'quotes_no_quotes_desc': '見積を依頼すると、ここに表示されます',
    'quotes_request_new': '見積を依頼',
    'quotes_request_quote': '見積を依頼',
    'quotes_quote_number': '見積番号',
    'quotes_date': '日付',
    'quotes_items': '商品数',
    'quotes_est_total': '見積合計',
    'quotes_status': 'ステータス',
    'quotes_status_pending': '保留中',
    'quotes_status_approved': '承認済み',
    'quotes_status_rejected': '却下',
    'contact_title': 'お問い合わせ',
    'contact_desc': 'ご質問がありますか？お手伝いします。',
    'contact_form_title': 'メッセージを送る',
    'contact_name': 'お名前',
    'contact_email': 'メールアドレス',
    'contact_phone': '電話番号',
    'contact_company': '会社名',
    'contact_subject': '件名',
    'contact_message': 'メッセージ',
    'contact_send': '送信',
    'contact_office_hours': '営業時間',
    'contact_response_time': '24時間以内にご返信いたします',
    'contact_address': '住所',
    'contact_phone_label': '電話番号',
    'contact_email_label': 'メールアドレス',
    'auth_login_title': 'ログイン',
    'auth_login_desc': '注文管理と見積依頼にログインしてください',
    'auth_login_button': 'ログイン',
    'auth_register_title': 'アカウント作成',
    'auth_register_desc': 'LabProGlobalアカウントを作成して注文管理和見積依頼',
    'auth_email': 'メールアドレス',
    'auth_password': 'パスワード',
    'auth_confirm_password': 'パスワード確認',
    'auth_forgot_password': 'パスワードをお忘れですか？',
    'auth_reset_title': 'パスワードリセット',
    'auth_reset_desc': 'メールアドレスを入力してください',
    'auth_reset_button': 'リンクを送信',
    'auth_reset_success': 'リセットメールを送信しました',
    'auth_reset_error': 'このメールアドレスのアカウントが見つかりません',
    'auth_no_account': 'アカウントをお持ちでない方',
    'auth_have_account': 'すでにアカウントをお持ちの方',
    'auth_create_account': 'アカウント作成',
    'auth_login_google': 'Googleでログイン',
    'auth_or': 'または',
    'auth_min_password': '8文字以上',
    'auth_invalid_credentials': '認証情報が無効です',
    'auth_email_required': 'メールアドレスは必須',
    'auth_password_required': 'パスワードは必須',
    'auth_passwords_match': 'パスワードが一致しません',
    'auth_invalid_email': '無効なメールアドレス',
    'auth_login_success': 'ログインしました',
    'auth_logout_success': 'ログアウトしました',
    'auth_auth_failed': '認証に失敗しました',
    'auth_company_optional': '会社名（任意）',
    'auth_create_account_btn': 'アカウント作成',
    'auth_create_account_link': 'アカウント作成',
    'auth_join_desc': 'LabProGlobalを信頼する何千ものラボに参加しましょう',
    'auth_name': 'お名前',
    'auth_or_continue': 'または次で続行',
    'auth_sign_in': 'ログイン',
    'auth_sign_in_link': 'ログイン',
    'auth_sign_in_subtitle': 'アカウントにログイン',
    'auth_sign_up': '新規登録',
    'auth_signing_in': 'ログイン中...',
    'auth_welcome_back': 'おかえりなさい',
    'auth_enter_password': 'パスワードを入力',
    'auth_demo_mode': 'デモモード',
    'auth_demo_mode_notice': 'デモ資格情報を使用しています',
    'auth_demo_mode_setup': 'DATABASE_URL と NEXTAUTH_SECRET を設定してください',
    'auth_demo_credentials': 'デモ資格情報',
    'auth_demo_email': 'demo@labproglobal.com',
    'auth_demo_password': 'demo123',
    'auth_env_setup_notice': '環境変数を設定してください',
    'auth_already_have': 'アカウントをお持ちの方',
    'footer_company': 'LabProGlobal',
    'footer_tagline': '高品質な実験機器をお届けする信頼できるパートナー',
    'footer_contact': 'お問い合わせ',
    'footer_newsletter': 'ニュースレター',
    'footer_newsletter_desc': '最新ニュースと特別オファーをお届けします',
    'footer_email': 'メールアドレス',
    'footer_subscribe': '購読する',
    'footer_categories': 'カテゴリー',
    'footer_support': 'サポート',
    'footer_about': '会社概要',
    'footer_help': 'ヘルプセンター',
    'footer_returns': '返品',
    'footer_shipping': '配送',
    'footer_faq': 'よくある質問',
    'footer_contact_us': 'お問い合わせ',
    'footer_legal': '法的情報',
    'footer_privacy': 'プライバシーポリシー',
    'footer_terms': '利用規約',
    'footer_returns_policy': '返品ポリシー',
    'footer_copyright': '© 2024 LabProGlobal. All rights reserved.',
    'footer_all_rights': '全著作権所有',
    'footer_description': '高品質な実験機器をお届けする信頼できるパートナー',
    'footer_account_col': 'マイアカウント',
    'footer_products_col': '製品',
    'footer_services_col': 'サービス',
    'footer_quick_links': 'クイックリンク',
    'footer_all_products': 'すべての製品',
    'footer_sign_in': 'ログイン',
    'footer_create_account': 'アカウント作成',
    'footer_my_orders': '注文履歴',
    'footer_my_quotes': '見積履歴',
    'footer_address_book': '住所簿',
    'footer_bulk_orders': '大口注文',
    'footer_request_quote': '見積を依頼',
    'footer_technical_support': '技術サポート',
    'footer_shipping_policy': '配送ポリシー',
    'footer_returns_refunds': '返品・返金',
    'footer_rights': '全著作権所有',
    'terms_title': '利用規約',
    'terms_last_updated': '最終更新日:',
    'terms_section1': '1. 利用規約の受け入れ',
    'terms_section2': '2. サービスと製品',
    'terms_section3': '3. ユーザーアカウント',
    'terms_section4': '4. 注文と価格',
    'terms_section5': '5. 配送と配達',
    'terms_section6': '6. 返品と返金',
    'terms_section7': '7. 責任',
    'terms_section8': '8. 知的所有権',
    'terms_section9': '9. 適用法',
    'terms_section10': '10. お問い合わせ',
    'terms_item1': '本网站にアクセスまたは本站示を利用することで、本利用規約に同意したものとみなされます。',
    'terms_item2': ' лабораторные оборудованиеと試薬を提供する',
    'terms_item3': 'アカウントとパスワードの機密性を維持する責任は您您にあります。',
    'terms_item4': '表示価格は米ドルで、予告なく変更される場合があります。',
    'terms_item5': '配送日時はあくまで目安です。',
    'terms_item6': '返品ポリシーについては、詳細をご覧ください。',
    'terms_item7': '法律により認められる最大限において、間接的または結果的損害について責任を負いません。',
    'terms_item8': '本网站のすべての内容はLabProGlobalの財産です。',
    'terms_item9': '本利用規約は、米国デラウェア州の法律に準拠します。',
    'terms_item10': 'ご質問はlegal@labproglobal.comまでご連絡ください。',
    'privacy_title': 'プライバシーポリシー',
    'privacy_last_updated': '最終更新日:',
    'privacy_section1': '1. 当社が収集する情報',
    'privacy_section2': '2. 当社が情報を使用する目的',
    'privacy_section3': '3. 情報の共有',
    'privacy_section4': '4. データセキュリティ',
    'privacy_section5': '5. Cookie',
    'privacy_section6': '6. お客様の権利',
    'privacy_section7': '7. お問い合わせ',
    'privacy_item1a': '連絡先情報（名前、メール、電話会社名）',
    'privacy_item1b': '配送先と請求先の住所',
    'privacy_item1c': '注文履歴と取引詳細',
    'privacy_item1d': '見積依頼とご連絡履歴',
    'privacy_item1e': '使用データと分析',
    'privacy_item1f': '당사 网站 및 서비스 개선',
    'privacy_item2a': '당사는 개인 정보를 판매하지 않습니다.',
    'privacy_item2b': '당사는 업계 표준 보안 Measures를実装しています。',
    'privacy_item2c': ' 쿠키를 사용하여 장바구니를 유지하고',
    'privacy_item3': '개인 데이터 접근, 수정, 삭제 권리가 있습니다.',
    'privacy_item4': '개인정보 관련 문의는 privacy@labproglobal.com으로 연락주세요.',
    'privacy_item5': '모든 데이터는 암호화된 서버에 안전하게 저장됩니다.',
    'privacy_item6': '계정 및 데이터 삭제를 요청할 수 있습니다.',
    'privacy_item7': '관련 데이터 보호 법률을 준수합니다.',
    'returns_title': '返品・返金',
    'returns_subtitle': 'ご購入にご満足いただけることをお約束します。',
    'returns_30day': '30日間返品可',
    'returns_30day_desc': '標準品は無毃・未使用の場合、受領後30日以内に返品可能',
    'returns_easy': '簡単なプロセス',
    'returns_easy_desc': 'アカウントから返品をリクエスト',
    'returns_full': '全額返金',
    'returns_full_desc': '5〜7営業日以内に返金処理',
    'returns_policy': '返品ポリシー',
    'returns_policy_standard': '標準製品：無毃・未使用状態であれば30日以内に全額返金。',
    'returns_policy_special': '特別注文：欠陥がある場合のみ返品可。',
    'returns_policy_defective': '欠陥製品：直ちにでください。無料交換または返金。',
    'returns_policy_shipping': '返品送料：客户負担。',
    'returns_how': 'アイテムを返品する方法',
    'returns_step1': 'アカウントにログインし注文履歴へ',
    'returns_step2': '返品したい注文と商品を選択',
    'returns_step3': '理由を選択し、リクエストを送信',
    'returns_step4': '返品許可と shipping ラベルを受け取る',
    'returns_step5': '商品を安全に梱包し返送',
    'returns_step6': '返品処理完了後、返金を受け取る',
    'returns_contact': '返品部門에 문의',
    'returns_need_help': '返品についてのお問い合わせ',
    'products_page_title': 'すべての製品',
    'products_results_count': '{count}件の製品が見つかりました',
    'products_showing_range': '{total}件中{from}〜{to}件を表示',
    'products_no_results': '製品が見つかりません',
    'products_prev': '前へ',
    'products_next': '次へ',
    'products_add_to_cart': 'カートに追加',
    'products_brand': 'ブランド',
    'products_in_stock': '在庫あり',
    'products_out_of_stock': '在庫切れ',
    'products_on_order': '受注生産',
    'products_lead_time': 'リードタイム',
    'products_sku': 'SKU',
    'products_related': '関連製品',
    'products_request_quote': '見積を依頼',
    'products_specifications': '仕様',
    'products_title': '製品',
    'products_view_all': 'すべて見る',
    'products_sort_featured': 'おすすめ',
    'products_sort_newest': '新着順',
    'products_sort_price_asc': '価格：安い順',
    'products_sort_price_desc': '価格：高い順',
    'product_sku_label': 'SKU',
    'product_key_specs': '主要仕様',
    'product_full_specs': '完全な仕様',
    'product_expert_support': '専門サポート',
    'product_fast_shipping': '迅速配送',
    'product_secure_payment': '安全な決済',
    'product_returns': '30日間返品可',
    'product_home': 'ホーム',
    'product_products': '製品',
    'product_related': '関連製品',
    'home_hero_title': '高品質実験機器',
    'home_hero_subtitle': 'ラボに必要なすべてが見つかる',
    'home_hero_button': '製品を見る',
    'home_hero_quote': '見積を依頼',
    'home_featured': '注目の製品',
    'home_categories': '人気のカテゴリー',
    'home_why': '選ばれる理由',
    'home_quality': '品質保証',
    'home_quality_desc': 'すべての製品は国際品質基準を満たしています',
    'home_pricing': '競争力のある価格',
    'home_pricing_desc': '透明な価格で追加料金なし',
    'home_shipping': '迅速配送',
    'home_shipping_desc': 'リアルタイム追跡で安全・迅速な配送',
    'home_support': '専門サポート',
    'home_support_desc': '専門家チームがご質問にお答えします',
    'home_view_all': 'すべて見る',
    'home_view_product': '詳細を見る',
    'home_add_to_cart': 'カートに追加',
    'home_get_quote': '見積を依頼',
    'home_learn_more': '詳細を見る',
    'home_featured_title': '注目の製品',
    'home_featured_desc': '高品質実験機器のセレクション',
    'home_featured_subtitle': 'お客様のために選んだ最高の製品',
    'home_categories_title': '人気のカテゴリー',
    'home_categories_desc': '必要なものを正確に見つける',
    'home_about_title': '会社概要',
    'home_about_p1': 'LabProGlobalは高品質な実験機器・試薬の大手提供商です。',
    'home_about_p2': '長年の経験を持ち、精密機器、流量ソリューション、分析機器を提供',
    'home_about_p3': '私たちの使命は、科学の発展を支援することです。',
    'home_about_btn': '詳細を見る',
    'home_trust': '信頼の構築',
    'home_trust_p1': '世界中の何千ものラボがLabProGlobalを信頼',
    'home_trust_p2': '品質、透明性、顧客満足を追求',
    'home_trust_p3': '専任のチームがお客様のサポートに',
    'home_newsletter_title': 'ニュースレター',
    'home_newsletter_desc': '最新ニュース、特別オファーをお届けします',
    'home_newsletter_placeholder': 'メールアドレス',
    'home_newsletter_button': '購読する',
    'home_newsletter_success': '購読ありがとうございます！',
    'home_cta_title': 'カスタム見積が必要ですか？',
    'home_cta_subtitle': '今すぐ联系我们、24時間以内にご返信',
    'home_cta_button': '見積を依頼',
    'home_trust_quality': '品質',
    'home_trust_quality_desc': '高品質保証の製品',
    'home_trust_pricing': '価格',
    'home_trust_pricing_desc': '競争力のある透明な価格',
    'home_trust_shipping': '配送',
    'home_trust_shipping_desc': '迅速で安全な配送',
    'home_trust_support': 'サポート',
    'home_trust_support_desc': '24時間365日の専門サポート',
    'about_title': '会社概要',
    'about_hero_title': '会社概要',
    'about_hero_subtitle': 'LabProGlobalと私たちの使命について',
    'about_mission_title': '私たちの使命',
    'about_mission_p1': 'LabProGlobalでは、高品質で信頼できる実験機器でラボを支援しています',
    'about_mission_p2': '科学発見を加速するために、研究者と専門家に必要なツールを提供',
    'about_vision_title': '私たちのビジョン',
    'about_vision_p1': '実験機器・試薬の信頼できるパートナーとなること',
    'about_vision_p2': '科学コミュニティの的需求に進化し続ける',
    'about_values_title': '私たちの価値観',
    'about_quality': '品質',
    'about_quality_desc': '厳しい品質基準を満たす製品のみを品揃え',
    'about_innovation': 'イノベーション',
    'about_innovation_desc': 'お客様により良いサービスを提供するため、 新製品を探求',
    'about_integrity': '誠実さ',
    'about_integrity_desc': '正直な価格、透明なポリシー、倫理的なビジネス慣行',
    'about_customers': 'お客様第一',
    'about_customers_desc': 'お客様の成功が私たちの最優先事項',
    'about_team_title': '私たちのチーム',
    'about_team_p1': '実験機器、サプライチェーン管理、カスタマーサービスの専門知識を集結',
    'about_team_p2': '科学に情熱を持ち、お客様の研究・業務目標達成を支援',
    'about_contact_title': 'お問い合わせ',
    'about_contact_p1': 'ご質問やお問い合わせは我们的チームが喜んでお手伝いします',
    'about_contact_p2': 'お問い合わせフォームまたはFAQをご覧ください',
    'search_title': '検索',
    'search_results_for': '検索結果',
    'search_results_count': '{count}件の結果',
    'search_no_results': '検索結果が見つかりません',
    'search_browse_all': 'すべての製品を見る',
    'search_placeholder_hint': '検索語句を入力...',
    'categories_title': 'カテゴリー',
    'categories_subtitle': 'カテゴリーで絞り込む',
    'categories_all_label': 'すべての製品',
    'categories_browse_all': 'すべて見る',
    'categories_subcategories': 'サブカテゴリー',
    'categories_no_products': 'このカテゴリーに製品がありません',
    'categories_prev': '前へ',
    'categories_next': '次へ',
    'categories_products_count': '{count}件の製品',
    'categories_page_of': '{total}ページ中{current}ページ',
    'categories_sort_bar': '並び替え',
    'categories_other': 'その他',
    'categories_view_all': 'すべて見る',
    'brands_title': 'ブランド',
    'brands_subtitle': 'ブランドで絞り込む',
    'brands_products': '{count}件の製品',
    'brands_no_products': 'このブランドの製品がありません',
    'brands_no_brands': 'ブランドが見つかりません',
    'brands_browse_all': 'すべてのブランドを見る',
    'brands_count': '{count}ブランド',
    'shipping_title': '配送ポリシー',
    'shipping_subtitle': '配送オプションとポリシーについて',
    'shipping_options': '配送オプション',
    'shipping_processing': '処理中',
    'shipping_delivery_col': 'お届け',
    'shipping_carriers': '運送会社',
    'shipping_carriers_desc': 'UPS、FedEx、DHLなどの信頼できる運送会社を使用',
    'shipping_countries': '対応国',
    'shipping_countries_desc': '100カ国以上に配送可能',
    'shipping_tracking': '追跡',
    'shipping_tracking_desc': 'リアルタイムで追跡情報を提供',
    'shipping_free_title': '送料無料',
    'shipping_free_text': '条件を満たした注文は送料無料',
    'shipping_quote': '配送見積',
    'shipping_quote_text': '大口注文の配送見積りは別途お問い合わせ',
    'shipping_special': '特別注文',
    'shipping_instock': '在庫あり',
    'shipping_notes_col': '備考',
    'shipping_carrier_col': '運送会社',
    'support_title': 'サポート',
    'support_subtitle': 'お問い合わせ方法',
    'support_contact_title': 'お問い合わせ',
    'support_email': 'メール',
    'support_email_label': 'メールアドレス',
    'support_email_desc': '24時間以内にご返信',
    'support_phone': '電話番号',
    'support_phone_desc': '平日 9:00-18:00',
    'support_livechat': 'ライブチャット',
    'support_livechat_desc': '今すぐエージェントとお話ください',
    'support_faq': 'よくある質問',
    'support_faq1_q': '注文の方法を教えてください',
    'support_faq1_a': '当社のウェブサイトから直接ご注文いただけます',
    'support_faq2_q': '配送オプションは？',
    'support_faq2_a': 'UPS、FedEx、DHLによる通常配送、迅速配送、お急ぎ配送を提供',
    'support_faq3_q': '返品ポリシーについて教えてください',
    'support_faq3_a': '標準 产品は开封されていない状態で30日以内に返品可能',
    'support_faq4_q': '見積りを依頼するには？',
    'support_faq4_a': '製品ページの「見積を依頼」をクリック',
    'support_faq5_q': '大量注文の割引はありますか？',
    'support_faq5_a': 'はい，大口注文には別途お問い合わせください',
    'support_name_label': 'お名前',
    'support_subject_label': '件名',
    'support_message_label': 'メッセージ',
    'support_send_btn': '送信',
    'support_sent_title': '送信完了',
    'support_sent_desc': 'お問い合わせありがとうございます。24時間以内にご返信いたします。',
    'error_title': 'エラー',
    'error_generic': 'エラーが発生しました。もう一度お試しください。',
    'error_404_title': 'ページが見つかりません',
    'error_404_desc': 'お探しのページは存在しないか、移動した可能性があります。',
    'error_404_button': 'ホームに戻る',
    'error_back_home': 'ホームに戻る',
    'aria_language_options': '言語オプション',
    'aria_close_menu': 'メニューを閉じる',
    'aria_open_menu': 'メニューを開く',
    'aria_remove_item': 'アイテムを削除',
    'aria_increase_quantity': '数量を増やす',
    'aria_decrease_quantity': '数量を減らす',
    'aria_select_language': '言語を選択',
    'placeholder_name_example': '山田 太郎',
    'placeholder_company_example': '株式会社サンプル',
    'placeholder_email_example': 'your@email.com',
    'placeholder_phone_example': '+81 3-1234-5678',
    'placeholder_notes_example': '追加のメモをここに入力...',
    'placeholder_search_example': '製品を検索...',
    'cat_Flow_Control': '流量制御',
    'cat_Environmental': '環境',
    'cat_General': '一般',
    'cat_Industrial_Measurement': '工業計測',
    'cat_Laboratory_Equipment': '実験機器',
    'cat_Pumps_Valves': 'ポンプ・バルブ',
    'filter_availability': '在庫状況',
    'filter_brand': 'ブランド',
    'filter_in_stock_only': '在庫のみ',
    'filter_min': '最小',
    'filter_max': '最大',
    'filter_price_range': '価格帯',
    'hero_title': '高品質実験機器',
    'hero_subtitle': 'ラボに必要なすべてが見つかる',
    'hero_cta_shop': '製品を見る',
    'hero_cta_quote': '見積を依頼',
    'quote_title': '見積を依頼',
    'quote_subtitle': 'フォームにご記入いただければ、24時間以内にご連絡いたします',
    'quote_sidebar_title': '選択した製品',
    'quote_items_selected': '{count}件の製品を選択中',
    'quote_select_product': '製品を選択',
    'quote_review_msg': '送信前に内容をご確認ください',
    'quote_submit': '送信',
    'quote_submitting': '送信中...',
    'quote_success': '見積依頼が正常に送信されました！',
    'quote_submitted_title': '送信完了',
    'quote_response_time': '応答時間',
    'quote_response_value': '24時間以内',
    'quote_within_24h': '24時間以内にご連絡いたします',
    'quote_name': '氏名',
    'quote_email': 'メールアドレス',
    'quote_phone': '電話番号',
    'quote_company': '会社名',
    'quote_company_optional': '会社名（任意）',
    'quote_message': 'メッセージ',
    'quote_notes': '備考',
    'quote_items_label': '製品',
    'quote_items_for': '{count}件の製品',
    'quote_items_selected_label': '件選択中',
    'quote_number_label': '#',
    'quote_no_items': '製品が選択されていません',
    'quote_empty': '見積リストは空です',
    'quote_browse_products': '製品を探す',
    'quote_add_all': 'すべてフォームに追加',
    'quote_cart_items': 'カート内商品',
    'quote_contact_info': '連絡先情報',
    'quote_fill_required': '必須項目をすべて入力してください',
    'quote_email_required': 'メールアドレスは必須',
    'quote_full_name_required': '氏名は必須',
    'quote_phone_optional': '電話番号（任意）',
}

# For any missing keys in JA, fall back to EN
for k in sorted_keys:
    if k not in JA:
        JA[k] = en_dict.get(k, f'[{k}]')

# HI, AR, PT: use EN
HI = dict(en_dict)
AR = dict(en_dict)
PT = dict(en_dict)

# Build header
header = """// Translation keys for LabProGlobal
// All keys from TranslationKeys type

export type Locale = 'en' | 'zh' | 'es' | 'ja' | 'hi' | 'ar' | 'pt'

export const LOCALES: { code: Locale; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'zh', label: '中文' },
  { code: 'es', label: 'Español' },
  { code: 'ja', label: '日本語' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'ar', label: 'العربية' },
  { code: 'pt', label: 'Português' },
]

export type TranslationKeys = {
""" + type_body + """
}

"""

footer = """

// =========================================================
//  Translation Data
// =========================================================

export const translations: Record<Locale, TranslationKeys> = {
"""

en_b = make_block('en', en_dict, '英语 (English)')
zh_b = make_block('zh', zh_dict, '简体中文')
es_b = make_block('es', ES, '西班牙语')
ja_b = make_block('ja', JA, '日语')
hi_b = make_block('hi', HI, '印地语 (हिन्दी)')
ar_b = make_block('ar', AR, '阿拉伯语 (RTL)')
pt_b = make_block('pt', PT, '葡萄牙语')

footer += en_b + zh_b + es_b + ja_b + hi_b + ar_b + pt_b + '}\n'

full = header + footer

with open(r'E:\novatech-store\lib\i18n\translations.ts', 'w', encoding='utf-8') as f:
    f.write(full)

print(f"Written {len(full)} chars, {len(full.splitlines())} lines")
print("Done!")
