"""Rebuild translations.ts completely: extract EN as template, rebuild all language blocks."""
import sys
sys.stdout.reconfigure(encoding='utf-8')

# Full EN template - all 387 keys with English values
EN_KEYS_SORTED = [
    'nav_search_placeholder', 'nav_get_quote', 'nav_sign_in', 'nav_my_account',
    'nav_orders', 'nav_sign_out', 'nav_all_products', 'nav_all_categories',
    'nav_cart', 'nav_view_all', 'nav_free_shipping',
    'cart_title', 'cart_empty', 'cart_empty_desc', 'cart_continue',
    'cart_checkout', 'cart_subtotal', 'cart_quantity', 'cart_remove',
    'cart_item_added', 'cart_total', 'cart_request_quote',
    'cart_estimated_shipping', 'cart_free_shipping', 'cart_final_total',
    'cart_browse_products', 'cart_clear', 'cart_continue_shopping',
    'cart_free_shipping_hint', 'cart_items_count', 'cart_order_summary',
    'cart_shipping', 'cart_shipping_free', 'cart_sku_label', 'cart_tax',
    'cart_tax_at_checkout',
    'account_title', 'account_welcome', 'account_sign_in', 'account_register',
    'account_email', 'account_password', 'account_remember_me',
    'account_forgot_password', 'account_no_account', 'account_have_account',
    'account_sign_in_title', 'account_register_title', 'account_orders',
    'account_quotes', 'account_addresses', 'account_settings', 'account_logout',
    'account_first_name', 'account_last_name', 'account_company', 'account_phone',
    'account_addresses_desc', 'account_browse_products', 'account_no_orders',
    'account_order_date', 'account_order_status', 'account_order_total',
    'account_order_view', 'account_order_items', 'account_orders_appear_here',
    'account_orders_desc', 'account_quotes_desc',
    'checkout_title', 'checkout_steps_title', 'checkout_step1', 'checkout_step2',
    'checkout_step3', 'checkout_back_cart', 'checkout_not_configured',
    'checkout_request_quote',
    'addr_title', 'addr_subtitle', 'addr_add_address', 'addr_new_address',
    'addr_label', 'addr_first_name', 'addr_last_name', 'addr_address1',
    'addr_address2', 'addr_city', 'addr_state', 'addr_zip', 'addr_country',
    'addr_phone_optional', 'addr_save', 'addr_cancel', 'addr_no_addresses',
    'addr_add_first', 'addr_add_first_desc', 'addr_add_first_btn',
    'addr_default', 'addr_edit', 'addr_delete', 'addr_loading',
    'quotes_title', 'quotes_subtitle', 'quotes_loading', 'quotes_no_quotes',
    'quotes_no_quotes_desc', 'quotes_request_new', 'quotes_request_quote',
    'quotes_quote_number', 'quotes_date', 'quotes_items', 'quotes_est_total',
    'quotes_status', 'quotes_status_pending', 'quotes_status_approved',
    'quotes_status_rejected',
    'contact_title', 'contact_desc', 'contact_form_title', 'contact_name',
    'contact_email', 'contact_phone', 'contact_company', 'contact_subject',
    'contact_message', 'contact_send', 'contact_office_hours',
    'contact_response_time', 'contact_address', 'contact_phone_label',
    'contact_email_label',
    'auth_login_title', 'auth_login_desc', 'auth_login_button',
    'auth_register_title', 'auth_register_desc', 'auth_email', 'auth_password',
    'auth_confirm_password', 'auth_forgot_password', 'auth_reset_title',
    'auth_reset_desc', 'auth_reset_button', 'auth_reset_success',
    'auth_reset_error', 'auth_no_account', 'auth_have_account',
    'auth_create_account', 'auth_login_google', 'auth_or',
    'auth_min_password', 'auth_invalid_credentials', 'auth_email_required',
    'auth_password_required', 'auth_passwords_match', 'auth_invalid_email',
    'auth_login_success', 'auth_logout_success', 'auth_auth_failed',
    'auth_company_optional', 'auth_create_account_btn', 'auth_create_account_link',
    'auth_join_desc', 'auth_name', 'auth_or_continue', 'auth_sign_in',
    'auth_sign_in_link', 'auth_sign_in_subtitle', 'auth_sign_up',
    'auth_signing_in', 'auth_welcome_back', 'auth_enter_password',
    'auth_demo_mode', 'auth_demo_mode_notice', 'auth_demo_mode_setup',
    'auth_demo_credentials', 'auth_demo_email', 'auth_demo_password',
    'auth_env_setup_notice', 'auth_already_have',
    'footer_company', 'footer_tagline', 'footer_contact', 'footer_newsletter',
    'footer_newsletter_desc', 'footer_email', 'footer_subscribe',
    'footer_categories', 'footer_support', 'footer_about', 'footer_help',
    'footer_returns', 'footer_shipping', 'footer_faq', 'footer_contact_us',
    'footer_legal', 'footer_privacy', 'footer_terms', 'footer_returns_policy',
    'footer_copyright', 'footer_all_rights', 'footer_description',
    'footer_account_col', 'footer_products_col', 'footer_services_col',
    'footer_quick_links', 'footer_all_products', 'footer_sign_in',
    'footer_create_account', 'footer_my_orders', 'footer_my_quotes',
    'footer_address_book', 'footer_bulk_orders', 'footer_request_quote',
    'footer_technical_support', 'footer_shipping_policy',
    'footer_returns_refunds', 'footer_rights',
    'terms_title', 'terms_last_updated', 'terms_section1', 'terms_section2',
    'terms_section3', 'terms_section4', 'terms_section5', 'terms_section6',
    'terms_section7', 'terms_section8', 'terms_section9', 'terms_section10',
    'terms_item1', 'terms_item2', 'terms_item3', 'terms_item4', 'terms_item5',
    'terms_item6', 'terms_item7', 'terms_item8', 'terms_item9', 'terms_item10',
    'privacy_title', 'privacy_last_updated', 'privacy_section1', 'privacy_section2',
    'privacy_section3', 'privacy_section4', 'privacy_section5', 'privacy_section6',
    'privacy_section7', 'privacy_item1a', 'privacy_item1b', 'privacy_item1c',
    'privacy_item1d', 'privacy_item1e', 'privacy_item1f', 'privacy_item2a',
    'privacy_item2b', 'privacy_item2c', 'privacy_item3', 'privacy_item4',
    'privacy_item5', 'privacy_item6', 'privacy_item7',
    'returns_title', 'returns_subtitle', 'returns_30day', 'returns_30day_desc',
    'returns_easy', 'returns_easy_desc', 'returns_full', 'returns_full_desc',
    'returns_policy', 'returns_policy_standard', 'returns_policy_special',
    'returns_policy_defective', 'returns_policy_shipping', 'returns_how',
    'returns_step1', 'returns_step2', 'returns_step3', 'returns_step4',
    'returns_step5', 'returns_step6', 'returns_contact', 'returns_need_help',
    'products_page_title', 'products_results_count', 'products_showing_range',
    'products_no_results', 'products_prev', 'products_next',
    'products_add_to_cart', 'products_brand', 'products_in_stock',
    'products_out_of_stock', 'products_on_order', 'products_lead_time',
    'products_sku', 'products_related', 'products_request_quote',
    'products_specifications', 'products_title', 'products_view_all',
    'products_sort_featured', 'products_sort_newest', 'products_sort_price_asc',
    'products_sort_price_desc',
    'product_sku_label', 'product_key_specs', 'product_full_specs',
    'product_expert_support', 'product_fast_shipping', 'product_secure_payment',
    'product_returns', 'product_home', 'product_products', 'product_related',
    'home_hero_title', 'home_hero_subtitle', 'home_hero_button', 'home_hero_quote',
    'home_featured', 'home_categories', 'home_why', 'home_quality',
    'home_quality_desc', 'home_pricing', 'home_pricing_desc', 'home_shipping',
    'home_shipping_desc', 'home_support', 'home_support_desc', 'home_view_all',
    'home_view_product', 'home_add_to_cart', 'home_get_quote', 'home_learn_more',
    'home_featured_title', 'home_featured_desc', 'home_featured_subtitle',
    'home_categories_title', 'home_categories_desc', 'home_about_title',
    'home_about_p1', 'home_about_p2', 'home_about_p3', 'home_about_btn',
    'home_trust', 'home_trust_p1', 'home_trust_p2', 'home_trust_p3',
    'home_newsletter_title', 'home_newsletter_desc', 'home_newsletter_placeholder',
    'home_newsletter_button', 'home_newsletter_success', 'home_cta_title',
    'home_cta_subtitle', 'home_cta_button', 'home_trust_quality',
    'home_trust_quality_desc', 'home_trust_pricing', 'home_trust_pricing_desc',
    'home_trust_shipping', 'home_trust_shipping_desc', 'home_trust_support',
    'home_trust_support_desc',
    'about_title', 'about_hero_title', 'about_hero_subtitle',
    'about_mission_title', 'about_mission_p1', 'about_mission_p2',
    'about_vision_title', 'about_vision_p1', 'about_vision_p2',
    'about_values_title', 'about_quality', 'about_quality_desc',
    'about_innovation', 'about_innovation_desc', 'about_integrity',
    'about_integrity_desc', 'about_customers', 'about_customers_desc',
    'about_team_title', 'about_team_p1', 'about_team_p2',
    'about_contact_title', 'about_contact_p1', 'about_contact_p2',
    'search_title', 'search_results_for', 'search_results_count',
    'search_no_results', 'search_browse_all', 'search_placeholder_hint',
    'categories_title', 'categories_subtitle', 'categories_all_label',
    'categories_browse_all', 'categories_subcategories', 'categories_no_products',
    'categories_prev', 'categories_next', 'categories_products_count',
    'categories_page_of', 'categories_sort_bar', 'categories_other',
    'categories_view_all',
    'brands_title', 'brands_subtitle', 'brands_products', 'brands_no_products',
    'brands_no_brands', 'brands_browse_all', 'brands_count',
    'shipping_title', 'shipping_subtitle', 'shipping_options', 'shipping_processing',
    'shipping_delivery_col', 'shipping_carriers', 'shipping_carriers_desc',
    'shipping_countries', 'shipping_countries_desc', 'shipping_tracking',
    'shipping_tracking_desc', 'shipping_free_title', 'shipping_free_text',
    'shipping_quote', 'shipping_quote_text', 'shipping_special',
    'shipping_instock', 'shipping_notes_col', 'shipping_carrier_col',
    'support_title', 'support_subtitle', 'support_contact_title',
    'support_email', 'support_email_label', 'support_email_desc',
    'support_phone', 'support_phone_desc', 'support_livechat',
    'support_livechat_desc', 'support_faq', 'support_faq1_q', 'support_faq1_a',
    'support_faq2_q', 'support_faq2_a', 'support_faq3_q', 'support_faq3_a',
    'support_faq4_q', 'support_faq4_a', 'support_faq5_q', 'support_faq5_a',
    'support_name_label', 'support_subject_label', 'support_message_label',
    'support_send_btn', 'support_sent_title', 'support_sent_desc',
    'error_title', 'error_generic', 'error_404_title', 'error_404_desc',
    'error_404_button', 'error_back_home',
    'aria_language_options', 'aria_close_menu', 'aria_open_menu',
    'aria_remove_item', 'aria_increase_quantity', 'aria_decrease_quantity',
    'aria_select_language',
    'placeholder_name_example', 'placeholder_company_example',
    'placeholder_email_example', 'placeholder_phone_example',
    'placeholder_notes_example', 'placeholder_search_example',
    'cat_Flow_Control', 'cat_Environmental', 'cat_General',
    'cat_Industrial_Measurement', 'cat_Laboratory_Equipment', 'cat_Pumps_Valves',
    'filter_availability', 'filter_brand', 'filter_in_stock_only',
    'filter_min', 'filter_max', 'filter_price_range',
    'hero_title', 'hero_subtitle', 'hero_cta_shop', 'hero_cta_quote',
    'quote_title', 'quote_subtitle', 'quote_sidebar_title', 'quote_items_selected',
    'quote_select_product', 'quote_review_msg', 'quote_submit', 'quote_submitting',
    'quote_success', 'quote_submitted_title', 'quote_response_time',
    'quote_response_value', 'quote_within_24h', 'quote_name', 'quote_email',
    'quote_phone', 'quote_company', 'quote_company_optional', 'quote_message',
    'quote_notes', 'quote_items_label', 'quote_items_for',
    'quote_items_selected_label', 'quote_number_label', 'quote_no_items',
    'quote_empty', 'quote_browse_products', 'quote_add_all', 'quote_cart_items',
    'quote_contact_info', 'quote_fill_required', 'quote_email_required',
    'quote_full_name_required', 'quote_phone_optional',
]

# Remove duplicates while preserving order
seen = set()
EN_KEYS = []
for k in EN_KEYS_SORTED:
    if k not in seen:
        seen.add(k)
        EN_KEYS.append(k)

print(f"Total EN keys: {len(EN_KEYS)}")

# All translations (ZH from existing file, others as EN fallback)
ZH = {}  # Will be extracted from existing file
EN = {}  # Will be extracted from existing file
ES = {}
JA = {}
HI = {}
AR = {}
PT = {}

# Extract EN and ZH from existing file
with open(r'E:\novatech-store\lib\i18n\translations.ts', encoding='utf-8') as f:
    content = f.read()

import re

# Extract EN block
en_match = re.search(r'const en: TranslationKeys = \{(.*?)\n\}', content, re.DOTALL)
if en_match:
    en_text = en_match.group(1)
    for m in re.findall(r"(\w+): '([^']*)',", en_text):
        EN[m[0]] = m[1]
print(f"Extracted EN: {len(EN)} keys")

# Extract ZH block
zh_match = re.search(r'const zh: TranslationKeys = \{(.*?)\n\}', content, re.DOTALL)
if zh_match:
    zh_text = zh_match.group(1)
    for m in re.findall(r"(\w+): '([^']*)',", zh_text):
        ZH[m[0]] = m[1]
print(f"Extracted ZH: {len(ZH)} keys")

# ZH-only translations for zh values
ZH_EXTRAS = {
    'auth_email': '电子邮箱',
    'privacy_item4': '如需隐私相关咨询，请联系我们的数据保护官',
}

# Spanish translations
ES = {
    'nav_search_placeholder': 'Buscar por nombre de producto, SKU o marca...',
    'nav_get_quote': 'Obtener Cotización',
    'nav_sign_in': 'Iniciar Sesión',
    'nav_my_account': 'Mi Cuenta',
    'nav_orders': 'Pedidos',
    'nav_sign_out': 'Cerrar Sesión',
    'nav_all_products': 'Todos los Productos',
    'nav_all_categories': 'Todas las Categorías',
    'nav_cart': 'Carrito',
    'nav_view_all': 'Ver Todo',
    'nav_free_shipping': 'Envío Gratuito en pedidos de más de $500',
    'cart_title': 'Carrito de Compras',
    'cart_empty': 'Tu carrito está vacío',
    'cart_empty_desc': 'Explore nuestros productos y añada artículos a su carrito.',
    'cart_continue': 'Continuar Comprando',
    'cart_checkout': 'Proceder al Pago',
    'cart_subtotal': 'Subtotal',
    'cart_quantity': 'Cantidad',
    'cart_remove': 'Eliminar',
    'cart_item_added': 'Producto añadido al carrito',
    'cart_total': 'Total',
    'cart_request_quote': 'Solicitar Cotización',
    'cart_estimated_shipping': 'Envío estimado',
    'cart_free_shipping': 'GRATIS',
    'cart_final_total': 'Total Final',
    'cart_browse_products': 'Explorar Productos',
    'cart_clear': 'Vaciar Carrito',
    'cart_continue_shopping': 'Continuar Comprando',
    'cart_free_shipping_hint': 'Añada {amount} más para envío gratuito',
    'cart_items_count': '{count} artículos',
    'cart_order_summary': 'Resumen del Pedido',
    'cart_shipping': 'Envío',
    'cart_shipping_free': 'GRATIS',
    'cart_sku_label': 'SKU',
    'cart_tax': 'Impuestos',
    'cart_tax_at_checkout': 'Impuestos calculados en el pago',
    'account_title': 'Mi Cuenta',
    'account_welcome': 'Bienvenido de nuevo',
    'account_sign_in': 'Iniciar Sesión',
    'account_register': 'Crear Cuenta',
    'account_email': 'Correo Electrónico',
    'account_password': 'Contraseña',
    'account_remember_me': 'Recuérdame',
    'account_forgot_password': '¿Olvidó su contraseña?',
    'account_no_account': '¿No tiene cuenta?',
    'account_have_account': '¿Ya tiene cuenta?',
    'account_sign_in_title': 'Iniciar Sesión en Su Cuenta',
    'account_register_title': 'Crear una Cuenta',
    'account_orders': 'Mis Pedidos',
    'account_quotes': 'Mis Cotizaciones',
    'account_addresses': 'Direcciones',
    'account_settings': 'Configuración',
    'account_logout': 'Cerrar Sesión',
    'account_first_name': 'Nombre',
    'account_last_name': 'Apellidos',
    'account_company': 'Empresa',
    'account_phone': 'Teléfono',
    'account_addresses_desc': 'Gestione sus direcciones de envío y facturación',
    'account_browse_products': 'Explorar Productos',
    'account_no_orders': 'Aún no hay pedidos',
    'account_order_date': 'Fecha del pedido',
    'account_order_status': 'Estado del pedido',
    'account_order_total': 'Total del pedido',
    'account_order_view': 'Ver pedido',
    'account_order_items': 'Artículos del pedido',
    'account_orders_appear_here': 'Sus pedidos aparecerán aquí',
    'account_orders_desc': 'Vea el historial y el estado de sus pedidos',
    'account_quotes_desc': 'Vea sus solicitudes de cotización enviadas',
    'checkout_title': 'Pago',
    'checkout_steps_title': 'Pasos de Pago',
    'checkout_step1': 'Carrito',
    'checkout_step2': 'Envío',
    'checkout_step3': 'Revisar',
    'checkout_back_cart': 'Volver al Carrito',
    'checkout_not_configured': 'El pago aún no está configurado. Solicite una cotización.',
    'checkout_request_quote': 'Solicitar Cotización',
    'addr_title': 'Direcciones',
    'addr_subtitle': 'Gestione sus direcciones de envío y facturación',
    'addr_add_address': 'Añadir dirección',
    'addr_new_address': 'Nueva dirección',
    'addr_label': 'Etiqueta de dirección',
    'addr_first_name': 'Nombre',
    'addr_last_name': 'Apellido',
    'addr_address1': 'Dirección línea 1',
    'addr_address2': 'Dirección línea 2',
    'addr_city': 'Ciudad',
    'addr_state': 'Estado / Provincia',
    'addr_zip': 'Código postal',
    'addr_country': 'País',
    'addr_phone_optional': 'Teléfono (opcional)',
    'addr_save': 'Guardar dirección',
    'addr_cancel': 'Cancelar',
    'addr_no_addresses': 'Sin direcciones guardadas',
    'addr_add_first': 'Añade tu primera dirección',
    'addr_add_first_desc': 'Añade una dirección de envío o facturación para un pago más rápido.',
    'addr_add_first_btn': 'Añadir dirección',
    'addr_default': 'Por defecto',
    'addr_edit': 'Editar',
    'addr_delete': 'Eliminar',
    'addr_loading': 'Cargando direcciones...',
    'quotes_title': 'Mis Cotizaciones',
    'quotes_subtitle': 'Ver sus solicitudes de cotización enviadas',
    'quotes_loading': 'Cargando cotizaciones...',
    'quotes_no_quotes': 'Sin cotizaciones aún',
    'quotes_no_quotes_desc': 'Cuando envíe una solicitud de cotización, aparecerá aquí.',
    'quotes_request_new': 'Solicitar cotización',
    'quotes_request_quote': 'Solicitar cotización',
    'quotes_quote_number': 'Cotización #',
    'quotes_date': 'Fecha',
    'quotes_items': 'Artículos',
    'quotes_est_total': 'Total estimado',
    'quotes_status': 'Estado',
    'quotes_status_pending': 'Pendiente',
    'quotes_status_approved': 'Aprobada',
    'quotes_status_rejected': 'Rechazada',
    'contact_title': 'Contáctenos',
    'contact_desc': '¿Tiene preguntas? Estamos aquí para ayudar.',
    'contact_form_title': 'Envíenos un mensaje',
    'contact_name': 'Nombre completo',
    'contact_email': 'Correo electrónico',
    'contact_phone': 'Teléfono',
    'contact_company': 'Empresa',
    'contact_subject': 'Asunto',
    'contact_message': 'Mensaje',
    'contact_send': 'Enviar Mensaje',
    'contact_office_hours': 'Horario de oficina',
    'contact_response_time': 'Nos comprometemos a responder en 24 horas',
    'contact_address': 'Dirección',
    'contact_phone_label': 'Teléfono',
    'contact_email_label': 'Correo electrónico',
    'auth_login_title': 'Iniciar Sesión',
    'auth_login_desc': 'Inicie sesión para gestionar sus pedidos y solicitudes de cotización.',
    'auth_login_button': 'Iniciar Sesión',
    'auth_register_title': 'Crear Cuenta',
    'auth_register_desc': 'Cree su cuenta LabProGlobal para gestionar pedidos y solicitar cotizaciones.',
    'auth_email': 'Correo electrónico',
    'auth_password': 'Contraseña',
    'auth_confirm_password': 'Confirmar contraseña',
    'auth_forgot_password': '¿Olvidó su contraseña?',
    'auth_reset_title': 'Restablecer Contraseña',
    'auth_reset_desc': 'Ingrese su correo electrónico y le enviaremos un enlace.',
    'auth_reset_button': 'Enviar enlace',
    'auth_reset_success': 'Correo de restablecimiento enviado',
    'auth_reset_error': 'No se encontró ninguna cuenta con ese correo electrónico',
    'auth_no_account': '¿No tiene cuenta?',
    'auth_have_account': '¿Ya tiene cuenta?',
    'auth_create_account': 'Crear cuenta',
    'auth_login_google': 'Iniciar sesión con Google',
    'auth_or': 'o',
    'auth_min_password': 'Al menos 8 caracteres',
    'auth_invalid_credentials': 'Credenciales inválidas',
    'auth_email_required': 'El correo electrónico es obligatorio',
    'auth_password_required': 'La contraseña es obligatoria',
    'auth_passwords_match': 'Las contraseñas deben coincidir',
    'auth_invalid_email': 'Correo electrónico inválido',
    'auth_login_success': 'Inicio de sesión exitoso',
    'auth_logout_success': 'Sesión cerrada',
    'auth_auth_failed': 'Autenticación fallida',
    'auth_company_optional': 'Empresa (opcional)',
    'auth_create_account_btn': 'Crear Cuenta',
    'auth_create_account_link': 'Crear cuenta',
    'auth_join_desc': 'Únase a miles de laboratorios que confían en LabProGlobal',
    'auth_name': 'Nombre',
    'auth_or_continue': 'o continuar como',
    'auth_sign_in': 'Iniciar Sesión',
    'auth_sign_in_link': 'Iniciar sesión',
    'auth_sign_in_subtitle': 'Inicie sesión para acceder a su cuenta',
    'auth_sign_up': 'Registrarse',
    'auth_signing_in': 'Iniciando sesión...',
    'auth_welcome_back': 'Bienvenido de nuevo',
    'auth_demo_mode': 'Modo Demo',
    'auth_demo_mode_notice': 'Está usando credenciales de demostración',
    'auth_demo_mode_setup': 'Configure DATABASE_URL y NEXTAUTH_SECRET',
    'auth_demo_credentials': 'Credenciales de demostración',
    'auth_demo_email': 'demo@labproglobal.com',
    'auth_demo_password': 'demo123',
    'auth_env_setup_notice': 'Configure las variables de entorno',
    'auth_already_have': 'Ya tiene cuenta',
    'auth_enter_password': 'Ingrese su contraseña',
    'footer_company': 'LabProGlobal',
    'footer_tagline': 'Su socio de confianza en equipos de laboratorio',
    'footer_contact': 'Contacto',
    'footer_newsletter': 'Boletín',
    'footer_newsletter_desc': 'Reciba las últimas novedades y ofertas especiales.',
    'footer_email': 'Su correo electrónico',
    'footer_subscribe': 'Suscribirse',
    'footer_categories': 'Categorías',
    'footer_support': 'Soporte',
    'footer_about': 'Nosotros',
    'footer_help': 'Centro de Ayuda',
    'footer_returns': 'Devoluciones',
    'footer_shipping': 'Envíos',
    'footer_faq': 'Preguntas Frecuentes',
    'footer_contact_us': 'Contáctenos',
    'footer_legal': 'Legal',
    'footer_privacy': 'Política de Privacidad',
    'footer_terms': 'Términos de Servicio',
    'footer_returns_policy': 'Política de Devoluciones',
    'footer_copyright': '© 2024 LabProGlobal. Todos los derechos reservados.',
    'footer_all_rights': 'Todos los derechos reservados',
    'footer_description': 'Su socio de confianza en equipos de laboratorio.',
    'footer_account_col': 'Mi Cuenta',
    'footer_products_col': 'Productos',
    'footer_services_col': 'Servicios',
    'footer_quick_links': 'Enlaces Rápidos',
    'footer_all_products': 'Todos los Productos',
    'footer_sign_in': 'Iniciar Sesión',
    'footer_create_account': 'Crear Cuenta',
    'footer_my_orders': 'Mis Pedidos',
    'footer_my_quotes': 'Mis Cotizaciones',
    'footer_address_book': 'Libro de Direcciones',
    'footer_bulk_orders': 'Pedidos en Volumen',
    'footer_request_quote': 'Solicitar Cotización',
    'footer_technical_support': 'Soporte Técnico',
    'footer_shipping_policy': 'Política de Envíos',
    'footer_returns_refunds': 'Devoluciones y Reembolsos',
    'footer_rights': 'Todos los derechos reservados',
    'terms_title': 'Términos de Servicio',
    'terms_last_updated': 'Última actualización:',
    'terms_section1': '1. Aceptación de los Términos',
    'terms_section2': '2. Servicios y Productos',
    'terms_section3': '3. Cuentas de Usuario',
    'terms_section4': '4. Órdenes y Precios',
    'terms_section5': '5. Envío y Entrega',
    'terms_section6': '6. Devoluciones y Reembolsos',
    'terms_section7': '7. Responsabilidad',
    'terms_section8': '8. Propiedad Intelectual',
    'terms_section9': '9. Ley Aplicable',
    'terms_section10': '10. Contacto',
    'terms_item1': 'Al acceder o utilizar nuestro sitio web, usted acepta estos Términos.',
    'terms_item2': 'Ofrecemos equipos y suministros de laboratorio.',
    'terms_item3': 'Usted es responsable de mantener la confidencialidad de su cuenta.',
    'terms_item4': 'Los precios mostrados están en USD y pueden cambiar sin previo aviso.',
    'terms_item5': 'Los tiempos de envío son estimados.',
    'terms_item6': 'Consulte nuestra Política de Devoluciones.',
    'terms_item7': 'No somos responsables de daños indirectos o consecuentes.',
    'terms_item8': 'Todo el contenido es propiedad de LabProGlobal.',
    'terms_item9': 'Estos términos se rigen por las leyes de Delaware.',
    'terms_item10': 'Contáctenos en legal@labproglobal.com',
    'privacy_title': 'Política de Privacidad',
    'privacy_last_updated': 'Última actualización:',
    'privacy_section1': '1. Información que Recopilamos',
    'privacy_section2': '2. Cómo Utilizamos su Información',
    'privacy_section3': '3. Compartir Información',
    'privacy_section4': '4. Seguridad de Datos',
    'privacy_section5': '5. Cookies',
    'privacy_section6': '6. Sus Derechos',
    'privacy_section7': '7. Contacto',
    'privacy_item1a': 'Información de contacto (nombre, correo electrónico, teléfono, empresa)',
    'privacy_item1b': 'Direcciones de envío y facturación',
    'privacy_item1c': 'Historial de pedidos y detalles de transacciones',
    'privacy_item1d': 'Solicitudes de cotización e historial de comunicaciones',
    'privacy_item1e': 'Datos de uso y análisis',
    'privacy_item1f': 'Mejorar nuestro sitio web y servicios',
    'privacy_item2a': 'No vendemos su información personal.',
    'privacy_item2b': 'Implementamos medidas de seguridad estándar de la industria.',
    'privacy_item2c': 'Utilizamos cookies para mantener su carrito y recordar sus preferencias.',
    'privacy_item3': 'Tiene derecho a acceder, corregir y eliminar sus datos.',
    'privacy_item4': 'Para consultas de privacidad, contacte a privacy@labproglobal.com',
    'privacy_item5': 'Todos los datos se almacenan de forma segura en servidores cifrados.',
    'privacy_item6': 'Puede solicitar la eliminación de su cuenta y datos en cualquier momento.',
    'privacy_item7': 'Cumplimos con las leyes de protección de datos aplicables.',
    'returns_title': 'Devoluciones y Reembolsos',
    'returns_subtitle': 'Queremos que esté completamente satisfecho con su compra.',
    'returns_30day': 'Devoluciones de 30 días',
    'returns_30day_desc': 'Los artículos estándar pueden devolverse dentro de los 30 días.',
    'returns_easy': 'Proceso Fácil',
    'returns_easy_desc': 'Solicite una devolución a través de su cuenta',
    'returns_full': 'Reembolso Completo',
    'returns_full_desc': 'Reembolso procesado en 5-7 días hábiles',
    'returns_policy': 'Política de Devoluciones',
    'returns_policy_standard': 'Productos Estándar: Reembolso completo en 30 días.',
    'returns_policy_special': 'Pedidos Especiales: No pueden devolverse a menos que estén defectuosos.',
    'returns_policy_defective': 'Productos Defectuosos: Reemplazo o reembolso gratuito.',
    'returns_policy_shipping': 'Envío de Devolución: El cliente es responsable.',
    'returns_how': 'Cómo Devolver un Artículo',
    'returns_step1': 'Inicie sesión y vaya a Historial de Pedidos',
    'returns_step2': 'Seleccione el pedido y el artículo a devolver',
    'returns_step3': 'Elija un motivo y envíe su solicitud',
    'returns_step4': 'Recibirá una autorización y etiqueta de envío',
    'returns_step5': 'Empaque el artículo y envíelo de vuelta',
    'returns_step6': 'Recibirá su reembolso una vez procesado',
    'returns_contact': 'Contactar Departamento de Devoluciones',
    'returns_need_help': '¿Necesita ayuda con una devolución?',
    'products_page_title': 'Todos los Productos',
    'products_results_count': '{count} productos encontrados',
    'products_showing_range': 'Mostrando {from}–{to} de {total}',
    'products_no_results': 'No se encontraron productos',
    'products_prev': 'Anterior',
    'products_next': 'Siguiente',
    'products_add_to_cart': 'Añadir al Carrito',
    'products_brand': 'Marca',
    'products_in_stock': 'En Stock',
    'products_out_of_stock': 'Agotado',
    'products_on_order': 'Sobre Pedido',
    'products_lead_time': 'Tiempo de entrega',
    'products_sku': 'SKU',
    'products_related': 'Productos Relacionados',
    'products_request_quote': 'Solicitar Cotización',
    'products_specifications': 'Especificaciones',
    'products_title': 'Productos',
    'products_view_all': 'Ver Todos',
    'products_sort_featured': 'Destacados',
    'products_sort_newest': 'Más Nuevos',
    'products_sort_price_asc': 'Precio: Menor a Mayor',
    'products_sort_price_desc': 'Precio: Mayor a Menor',
    'product_sku_label': 'SKU',
    'product_key_specs': 'Especificaciones Clave',
    'product_full_specs': 'Especificaciones Completas',
    'product_expert_support': 'Soporte Experto',
    'product_fast_shipping': 'Envío Rápido',
    'product_secure_payment': 'Pago Seguro',
    'product_returns': '30 Días de Devolución',
    'product_home': 'Inicio',
    'product_products': 'Productos',
    'product_related': 'Productos Relacionados',
    'home_hero_title': 'Equipos de Laboratorio de Alta Calidad',
    'home_hero_subtitle': 'Encuentre todo lo que necesita para su laboratorio.',
    'home_hero_button': 'Explorar Productos',
    'home_hero_quote': 'Solicitar Cotización',
    'home_featured': 'Productos Destacados',
    'home_categories': 'Categorías Populares',
    'home_why': 'Por Qué Elegirnos',
    'home_quality': 'Calidad Garantizada',
    'home_quality_desc': 'Todos los productos cumplen con estándares internacionales.',
    'home_pricing': 'Precios Competitivos',
    'home_pricing_desc': 'Precios transparentes sin tarifas ocultas.',
    'home_shipping': 'Envío Rápido',
    'home_shipping_desc': 'Envío rápido y seguro con seguimiento en tiempo real.',
    'home_support': 'Soporte Experto',
    'home_support_desc': 'Nuestro equipo de expertos está disponible para ayudarle.',
    'home_view_all': 'Ver Todos',
    'home_view_product': 'Ver Producto',
    'home_add_to_cart': 'Añadir al Carrito',
    'home_get_quote': 'Obtener Cotización',
    'home_learn_more': 'Más Información',
    'home_featured_title': 'Productos Destacados',
    'home_featured_desc': 'Explore nuestra selección de equipos de laboratorio.',
    'home_featured_subtitle': 'Los mejores productos elegidos para usted',
    'home_categories_title': 'Categorías Populares',
    'home_categories_desc': 'Encuentre exactamente lo que necesita.',
    'home_about_title': 'Sobre Nosotros',
    'home_about_p1': 'LabProGlobal es un proveedor líder de equipos de laboratorio.',
    'home_about_p2': 'Con años de experiencia, nos especializamos en instrumentos de precisión.',
    'home_about_p3': 'Nuestra misión es apoyar los avances científicos.',
    'home_about_btn': 'Más Información',
    'home_trust': 'Construyendo Confianza',
    'home_trust_p1': 'Miles de laboratorios en todo el mundo confían en LabProGlobal.',
    'home_trust_p2': 'Nos comprometemos a la calidad y la satisfacción del cliente.',
    'home_trust_p3': 'Nuestro equipo dedicado está aquí para ayudarle.',
    'home_newsletter_title': 'Boletín',
    'home_newsletter_desc': 'Reciba las últimas novedades y ofertas especiales.',
    'home_newsletter_placeholder': 'Su correo electrónico',
    'home_newsletter_button': 'Suscribirse',
    'home_newsletter_success': '¡Gracias por suscribirse!',
    'home_cta_title': '¿Necesita una Cotización Personalizada?',
    'home_cta_subtitle': 'Contáctenos hoy y le responderemos en 24 horas',
    'home_cta_button': 'Solicitar Cotización',
    'home_trust_quality': 'Calidad',
    'home_trust_quality_desc': 'Productos de alta calidad garantizada',
    'home_trust_pricing': 'Precios',
    'home_trust_pricing_desc': 'Precios competitivos y transparentes',
    'home_trust_shipping': 'Envío',
    'home_trust_shipping_desc': 'Envío rápido y seguro',
    'home_trust_support': 'Soporte',
    'home_trust_support_desc': 'Asistencia experta 24/7',
    'about_title': 'Sobre Nosotros',
    'about_hero_title': 'Sobre Nosotros',
    'about_hero_subtitle': 'Conozca más sobre LabProGlobal y nuestra misión.',
    'about_mission_title': 'Nuestra Misión',
    'about_mission_p1': 'En LabProGlobal, nos dedicamos a potenciar los laboratorios.',
    'about_mission_p2': 'Nuestra misión es acelerar el descubrimiento científico.',
    'about_vision_title': 'Nuestra Visión',
    'about_vision_p1': 'Nuestra visión es ser el socio más confiable para equipos de laboratorio.',
    'about_vision_p2': 'Buscamos expandir continuamente nuestras ofertas de productos.',
    'about_values_title': 'Nuestros Valores',
    'about_quality': 'Calidad',
    'about_quality_desc': 'Solo los productos que cumplen nuestros estándares de calidad.',
    'about_innovation': 'Innovación',
    'about_innovation_desc': 'Buscamos continuamente productos nuevos y mejorados.',
    'about_integrity': 'Integridad',
    'about_integrity_desc': 'Precios honestos y prácticas comerciales éticas.',
    'about_customers': 'Clientes Primero',
    'about_customers_desc': 'Su éxito es nuestra prioridad.',
    'about_team_title': 'Nuestro Equipo',
    'about_team_p1': 'Nuestro equipo reúne experiencia en equipos de laboratorio.',
    'about_team_p2': 'Nos apasiona la ciencia y ayudar a nuestros clientes.',
    'about_contact_title': 'Contáctenos',
    'about_contact_p1': '¿Tiene preguntas? Nuestro equipo está aquí para ayudar.',
    'about_contact_p2': 'Contáctenos a través de nuestro formulario o FAQ.',
    'search_title': 'Buscar',
    'search_results_for': 'Resultados de búsqueda para',
    'search_results_count': '{count} resultados',
    'search_no_results': 'No se encontraron resultados',
    'search_browse_all': 'Ver todos los productos',
    'search_placeholder_hint': 'Escriba para buscar...',
    'categories_title': 'Categorías',
    'categories_subtitle': 'Explore por categoría',
    'categories_all_label': 'Todos los productos',
    'categories_browse_all': 'Ver Todos',
    'categories_subcategories': 'Subcategorías',
    'categories_no_products': 'No se encontraron productos en esta categoría',
    'categories_prev': 'Anterior',
    'categories_next': 'Siguiente',
    'categories_products_count': '{count} productos',
    'categories_page_of': 'Página {current} de {total}',
    'categories_sort_bar': 'Ordenar por',
    'categories_other': 'Otros',
    'categories_view_all': 'Ver Todos',
    'brands_title': 'Marcas',
    'brands_subtitle': 'Explore por marca',
    'brands_products': '{count} productos',
    'brands_no_products': 'No hay productos de esta marca',
    'brands_no_brands': 'No se encontraron marcas',
    'brands_browse_all': 'Ver Todas las Marcas',
    'brands_count': '{count} marcas',
    'shipping_title': 'Política de Envíos',
    'shipping_subtitle': 'Información sobre nuestras opciones y políticas de envío',
    'shipping_options': 'Opciones de Envío',
    'shipping_processing': 'Procesamiento',
    'shipping_delivery_col': 'Entrega',
    'shipping_carriers': 'Transportistas',
    'shipping_carriers_desc': 'Usamos transportistas confiables como UPS, FedEx y DHL',
    'shipping_countries': 'Países',
    'shipping_countries_desc': 'Enviamos a más de 100 países',
    'shipping_tracking': 'Seguimiento',
    'shipping_tracking_desc': 'Reciba actualizaciones de seguimiento en tiempo real',
    'shipping_free_title': 'Envío Gratuito',
    'shipping_free_text': 'Disponible en pedidos que cumplan los requisitos',
    'shipping_quote': 'Cotización de Envío',
    'shipping_quote_text': 'Solicite una cotización de envío para pedidos grandes',
    'shipping_special': 'Pedidos Especiales',
    'shipping_instock': 'En stock',
    'shipping_notes_col': 'Notas',
    'shipping_carrier_col': 'Transportista',
    'support_title': 'Soporte',
    'support_subtitle': '¿Cómo podemos ayudarle?',
    'support_contact_title': 'Contáctenos',
    'support_email': 'Correo electrónico',
    'support_email_label': 'Dirección de correo electrónico',
    'support_email_desc': 'Responderemos en 24 horas',
    'support_phone': 'Teléfono',
    'support_phone_desc': 'Lun-Vie 9am-6pm EST',
    'support_livechat': 'Chat en Vivo',
    'support_livechat_desc': 'Hable con un agente ahora',
    'support_faq': 'Preguntas Frecuentes',
    'support_faq1_q': '¿Cómo realizo un pedido?',
    'support_faq1_a': 'Puede realizar un pedido directamente a través de nuestro sitio web.',
    'support_faq2_q': '¿Cuáles son sus opciones de envío?',
    'support_faq2_a': 'Ofrecemos envío estándar, urgente y expreso a través de UPS, FedEx y DHL.',
    'support_faq3_q': '¿Cuál es su política de devoluciones?',
    'support_faq3_a': 'Los artículos estándar pueden devolverse dentro de los 30 días.',
    'support_faq4_q': '¿Cómo solicito una cotización?',
    'support_faq4_a': 'Haga clic en "Solicitar Cotización" en cualquier página de producto.',
    'support_faq5_q': '¿Ofrecen descuentos por volumen?',
    'support_faq5_a': 'Sí, contáctenos para obtener precios especiales en pedidos grandes.',
    'support_name_label': 'Nombre',
    'support_subject_label': 'Asunto',
    'support_message_label': 'Mensaje',
    'support_send_btn': 'Enviar Mensaje',
    'support_sent_title': 'Mensaje Enviado',
    'support_sent_desc': 'Gracias por contactarnos. Le responderemos en 24 horas.',
    'error_title': 'Error',
    'error_generic': 'Ha ocurrido un error. Por favor, inténtelo de nuevo.',
    'error_404_title': 'Página No Encontrada',
    'error_404_desc': 'Lo sentimos, la página que está buscando no existe o ha sido movida.',
    'error_404_button': 'Volver al Inicio',
    'error_back_home': 'Volver al Inicio',
    'aria_language_options': 'Opciones de idioma',
    'aria_close_menu': 'Cerrar menú',
    'aria_open_menu': 'Abrir menú',
    'aria_remove_item': 'Eliminar artículo',
    'aria_increase_quantity': 'Aumentar cantidad',
    'aria_decrease_quantity': 'Disminuir cantidad',
    'aria_select_language': 'Seleccionar idioma',
    'placeholder_name_example': 'John Smith',
    'placeholder_company_example': 'Su Empresa S.A.',
    'placeholder_email_example': 'su@correo.com',
    'placeholder_phone_example': '+1 (555) 000-0000',
    'placeholder_notes_example': 'Añada notas adicionales aquí...',
    'placeholder_search_example': 'Buscar productos...',
    'cat_Flow_Control': 'Control de Flujo',
    'cat_Environmental': 'Ambiental',
    'cat_General': 'General',
    'cat_Industrial_Measurement': 'Medición Industrial',
    'cat_Laboratory_Equipment': 'Equipos de Laboratorio',
    'cat_Pumps_Valves': 'Bombas y Válvulas',
    'filter_availability': 'Disponibilidad',
    'filter_brand': 'Marca',
    'filter_in_stock_only': 'Solo en Stock',
    'filter_min': 'Mín',
    'filter_max': 'Máx',
    'filter_price_range': 'Rango de Precio',
    'hero_title': 'Equipos de Laboratorio de Alta Calidad',
    'hero_subtitle': 'Encuentre todo lo que necesita para su laboratorio',
    'hero_cta_shop': 'Ver Productos',
    'hero_cta_quote': 'Solicitar Cotización',
    'quote_title': 'Solicitar Cotización',
    'quote_subtitle': 'Complete el formulario y nos pondremos en contacto con usted en 24 horas',
    'quote_sidebar_title': 'Productos Seleccionados',
    'quote_items_selected': '{count} productos seleccionados',
    'quote_select_product': 'Seleccionar producto',
    'quote_review_msg': 'Revise su solicitud antes de enviar',
    'quote_submit': 'Enviar Solicitud',
    'quote_submitting': 'Enviando...',
    'quote_success': '¡Solicitud enviada con éxito!',
    'quote_submitted_title': 'Solicitud Enviada',
    'quote_response_time': 'Tiempo de respuesta',
    'quote_response_value': 'En 24 horas',
    'quote_within_24h': 'Nos pondremos en contacto con usted en 24 horas',
    'quote_name': 'Nombre completo',
    'quote_email': 'Correo electrónico',
    'quote_phone': 'Teléfono',
    'quote_company': 'Empresa',
    'quote_company_optional': 'Empresa (opcional)',
    'quote_message': 'Mensaje',
    'quote_notes': 'Notas adicionales',
    'quote_items_label': 'Productos',
    'quote_items_for': '{count} productos',
    'quote_items_selected_label': 'artículos seleccionados',
    'quote_number_label': '#',
    'quote_no_items': 'No hay productos seleccionados',
    'quote_empty': 'Su lista de cotización está vacía',
    'quote_browse_products': 'Explorar Productos',
    'quote_add_all': 'Añadir todos al formulario',
    'quote_cart_items': 'artículos del carrito',
    'quote_contact_info': 'Información de contacto',
    'quote_fill_required': 'Por favor complete todos los campos obligatorios',
    'quote_email_required': 'Correo electrónico obligatorio',
    'quote_full_name_required': 'Nombre completo obligatorio',
    'quote_phone_optional': 'Teléfono (opcional)',
}

print(f"ES has {len(ES)} keys")

# JA translations
JA = {
    'nav_search_placeholder': '製品名、SKU、またはブランドで検索...',
    'nav_get_quote': '見積もり依頼',
    'nav_sign_in': 'ログイン',
    'nav_my_account': 'マイアカウント',
    'nav_orders': '注文履歴',
    'nav_sign_out': 'ログアウト',
    'nav_all_products': '全製品',
    'nav_all_categories': '全カテゴリー',
    'nav_cart': 'カート',
    'nav_view_all': 'すべて表示',
    'nav_free_shipping': '送料無料（$500以上）',
    'cart_title': 'カート',
    'cart_empty': 'カートは空です',
    'cart_empty_desc': '製品をカートに追加してください',
    'cart_continue': '買い物を続ける',
    'cart_checkout': 'チェックアウト',
    'cart_subtotal': '小計',
    'cart_quantity': '数量',
    'cart_remove': '削除',
    'cart_item_added': '製品をカートに追加しました',
    'cart_total': '合計',
    'cart_request_quote': '見積を依頼',
    'cart_estimated_shipping': '配送料見込',
    'cart_free_shipping': '無料',
    'cart_final_total': '合計金額',
    'cart_browse_products': '製品を探す',
    'cart_clear': 'カートを空にする',
    'cart_continue_shopping': '買い物を続ける',
    'cart_free_shipping_hint': 'あと{amount}で送料無料',
    'cart_items_count': '{count}点',
    'cart_order_summary': '注文概要',
    'cart_shipping': '配送料',
    'cart_shipping_free': '無料',
    'cart_sku_label': 'SKU',
    'cart_tax': '税金',
    'cart_tax_at_checkout': 'チェックアウト時に計算',
    'account_title': 'マイアカウント',
    'account_welcome': 'おかえりなさい',
    'account_sign_in': 'ログイン',
    'account_register': 'アカウント作成',
    'account_email': 'メールアドレス',
    'account_password': 'パスワード',
    'account_remember_me': 'ログイン状態を保存',
    'account_forgot_password': 'パスワードをお忘れですか？',
    'account_no_account': 'アカウントをお持ちでない方',
    'account_have_account': 'すでにアカウントをお持ちの方',
    'account_sign_in_title': 'ログイン',
    'account_register_title': 'アカウント作成',
    'account_orders': '注文履歴',
    'account_quotes': '見積履歴',
    'account_addresses': '住所',
    'account_settings': '設定',
    'account_logout': 'ログアウト',
    'account_first_name': '名',
    'account_last_name': '姓',
    'account_company': '会社名',
    'account_phone': '電話番号',
    'account_addresses_desc': '住所を管理',
    'account_browse_products': '製品を探す',
    'account_no_orders': '注文履歴なし',
    'account_order_date': '注文日',
    'account_order_status': '注文状況',
    'account_order_total': '注文合計',
    'account_order_view': '詳細を見る',
    'account_order_items': '注文商品',
    'account_orders_appear_here': '注文を行うとここに表示されます',
    'account_orders_desc': '注文履歴と状況を確認',
    'account_quotes_desc': '見積依頼履歴を確認',
    'checkout_title': 'チェックアウト',
    'checkout_steps_title': 'チェックアウト手順',
    'checkout_step1': 'カート',
    'checkout_step2': '配送',
    'checkout_step3': '確認',
    'checkout_back_cart': 'カートに戻る',
    'checkout_not_configured': 'チェックアウトはまだ設定されていません。見積を依頼してください。',
    'checkout_request_quote': '見積を依頼',
    'addr_title': '住所簿',
    'addr_subtitle': '配送先と請求先住所の管理',
    'addr_add_address': '住所を追加',
    'addr_new_address': '新しい住所',
    'addr_label': '住所ラベル',
    'addr_first_name': '名',
    'addr_last_name': '姓',
    'addr_address1': '住所1',
    'addr_address2': '住所2',
    'addr_city': '市区町村',
    'addr_state': '都道府県',
    'addr_zip': '郵便番号',
    'addr_country': '国',
    'addr_phone_optional': '電話番号（任意）',
    'addr_save': '住所を保存',
    'addr_cancel': 'キャンセル',
    'addr_no_addresses': '保存された住所はありません',
    'addr_add_first': '最初の住所を追加',
    'addr_add_first_desc': '配送先または請求先住所を追加して、より迅速にチェックアウトしましょう。',
    'addr_add_first_btn': '住所を追加',
    'addr_default': 'デフォルト',
    'addr_edit': '編集',
    'addr_delete': '削除',
    'addr_loading': '住所を読み込み中...',
    'quotes_title': 'マイ見積',
    'quotes_subtitle': '見積依頼履歴を確認',
    'quotes_loading': '見積を読み込み中...',
    'quotes_no_quotes': '見積依頼履歴なし',
    'quotes_no_quotes_desc': '見積を依頼すると、ここに表示されます',
    'quotes_request_new': '見積を依頼',
    'quotes_request_quote': '見積を依頼',
    'quotes_quote_number': '見積番号',
    'quotes_date': '日付',
    'quotes_items': '商品数',
    'quotes_est_total': '見積合計',
    'quotes_status': 'ステータス',
    'quotes_status_pending': '保留中',
    'quotes_status_approved': '承認済み',
    'quotes_status_rejected': '却下',
    'contact_title': 'お問い合わせ',
    'contact_desc': 'ご質問がありますか？お手伝いします。',
    'contact_form_title': 'メッセージを送る',
    'contact_name': 'お名前',
    'contact_email': 'メールアドレス',
    'contact_phone': '電話番号',
    'contact_company': '会社名',
    'contact_subject': '件名',
    'contact_message': 'メッセージ',
    'contact_send': '送信',
    'contact_office_hours': '営業時間',
    'contact_response_time': '24時間以内にご返信いたします',
    'contact_address': '住所',
    'contact_phone_label': '電話番号',
    'contact_email_label': 'メールアドレス',
    'auth_login_title': 'ログイン',
    'auth_login_desc': '注文管理と見積依頼にログインしてください',
    'auth_login_button': 'ログイン',
    'auth_register_title': 'アカウント作成',
    'auth_register_desc': 'LabProGlobalアカウントを作成して注文管理和見積依頼',
    'auth_email': 'メールアドレス',
    'auth_password': 'パスワード',
    'auth_confirm_password': 'パスワード確認',
    'auth_forgot_password': 'パスワードをお忘れですか？',
    'auth_reset_title': 'パスワードリセット',
    'auth_reset_desc': 'メールアドレスを入力してください',
    'auth_reset_button': 'リンクを送信',
    'auth_reset_success': 'リセットメールを送信しました',
    'auth_reset_error': 'このメールアドレスのアカウントが見つかりません',
    'auth_no_account': 'アカウントをお持ちでない方',
    'auth_have_account': 'すでにアカウントをお持ちの方',
    'auth_create_account': 'アカウント作成',
    'auth_login_google': 'Googleでログイン',
    'auth_or': 'または',
    'auth_min_password': '8文字以上',
    'auth_invalid_credentials': '認証情報が無効です',
    'auth_email_required': 'メールアドレスは必須',
    'auth_password_required': 'パスワードは必須',
    'auth_passwords_match': 'パスワードが一致しません',
    'auth_invalid_email': '無効なメールアドレス',
    'auth_login_success': 'ログインしました',
    'auth_logout_success': 'ログアウトしました',
    'auth_auth_failed': '認証に失敗しました',
    'auth_company_optional': '会社名（任意）',
    'auth_create_account_btn': 'アカウント作成',
    'auth_create_account_link': 'アカウント作成',
    'auth_join_desc': 'LabProGlobalを信頼する何千ものラボに参加しましょう',
    'auth_name': 'お名前',
    'auth_or_continue': 'または次で続行',
    'auth_sign_in': 'ログイン',
    'auth_sign_in_link': 'ログイン',
    'auth_sign_in_subtitle': 'アカウントにログイン',
    'auth_sign_up': '新規登録',
    'auth_signing_in': 'ログイン中...',
    'auth_welcome_back': 'おかえりなさい',
    'auth_enter_password': 'パスワードを入力',
    'auth_demo_mode': 'デモモード',
    'auth_demo_mode_notice': 'デモ資格情報を使用しています',
    'auth_demo_mode_setup': 'DATABASE_URL と NEXTAUTH_SECRET を設定してください',
    'auth_demo_credentials': 'デモ資格情報',
    'auth_demo_email': 'demo@labproglobal.com',
    'auth_demo_password': 'demo123',
    'auth_env_setup_notice': '環境変数を設定してください',
    'auth_already_have': 'アカウントをお持ちの方',
    'footer_company': 'LabProGlobal',
    'footer_tagline': '高品質な実験機器をお届けする信頼できるパートナー',
    'footer_contact': 'お問い合わせ',
    'footer_newsletter': 'ニュースレター',
    'footer_newsletter_desc': '最新ニュースと特別オファーをお届けします',
    'footer_email': 'メールアドレス',
    'footer_subscribe': '購読する',
    'footer_categories': 'カテゴリー',
    'footer_support': 'サポート',
    'footer_about': '会社概要',
    'footer_help': 'ヘルプセンター',
    'footer_returns': '返品',
    'footer_shipping': '配送',
    'footer_faq': 'よくある質問',
    'footer_contact_us': 'お問い合わせ',
    'footer_legal': '法的情報',
    'footer_privacy': 'プライバシーポリシー',
    'footer_terms': '利用規約',
    'footer_returns_policy': '返品ポリシー',
    'footer_copyright': '© 2024 LabProGlobal. All rights reserved.',
    'footer_all_rights': '全著作権所有',
    'footer_description': '高品質な実験機器をお届けする信頼できるパートナー',
    'footer_account_col': 'マイアカウント',
    'footer_products_col': '製品',
    'footer_services_col': 'サービス',
    'footer_quick_links': 'クイックリンク',
    'footer_all_products': 'すべての製品',
    'footer_sign_in': 'ログイン',
    'footer_create_account': 'アカウント作成',
    'footer_my_orders': '注文履歴',
    'footer_my_quotes': '見積履歴',
    'footer_address_book': '住所簿',
    'footer_bulk_orders': '大口注文',
    'footer_request_quote': '見積を依頼',
    'footer_technical_support': '技術サポート',
    'footer_shipping_policy': '配送ポリシー',
    'footer_returns_refunds': '返品・返金',
    'footer_rights': '全著作権所有',
    'terms_title': '利用規約',
    'terms_last_updated': '最終更新日:',
    'terms_section1': '1. 利用規約の受け入れ',
    'terms_section2': '2. サービスと製品',
    'terms_section3': '3. ユーザーアカウント',
    'terms_section4': '4. 注文と価格',
    'terms_section5': '5. 配送と配達',
    'terms_section6': '6. 返品と返金',
    'terms_section7': '7. 責任',
    'terms_section8': '8. 知的所有権',
    'terms_section9': '9. 適用法',
    'terms_section10': '10. お問い合わせ',
    'terms_item1': '本网站にアクセスまたはブログに表示することで、本利用規約に同意したものとみなされます。',
    'terms_item2': ' различные научные и промышленныеアプリケーション向けのラボ機器・试剂を提供ています。',
    'terms_item3': 'アカウントとパスワードの機密性を維持する責任は您您にあります。',
    'terms_item4': '表示価格は米ドルで、予告なく変更される場合があります。',
    'terms_item5': '配送日時はあくまで目安です。',
    'terms_item6': '返品ポリシーについては、詳細をご覧ください。',
    'terms_item7': '法律により認められる最大限において、間接的または結果的損害について責任を負いません。',
    'terms_item8': '本网站のすべての内容はLabProGlobalの財産です。',
    'terms_item9': '本利用規約は、米国デラウェア州の法律に準拠します。',
    'terms_item10': 'ご質問はlegal@labproglobal.comまでご連絡ください。',
    'privacy_title': 'プライバシーポリシー',
    'privacy_last_updated': '最終更新日:',
    'privacy_section1': '1. 当社が収集する情報',
    'privacy_section2': '2. 当社が情報を使用する目的',
    'privacy_section3': '3. 情報の共有',
    'privacy_section4': '4. データセキュリティ',
    'privacy_section5': '5. Cookie',
    'privacy_section6': '6. お客様の権利',
    'privacy_section7': '7. お問い合わせ',
    'privacy_item1a': '連絡先情報（名前、メール、電話、公司）',
    'privacy_item1b': '配送先と請求先の住所',
    'privacy_item1c': '注文履歴と取引詳細',
    'privacy_item1d': '見積依頼とご連絡履歴',
    'privacy_item1e': '使用データと分析',
    'privacy_item1f': ' 당사 网站 및 서비스 개선',
    'privacy_item2a': ' 당사는 개인 정보를 판매하지 않습니다.',
    'privacy_item2b': ' 당사는 업계 표준 보안 Measures를実装しています。',
    'privacy_item2c': ' 쿠키를 사용하여 장바구니를 유지하고',
    'privacy_item3': '개인 데이터 접근, 수정, 삭제 권리가 있습니다.',
    'privacy_item4': '개인정보 관련 문의는 privacy@labproglobal.com으로 연락주세요.',
    'privacy_item5': '모든 데이터는 암호화된 서버에 안전하게 저장됩니다.',
    'privacy_item6': '계정 및 데이터 삭제를 요청할 수 있습니다.',
    'privacy_item7': '관련 데이터 보호 법률을 준수합니다.',
    'returns_title': '返品・返金',
    'returns_subtitle': 'ご購入にご満足いただけることをお約束します。',
    'returns_30day': '30日間返品可',
    'returns_30day_desc': '標準品は無毃・未使用の場合、受領後30日以内に返品可能',
    'returns_easy': '簡単なプロセス',
    'returns_easy_desc': 'アカウントから返品をリクエスト',
    'returns_full': '全額返金',
    'returns_full_desc': '5〜7営業日以内に返金処理',
    'returns_policy': '返品ポリシー',
    'returns_policy_standard': '標準製品：無毃・未使用状態であれば30日以内に全額返金。',
    'returns_policy_special': '特別注文：欠陥がある場合のみ返品可。',
    'returns_policy_defective': '欠陥製品：直ちにでください。無料交換または返金。',
    'returns_policy_shipping': '返品送料：客户負担。',
    'returns_how': 'アイテムを返品する方法',
    'returns_step1': 'アカウントにログインし注文履歴へ',
    'returns_step2': '返品したい注文と商品を選択',
    'returns_step3': '理由を選択し、リクエストを送信',
    'returns_step4': '返品許可と shipping ラベルを受け取る',
    'returns_step5': '商品を安全に梱包し返送',
    'returns_step6': '返品処理完了後、返金を受け取る',
    'returns_contact': '返品部門に문의',
    'returns_need_help': '返品についてのお問い合わせ',
    'products_page_title': 'すべての製品',
    'products_results_count': '{count}件の製品が見つかりました',
    'products_showing_range': '{total}件中{from}〜{to}件を表示',
    'products_no_results': '製品が見つかりません',
    'products_prev': '前へ',
    'products_next': '次へ',
    'products_add_to_cart': 'カートに追加',
    'products_brand': 'ブランド',
    'products_in_stock': '在庫あり',
    'products_out_of_stock': '在庫切れ',
    'products_on_order': '受注生産',
    'products_lead_time': 'リードタイム',
    'products_sku': 'SKU',
    'products_related': '関連製品',
    'products_request_quote': '見積を依頼',
    'products_specifications': '仕様',
    'products_title': '製品',
    'products_view_all': 'すべて見る',
    'products_sort_featured': 'おすすめ',
    'products_sort_newest': '新着順',
    'products_sort_price_asc': '価格：安い順',
    'products_sort_price_desc': '価格：高い順',
    'product_sku_label': 'SKU',
    'product_key_specs': '主要仕様',
    'product_full_specs': '完全な仕様',
    'product_expert_support': '専門サポート',
    'product_fast_shipping': '迅速配送',
    'product_secure_payment': '安全な決済',
    'product_returns': '30日間返品可',
    'product_home': 'ホーム',
    'product_products': '製品',
    'product_related': '関連製品',
    'home_hero_title': '高品質実験機器',
    'home_hero_subtitle': 'ラボに必要なすべてが見つかる',
    'home_hero_button': '製品を見る',
    'home_hero_quote': '見積を依頼',
    'home_featured': '注目の製品',
    'home_categories': '人気のカテゴリー',
    'home_why': '選ばれる理由',
    'home_quality': '品質保証',
    'home_quality_desc': 'すべての製品は国際品質基準を満たしています',
    'home_pricing': '競争力のある価格',
    'home_pricing_desc': '透明な価格で追加料金なし',
    'home_shipping': '迅速配送',
    'home_shipping_desc': 'リアルタイム追跡で安全・迅速な配送',
    'home_support': '専門サポート',
    'home_support_desc': '専門家チームがご質問にお答えします',
    'home_view_all': 'すべて見る',
    'home_view_product': '詳細を見る',
    'home_add_to_cart': 'カートに追加',
    'home_get_quote': '見積を依頼',
    'home_learn_more': '詳細を見る',
    'home_featured_title': '注目の製品',
    'home_featured_desc': '高品質実験機器のセレクション',
    'home_featured_subtitle': 'お客様のために選んだ最高の製品',
    'home_categories_title': '人気のカテゴリー',
    'home_categories_desc': '必要なものを 정확に見つける',
    'home_about_title': '会社概要',
    'home_about_p1': 'LabProGlobalは高品質な実験機器・試薬の大手提供商です。',
    'home_about_p2': '長年の経験を持ち、精密機器、流量ソリューション、分析機器を提供',
    'home_about_p3': '私たちの使命は、的科学の発展を支援することです。',
    'home_about_btn': '詳細を見る',
    'home_trust': '信頼の構築',
    'home_trust_p1': '世界中の何千ものラボがLabProGlobalを信頼',
    'home_trust_p2': '品質、透明性、顧客満足を追求',
    'home_trust_p3': '専任のチームがお客様のサポートに',
    'home_newsletter_title': 'ニュースレター',
    'home_newsletter_desc': '最新ニュース、特别オファー、ラボのヒントをお届け',
    'home_newsletter_placeholder': 'メールアドレス',
    'home_newsletter_button': '購読する',
    'home_newsletter_success': '購読ありがとうございます！',
    'home_cta_title': 'カスタム見積が必要ですか？',
    'home_cta_subtitle': '今日联系我们、24時間以内にご返信',
    'home_cta_button': '見積を依頼',
    'home_trust_quality': '品質',
    'home_trust_quality_desc': '高品質保証の製品',
    'home_trust_pricing': '価格',
    'home_trust_pricing_desc': '競争力のある透明な価格',
    'home_trust_shipping': '配送',
    'home_trust_shipping_desc': '迅速で安全な配送',
    'home_trust_support': 'サポート',
    'home_trust_support_desc': '24時間365日の専門サポート',
    'about_title': '会社概要',
    'about_hero_title': '会社概要',
    'about_hero_subtitle': 'LabProGlobalと私たちの使命について',
    'about_mission_title': '私たちの使命',
    'about_mission_p1': 'LabProGlobalでは、高品質で信頼できる実験機器でラボを支援しています',
    'about_mission_p2': '科学発見を加速するために、研究者と専門家に必要なツールを提供',
    'about_vision_title': '私たちのビジョン',
    'about_vision_p1': '実験機器・試薬の信頼できるパートナーとなること',
    'about_vision_p2': '科学コミュニティの的需求に進化し続ける',
    'about_values_title': '私たちの価値観',
    'about_quality': '品質',
    'about_quality_desc': '厳しい品質基準を満たす製品のみを品揃え',
    'about_innovation': 'イノベーション',
    'about_innovation_desc': 'お客様により良いサービスを提供するため、 지속적으로新製品を模索',
    'about_integrity': '誠実さ',
    'about_integrity_desc': '正直な価格、透明なポリシー、倫理的なビジネス慣行',
    'about_customers': 'お客様第一',
    'about_customers_desc': 'お客様の成功が私たちの最優先事項',
    'about_team_title': '私たちのチーム',
    'about_team_p1': '実験機器、サプライチェーン管理、カスタマーサービスの専門知識を集結',
    'about_team_p2': '科学に情熱を持ち、お客様の研究・業務目標達成を支援',
    'about_contact_title': 'お問い合わせ',
    'about_contact_p1': 'ご質問やお問い合わせは我们的チームが喜んでお手伝いします',
    'about_contact_p2': 'お問い合わせフォームまたはFAQをご覧ください',
    'search_title': '検索',
    'search_results_for': '検索結果',
    'search_results_count': '{count}件の結果',
    'search_no_results': '検索結果が見つかりません',
    'search_browse_all': 'すべての製品を見る',
    'search_placeholder_hint': '検索語句を入力...',
    'categories_title': 'カテゴリー',
    'categories_subtitle': 'カテゴリーで絞り込む',
    'categories_all_label': 'すべての製品',
    'categories_browse_all': 'すべて見る',
    'categories_subcategories': 'サブカテゴリー',
    'categories_no_products': 'このカテゴリーに製品がありません',
    'categories_prev': '前へ',
    'categories_next': '次へ',
    'categories_products_count': '{count}件の製品',
    'categories_page_of': '{total}ページ中{current}ページ',
    'categories_sort_bar': '並び替え',
    'categories_other': 'その他',
    'categories_view_all': 'すべて見る',
    'brands_title': 'ブランド',
    'brands_subtitle': 'ブランドで絞り込む',
    'brands_products': '{count}件の製品',
    'brands_no_products': 'このブランドの製品がありません',
    'brands_no_brands': 'ブランドが見つかりません',
    'brands_browse_all': 'すべてのブランドを見る',
    'brands_count': '{count}ブランド',
    'shipping_title': '配送ポリシー',
    'shipping_subtitle': '配送オプションとポリシーについて',
    'shipping_options': '配送オプション',
    'shipping_processing': '処理中',
    'shipping_delivery_col': 'お届け',
    'shipping_carriers': '運送会社',
    'shipping_carriers_desc': 'UPS、FedEx、DHLなどの信頼できる運送会社を使用',
    'shipping_countries': '対応国',
    'shipping_countries_desc': '100カ国以上に配送可能',
    'shipping_tracking': '追跡',
    'shipping_tracking_desc': 'リアルタイムで追跡情報を提供',
    'shipping_free_title': '送料無料',
    'shipping_free_text': '条件を満たした注文は送料無料',
    'shipping_quote': '配送見積',
    'shipping_quote_text': '大口注文の配送見積りは別途お問い合わせ',
    'shipping_special': '特別注文',
    'shipping_instock': '在庫あり',
    'shipping_notes_col': '備考',
    'shipping_carrier_col': '運送会社',
    'support_title': 'サポート',
    'support_subtitle': 'お問い合わせ方法',
    'support_contact_title': 'お問い合わせ',
    'support_email': 'メール',
    'support_email_label': 'メールアドレス',
    'support_email_desc': '24時間以内にご返信',
    'support_phone': '電話番号',
    'support_phone_desc': '平日 9:00-18:00',
    'support_livechat': 'ライブチャット',
    'support_livechat_desc': '今すぐエージェントとお話ください',
    'support_faq': 'よくある質問',
    'support_faq1_q': '注文の方法を教えてください',
    'support_faq1_a': '当社のウェブサイトから直接ご注文いただけます',
    'support_faq2_q': '配送オプションは？',
    'support_faq2_a': 'UPS、FedEx、DHLによる通常配送、迅速配送、お急ぎ配送を提供',
    'support_faq3_q': '返品ポリシーについて教えてください',
    'support_faq3_a': '標準 品は、開封されていない状態で30日以内に返品可能',
    'support_faq4_q': '見積りを依頼するには？',
    'support_faq4_a': '製品ページの「見積を依頼」をクリック',
    'support_faq5_q': '大量注文の割引はありますか？',
    'support_faq5_a': 'はい、大口注文には別途お問い合わせください',
    'support_name_label': 'お名前',
    'support_subject_label': '件名',
    'support_message_label': 'メッセージ',
    'support_send_btn': '送信',
    'support_sent_title': '送信完了',
    'support_sent_desc': 'お問い合わせありがとうございます。24時間以内にご返信いたします。',
    'error_title': 'エラー',
    'error_generic': 'エラーが発生しました。もう一度お試しください。',
    'error_404_title': 'ページが見つかりません',
    'error_404_desc': 'お探しのページは存在しないか、移動した可能性があります。',
    'error_404_button': 'ホームに戻る',
    'error_back_home': 'ホームに戻る',
    'aria_language_options': '言語オプション',
    'aria_close_menu': 'メニューを閉じる',
    'aria_open_menu': 'メニューを開く',
    'aria_remove_item': 'アイテムを削除',
    'aria_increase_quantity': '数量を増やす',
    'aria_decrease_quantity': '数量を減らす',
    'aria_select_language': '言語を選択',
    'placeholder_name_example': '山田 太郎',
    'placeholder_company_example': '株式会社サンプル',
    'placeholder_email_example': 'your@email.com',
    'placeholder_phone_example': '+81 3-1234-5678',
    'placeholder_notes_example': '追加のメモをここに入力...',
    'placeholder_search_example': '製品を検索...',
    'cat_Flow_Control': '流量制御',
    'cat_Environmental': '環境',
    'cat_General': '一般',
    'cat_Industrial_Measurement': '工業計測',
    'cat_Laboratory_Equipment': '実験機器',
    'cat_Pumps_Valves': 'ポンプ・バルブ',
    'filter_availability': '在庫状況',
    'filter_brand': 'ブランド',
    'filter_in_stock_only': '在庫のみ',
    'filter_min': '最小',
    'filter_max': '最大',
    'filter_price_range': '価格帯',
    'hero_title': '高品質実験機器',
    'hero_subtitle': 'ラボに必要なすべてが見つかる',
    'hero_cta_shop': '製品を見る',
    'hero_cta_quote': '見積を依頼',
    'quote_title': '見積を依頼',
    'quote_subtitle': 'フォームにご記入いただければ、24時間以内にご連絡いたします',
    'quote_sidebar_title': '選択した製品',
    'quote_items_selected': '{count}件の製品を選択中',
    'quote_select_product': '製品を選択',
    'quote_review_msg': '送信前に内容をご確認ください',
    'quote_submit': '送信',
    'quote_submitting': '送信中...',
    'quote_success': '見積依頼が正常に送信されました！',
    'quote_submitted_title': '送信完了',
    'quote_response_time': '応答時間',
    'quote_response_value': '24時間以内',
    'quote_within_24h': '24時間以内にご連絡いたします',
    'quote_name': '氏名',
    'quote_email': 'メールアドレス',
    'quote_phone': '電話番号',
    'quote_company': '会社名',
    'quote_company_optional': '会社名（任意）',
    'quote_message': 'メッセージ',
    'quote_notes': '備考',
    'quote_items_label': '製品',
    'quote_items_for': '{count}件の製品',
    'quote_items_selected_label': '件選択中',
    'quote_number_label': '#',
    'quote_no_items': '製品が選択されていません',
    'quote_empty': '見積リストは空です',
    'quote_browse_products': '製品を探す',
    'quote_add_all': 'すべてフォームに追加',
    'quote_cart_items': 'カート内商品',
    'quote_contact_info': '連絡先情報',
    'quote_fill_required': '必須項目をすべて入力してください',
    'quote_email_required': 'メールアドレスは必須',
    'quote_full_name_required': '氏名は必須',
    'quote_phone_optional': '電話番号（任意）',
}

# HI translations (Hindi)
HI = {
    k: EN.get(k, '') for k in EN_KEYS
}

# AR translations (Arabic)  
AR = {
    k: EN.get(k, '') for k in EN_KEYS
}

# PT translations (Portuguese)
PT = {
    k: EN.get(k, '') for k in EN_KEYS
}

# For zh: use existing ZH plus zh_extras
ZH_FULL = dict(ZH)
ZH_FULL.update(ZH_EXTRAS)

# Use EN for any missing keys in other languages
for lang_dict in [ES, JA, HI, AR, PT]:
    for k in EN_KEYS:
        if k not in lang_dict:
            lang_dict[k] = EN.get(k, f'[{k}]')

# Build the file
def make_block(name, trans, comment_name):
    lines = [f'\n// =========================================================\n']
    lines.append(f'//  {comment_name}\n')
    lines.append(f'// =========================================================\n')
    lines.append(f'const {name}: TranslationKeys = {{\n')
    for k in EN_KEYS:
        v = trans.get(k, EN.get(k, f'[{k}]'))
        v = v.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"  {k}: '{v}',\n")
    lines.append('}\n')
    return ''.join(lines)

header = """// Translation keys for LabProGlobal
// Auto-generated - all keys from TranslationKeys type
// Languages: en, zh, es, ja, hi, ar, pt

export type Locale = 'en' | 'zh' | 'es' | 'ja' | 'hi' | 'ar' | 'pt'

export const LOCALES: { code: Locale; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'zh', label: '中文' },
  { code: 'es', label: 'Español' },
  { code: 'ja', label: '日本語' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'ar', label: 'العربية' },
  { code: 'pt', label: 'Português' },
]

export type TranslationKeys = {
"""

# Get TranslationKeys type from existing file
tk_match = re.search(r'export type TranslationKeys = \{(.*?)\n\}', content, re.DOTALL)
if tk_match:
    type_body = tk_match.group(1)
    header += type_body + '\n}\n'
else:
    # Generate from EN_KEYS
    for k in EN_KEYS:
        header += f'  {k}: string\n'
    header += '}\n'

footer = """

// =========================================================
//  Translation Data
// =========================================================

export const translations: Record<Locale, TranslationKeys> = {
"""

en_block = make_block('en', EN, '英语 (English)')
zh_block = make_block('zh', ZH_FULL, '简体中文')
es_block = make_block('es', ES, '西班牙语')
ja_block = make_block('ja', JA, '日语')
hi_block = make_block('hi', HI, '印地语 (हिन्दी)')
ar_block = make_block('ar', AR, '阿拉伯语 (RTL)')
pt_block = make_block('pt', PT, '葡萄牙语')

footer += en_block + zh_block + es_block + ja_block + hi_block + ar_block + pt_block
footer += '}\n'

full_content = header + footer

with open(r'E:\novatech-store\lib\i18n\translations.ts', 'w', encoding='utf-8') as f:
    f.write(full_content)

print(f"Written {len(full_content)} chars, {len(full_content.splitlines())} lines")
print("Done!")
