"""Rebuild ES block from EN template with Spanish translations."""
import sys
sys.stdout.reconfigure(encoding='utf-8')
import re

# Complete Spanish translations for ALL 387 keys
# Organized by category matching EN block structure
ES = {
    # Navigation
    'nav_search_placeholder': 'Buscar por nombre de producto, SKU o marca...',
    'nav_get_quote': 'Obtener Cotización',
    'nav_sign_in': 'Iniciar Sesión',
    'nav_my_account': 'Mi Cuenta',
    'nav_orders': 'Pedidos',
    'nav_sign_out': 'Cerrar Sesión',
    'nav_all_products': 'Todos los Productos',
    'nav_all_categories': 'Todas las Categorías',
    'nav_cart': 'Carrito',
    'nav_view_all': 'Ver Todo',
    'nav_free_shipping': 'Envío Gratuito',
    # Cart
    'cart_title': 'Carrito de Compras',
    'cart_empty': 'Tu carrito está vacío',
    'cart_empty_desc': 'Explore nuestros productos y añada artículos a su carrito.',
    'cart_continue': 'Continuar Comprando',
    'cart_checkout': 'Proceder al Pago',
    'cart_subtotal': 'Subtotal',
    'cart_quantity': 'Cantidad',
    'cart_remove': 'Eliminar',
    'cart_item_added': 'Producto añadido al carrito',
    'cart_total': 'Total',
    'cart_request_quote': 'Solicitar Cotización',
    'cart_estimated_shipping': 'Envío estimado',
    'cart_free_shipping': 'GRATIS',
    'cart_final_total': 'Total Final',
    'cart_browse_products': 'Explorar Productos',
    'cart_clear': 'Vaciar Carrito',
    'cart_continue_shopping': 'Continuar Comprando',
    'cart_free_shipping_hint': 'Añada {amount} más para envío gratuito',
    'cart_items_count': '{count} artículos',
    'cart_order_summary': 'Resumen del Pedido',
    'cart_shipping': 'Envío',
    'cart_shipping_free': 'GRATIS',
    'cart_sku_label': 'SKU',
    'cart_tax': 'Impuestos',
    'cart_tax_at_checkout': 'Impuestos calculados en el pago',
    # Account
    'account_title': 'Mi Cuenta',
    'account_welcome': 'Bienvenido de nuevo',
    'account_sign_in': 'Iniciar Sesión',
    'account_register': 'Crear Cuenta',
    'account_email': 'Correo Electrónico',
    'account_password': 'Contraseña',
    'account_remember_me': 'Recuérdame',
    'account_forgot_password': '¿Olvidó su contraseña?',
    'account_no_account': '¿No tiene cuenta?',
    'account_have_account': '¿Ya tiene cuenta?',
    'account_sign_in_title': 'Iniciar Sesión en Su Cuenta',
    'account_register_title': 'Crear una Cuenta',
    'account_orders': 'Mis Pedidos',
    'account_quotes': 'Mis Cotizaciones',
    'account_addresses': 'Direcciones',
    'account_settings': 'Configuración',
    'account_logout': 'Cerrar Sesión',
    'account_first_name': 'Nombre',
    'account_last_name': 'Apellidos',
    'account_company': 'Empresa',
    'account_phone': 'Teléfono',
    'account_addresses_desc': 'Gestione sus direcciones de envío y facturación',
    'account_browse_products': 'Explorar Productos',
    'account_no_orders': 'Aún no hay pedidos',
    'account_order_date': 'Fecha del pedido',
    'account_order_status': 'Estado del pedido',
    'account_order_total': 'Total del pedido',
    'account_order_view': 'Ver pedido',
    'account_order_items': 'Artículos del pedido',
    'account_orders_appear_here': 'Sus pedidos aparecerán aquí',
    'account_orders_desc': 'Vea el historial y el estado de sus pedidos',
    'account_quotes_desc': 'Vea sus solicitudes de cotización enviadas',
    # Checkout
    'checkout_title': 'Pago',
    'checkout_steps_title': 'Pasos de Pago',
    'checkout_step1': 'Carrito',
    'checkout_step2': 'Envío',
    'checkout_step3': 'Revisar',
    'checkout_back_cart': 'Volver al Carrito',
    'checkout_not_configured': 'El pago aún no está configurado. Por favor, solicite una cotización en su lugar.',
    'checkout_request_quote': 'Solicitar Cotización',
    # Address Book
    'addr_title': 'Direcciones',
    'addr_subtitle': 'Gestione sus direcciones de envío y facturación',
    'addr_add_address': 'Añadir dirección',
    'addr_new_address': 'Nueva dirección',
    'addr_label': 'Etiqueta de dirección',
    'addr_first_name': 'Nombre',
    'addr_last_name': 'Apellido',
    'addr_address1': 'Dirección línea 1',
    'addr_address2': 'Dirección línea 2',
    'addr_city': 'Ciudad',
    'addr_state': 'Estado / Provincia',
    'addr_zip': 'Código postal',
    'addr_country': 'País',
    'addr_phone_optional': 'Teléfono (opcional)',
    'addr_save': 'Guardar dirección',
    'addr_cancel': 'Cancelar',
    'addr_no_addresses': 'Sin direcciones guardadas',
    'addr_add_first': 'Añade tu primera dirección',
    'addr_add_first_desc': 'Añade una dirección de envío o facturación para un pago más rápido.',
    'addr_add_first_btn': 'Añadir dirección',
    'addr_default': 'Por defecto',
    'addr_edit': 'Editar',
    'addr_delete': 'Eliminar',
    'addr_loading': 'Cargando direcciones...',
    # Quotes
    'quotes_title': 'Mis Cotizaciones',
    'quotes_subtitle': 'Ver sus solicitudes de cotización enviadas',
    'quotes_loading': 'Cargando cotizaciones...',
    'quotes_no_quotes': 'Sin cotizaciones aún',
    'quotes_no_quotes_desc': 'Cuando envíe una solicitud de cotización, aparecerá aquí.',
    'quotes_request_new': 'Solicitar cotización',
    'quotes_request_quote': 'Solicitar cotización',
    'quotes_quote_number': 'Cotización #',
    'quotes_date': 'Fecha',
    'quotes_items': 'Artículos',
    'quotes_est_total': 'Total estimado',
    'quotes_status': 'Estado',
    'quotes_status_pending': 'Pendiente',
    'quotes_status_approved': 'Aprobada',
    'quotes_status_rejected': 'Rechazada',
    # Quote Form
    'quote_title': 'Solicitar Cotización',
    'quote_subtitle': 'Complete el formulario y nos pondremos en contacto con usted en 24 horas',
    'quote_sidebar_title': 'Productos Seleccionados',
    'quote_items_selected': '{count} productos seleccionados',
    'quote_select_product': 'Seleccionar producto',
    'quote_review_msg': 'Revise su solicitud antes de enviar',
    'quote_submit': 'Enviar Solicitud',
    'quote_submitting': 'Enviando...',
    'quote_success': '¡Solicitud enviada con éxito!',
    'quote_submitted_title': 'Solicitud Enviada',
    'quote_response_time': 'Tiempo de respuesta',
    'quote_response_value': 'En 24 horas',
    'quote_within_24h': 'Nos pondremos en contacto con usted en 24 horas',
    'quote_name': 'Nombre completo',
    'quote_email': 'Correo electrónico',
    'quote_phone': 'Teléfono',
    'quote_company': 'Empresa',
    'quote_company_optional': 'Empresa (opcional)',
    'quote_message': 'Mensaje',
    'quote_notes': 'Notas adicionales',
    'quote_items_label': 'Productos',
    'quote_items_for': '{count} productos',
    'quote_items_selected_label': 'artículos seleccionados',
    'quote_number_label': '#',
    'quote_no_items': 'No hay productos seleccionados',
    'quote_empty': 'Su lista de cotización está vacía',
    'quote_browse_products': 'Explorar Productos',
    'quote_add_all': 'Añadir todos al formulario',
    'quote_cart_items': 'artículos del carrito',
    'quote_contact_info': 'Información de contacto',
    'quote_fill_required': 'Por favor complete todos los campos obligatorios',
    'quote_email_required': 'Correo electrónico obligatorio',
    'quote_full_name_required': 'Nombre completo obligatorio',
    # Contact
    'contact_title': 'Contáctenos',
    'contact_desc': '¿Tiene preguntas? Estamos aquí para ayudar.',
    'contact_form_title': 'Envíenos un mensaje',
    'contact_name': 'Nombre completo',
    'contact_email': 'Correo electrónico',
    'contact_phone': 'Teléfono',
    'contact_company': 'Empresa',
    'contact_subject': 'Asunto',
    'contact_message': 'Mensaje',
    'contact_send': 'Enviar Mensaje',
    'contact_office_hours': 'Horario de oficina',
    'contact_response_time': 'Nos comprometemos a responder en 24 horas',
    'contact_address': 'Dirección',
    'contact_phone_label': 'Teléfono',
    'contact_email_label': 'Correo electrónico',
    # Auth
    'auth_login_title': 'Iniciar Sesión',
    'auth_login_desc': 'Inicie sesión para gestionar sus pedidos y solicitudes de cotización.',
    'auth_login_button': 'Iniciar Sesión',
    'auth_register_title': 'Crear Cuenta',
    'auth_register_desc': 'Cree su cuenta LabProGlobal para gestionar pedidos y solicitar cotizaciones.',
    'auth_email': 'Correo electrónico',
    'auth_password': 'Contraseña',
    'auth_confirm_password': 'Confirmar contraseña',
    'auth_forgot_password': '¿Olvidó su contraseña?',
    'auth_reset_title': 'Restablecer Contraseña',
    'auth_reset_desc': 'Ingrese su correo electrónico y le enviaremos un enlace para restablecer su contraseña.',
    'auth_reset_button': 'Enviar enlace',
    'auth_reset_success': 'Correo de restablecimiento enviado',
    'auth_reset_error': 'No se encontró ninguna cuenta con ese correo electrónico',
    'auth_no_account': '¿No tiene cuenta?',
    'auth_have_account': '¿Ya tiene cuenta?',
    'auth_create_account': 'Crear cuenta',
    'auth_login_google': 'Iniciar sesión con Google',
    'auth_or': 'o',
    'auth_min_password': 'Al menos 8 caracteres',
    'auth_invalid_credentials': 'Credenciales inválidas',
    'auth_email_required': 'El correo electrónico es obligatorio',
    'auth_password_required': 'La contraseña es obligatoria',
    'auth_passwords_match': 'Las contraseñas deben coincidir',
    'auth_invalid_email': 'Correo electrónico inválido',
    'auth_login_success': 'Inicio de sesión exitoso',
    'auth_logout_success': 'Sesión cerrada',
    'auth_auth_failed': 'Autenticación fallida',
    'auth_company_optional': 'Empresa (opcional)',
    'auth_create_account_btn': 'Crear Cuenta',
    'auth_create_account_link': 'Crear cuenta',
    'auth_join_desc': 'Únase a miles de laboratorios que confían en LabProGlobal',
    'auth_name': 'Nombre',
    'auth_or_continue': 'o continuar como',
    'auth_sign_in': 'Iniciar Sesión',
    'auth_sign_in_link': 'Iniciar sesión',
    'auth_sign_in_subtitle': 'Inicie sesión para acceder a su cuenta',
    'auth_sign_up': 'Registrarse',
    'auth_signing_in': 'Iniciando sesión...',
    'auth_welcome_back': 'Bienvenido de nuevo',
    'auth_demo_mode': 'Modo Demo',
    'auth_demo_mode_notice': 'Está usando credenciales de demostración',
    'auth_demo_mode_setup': 'Configure DATABASE_URL y NEXTAUTH_SECRET para habilitar la autenticación real',
    'auth_demo_credentials': 'Credenciales de demostración',
    'auth_demo_email': 'demo@labproglobal.com',
    'auth_demo_password': 'demo123',
    'auth_env_setup_notice': 'Configure las variables de entorno para habilitar la autenticación',
    'auth_already_have': 'Ya tiene cuenta',
    'auth_enter_password': 'Ingrese su contraseña',
    # Footer
    'footer_company': 'LabProGlobal',
    'footer_tagline': 'Su socio de confianza en equipos de laboratorio',
    'footer_contact': 'Contacto',
    'footer_newsletter': 'Boletín',
    'footer_newsletter_desc': 'Reciba las últimas novedades y ofertas especiales.',
    'footer_email': 'Su correo electrónico',
    'footer_subscribe': 'Suscribirse',
    'footer_categories': 'Categorías',
    'footer_support': 'Soporte',
    'footer_about': 'Nosotros',
    'footer_help': 'Centro de Ayuda',
    'footer_returns': 'Devoluciones',
    'footer_shipping': 'Envíos',
    'footer_faq': 'Preguntas Frecuentes',
    'footer_contact_us': 'Contáctenos',
    'footer_legal': 'Legal',
    'footer_privacy': 'Política de Privacidad',
    'footer_terms': 'Términos de Servicio',
    'footer_returns_policy': 'Política de Devoluciones',
    'footer_copyright': '© 2024 LabProGlobal. Todos los derechos reservados.',
    'footer_all_rights': 'Todos los derechos reservados',
    'footer_description': 'Su socio de confianza en equipos de laboratorio de alta calidad.',
    'footer_account_col': 'Mi Cuenta',
    'footer_products_col': 'Productos',
    'footer_services_col': 'Servicios',
    'footer_quick_links': 'Enlaces Rápidos',
    'footer_all_products': 'Todos los Productos',
    'footer_sign_in': 'Iniciar Sesión',
    'footer_create_account': 'Crear Cuenta',
    'footer_my_orders': 'Mis Pedidos',
    'footer_my_quotes': 'Mis Cotizaciones',
    'footer_address_book': 'Libro de Direcciones',
    'footer_bulk_orders': 'Pedidos en Volumen',
    'footer_request_quote': 'Solicitar Cotización',
    'footer_technical_support': 'Soporte Técnico',
    'footer_shipping_policy': 'Política de Envíos',
    'footer_returns_refunds': 'Devoluciones y Reembolsos',
    'footer_rights': 'Todos los derechos reservados',
    # Terms
    'terms_title': 'Términos de Servicio',
    'terms_last_updated': 'Última actualización:',
    'terms_section1': '1. Aceptación de los Términos',
    'terms_section2': '2. Servicios y Productos',
    'terms_section3': '3. Cuentas de Usuario',
    'terms_section4': '4. Órdenes y Precios',
    'terms_section5': '5. Envío y Entrega',
    'terms_section6': '6. Devoluciones y Reembolsos',
    'terms_section7': '7. Responsabilidad',
    'terms_section8': '8. Propiedad Intelectual',
    'terms_section9': '9. Ley Aplicable',
    'terms_section10': '10. Contacto',
    'terms_item1': 'Al acceder o utilizar nuestro sitio web, usted acepta estar sujeto a estos Términos de Servicio.',
    'terms_item2': 'Ofrecemos equipos y suministros de laboratorio para diversas aplicaciones científicas e industriales.',
    'terms_item3': 'Usted es responsable de mantener la confidencialidad de su cuenta y contraseña.',
    'terms_item4': 'Los precios mostrados están en USD y pueden cambiar sin previo aviso. Nos reservamos el derecho de rechazar o cancelar pedidos.',
    'terms_item5': 'Los tiempos de envío son estimados. No somos responsables de retrasos causados por el transportista.',
    'terms_item6': 'Consulte nuestra Política de Devoluciones para obtener información detallada sobre devoluciones y reembolsos.',
    'terms_item7': 'En la máxima medida permitida por la ley, no somos responsables de daños indirectos o consecuentes.',
    'terms_item8': 'Todo el contenido de este sitio web es propiedad de LabProGlobal y está protegido por leyes de propiedad intelectual.',
    'terms_item9': 'Estos términos se rigen por las leyes del Estado de Delaware, EE.UU.',
    'terms_item10': 'Para cualquier pregunta sobre estos términos, contáctenos en legal@labproglobal.com',
    # Privacy
    'privacy_title': 'Política de Privacidad',
    'privacy_last_updated': 'Última actualización:',
    'privacy_section1': '1. Información que Recopilamos',
    'privacy_section2': '2. Cómo Utilizamos su Información',
    'privacy_section3': '3. Compartir Información',
    'privacy_section4': '4. Seguridad de Datos',
    'privacy_section5': '5. Cookies',
    'privacy_section6': '6. Sus Derechos',
    'privacy_section7': '7. Contacto',
    'privacy_item1a': 'Información de contacto (nombre, correo electrónico, teléfono, empresa)',
    'privacy_item1b': 'Direcciones de envío y facturación',
    'privacy_item1c': 'Historial de pedidos y detalles de transacciones',
    'privacy_item1d': 'Solicitudes de cotización e historial de comunicaciones',
    'privacy_item1e': 'Datos de uso y análisis',
    'privacy_item1f': 'Mejorar nuestro sitio web y servicios',
    'privacy_item2a': 'No vendemos su información personal. Compartimos datos solo con: proveedores de servicios que asisten nuestras operaciones, fuerzas del orden cuando la ley lo requiera, y socios comerciales con su consentimiento explícito.',
    'privacy_item2b': 'Implementamos medidas de seguridad estándar de la industria, incluyendo cifrado SSL, servidores seguros, controles de acceso y revisiones de seguridad periódicas para proteger su información personal.',
    'privacy_item2c': 'Utilizamos cookies y tecnologías similares para mantener su carrito de compras, recordar sus preferencias, analizar el tráfico del sitio y personalizar su experiencia. Puede controlar las cookies a través de la configuración de su navegador.',
    'privacy_item3': 'Tiene derecho a: acceder a sus datos personales, corregir información inexacta, solicitar la eliminación de sus datos, optar por no recibir comunicaciones de marketing y solicitar la portabilidad de datos. Contáctenos en privacy@labproglobal.com para ejercer estos derechos.',
    'privacy_item4': 'Para consultas relacionadas con la privacidad, contacte a nuestro Oficial de Protección de Datos en',
    'privacy_item5': 'Todos los datos se almacenan de forma segura en servidores cifrados.',
    'privacy_item6': 'Puede solicitar la eliminación de su cuenta y datos en cualquier momento.',
    'privacy_item7': 'Cumplimos con las leyes de protección de datos aplicables, incluyendo el RGPD.',
    # Returns
    'returns_title': 'Devoluciones y Reembolsos',
    'returns_subtitle': 'Queremos que esté completamente satisfecho con su compra.',
    'returns_30day': 'Devoluciones de 30 días',
    'returns_30day_desc': 'Los artículos estándar pueden devolverse dentro de los 30 días posteriores a la entrega',
    'returns_easy': 'Proceso Fácil',
    'returns_easy_desc': 'Solicite una devolución a través de su cuenta',
    'returns_full': 'Reembolso Completo',
    'returns_full_desc': 'Reembolso procesado en 5-7 días hábiles',
    'returns_policy': 'Política de Devoluciones',
    'returns_policy_standard': 'Productos Estándar: Reembolso completo dentro de 30 días en estado sin abrir y sin usar.',
    'returns_policy_special': 'Pedidos Especiales: No pueden devolverse a menos que estén defectuosos.',
    'returns_policy_defective': 'Productos Defectuosos: Contáctenos inmediatamente. Reemplazo o reembolso gratuito.',
    'returns_policy_shipping': 'Envío de Devolución: El cliente es responsable del envío estándar.',
    'returns_how': 'Cómo Devolver un Artículo',
    'returns_step1': 'Inicie sesión en su cuenta y vaya a Historial de Pedidos',
    'returns_step2': 'Seleccione el pedido y el artículo que desea devolver',
    'returns_step3': 'Elija un motivo de devolución y envíe su solicitud',
    'returns_step4': 'Recibirá una autorización de devolución y etiqueta de envío',
    'returns_step5': 'Empaque el artículo de forma segura y envíelo de vuelta',
    'returns_step6': 'Recibirá su reembolso una vez que procesemos la devolución',
    'returns_contact': 'Contactar Departamento de Devoluciones',
    'returns_need_help': '¿Necesita ayuda con una devolución?',
    # Products
    'products_page_title': 'Todos los Productos',
    'products_results_count': '{count} productos encontrados',
    'products_showing_range': 'Mostrando {from}–{to} de {total}',
    'products_no_results': 'No se encontraron productos',
    'products_prev': 'Anterior',
    'products_next': 'Siguiente',
    'products_add_to_cart': 'Añadir al Carrito',
    'products_brand': 'Marca',
    'products_in_stock': 'En Stock',
    'products_out_of_stock': 'Agotado',
    'products_on_order': 'Sobre Pedido',
    'products_lead_time': 'Tiempo de entrega',
    'products_sku': 'SKU',
    'products_related': 'Productos Relacionados',
    'products_request_quote': 'Solicitar Cotización',
    'products_specifications': 'Especificaciones',
    'products_title': 'Productos',
    'products_view_all': 'Ver Todos',
    'products_sort_featured': 'Destacados',
    'products_sort_newest': 'Más Nuevos',
    'products_sort_price_asc': 'Precio: Menor a Mayor',
    'products_sort_price_desc': 'Precio: Mayor a Menor',
    # Product Detail
    'product_sku_label': 'SKU',
    'product_key_specs': 'Especificaciones Clave',
    'product_full_specs': 'Especificaciones Completas',
    'product_expert_support': 'Soporte Experto',
    'product_fast_shipping': 'Envío Rápido',
    'product_secure_payment': 'Pago Seguro',
    'product_returns': '30 Días de Devolución',
    'product_home': 'Inicio',
    'product_products': 'Productos',
    'product_related': 'Productos Relacionados',
    # Home
    'home_hero_title': 'Equipos de Laboratorio de Alta Calidad',
    'home_hero_subtitle': 'Encuentre todo lo que necesita para su laboratorio: instrumentos de precisión, soluciones de flujo, analizadores y más.',
    'home_hero_button': 'Explorar Productos',
    'home_hero_quote': 'Solicitar Cotización',
    'home_featured': 'Productos Destacados',
    'home_categories': 'Categorías Populares',
    'home_why': 'Por Qué Elegirnos',
    'home_quality': 'Calidad Garantizada',
    'home_quality_desc': 'Todos los productos cumplen con los estándares internacionales de calidad y están respaldados por garantía del fabricante.',
    'home_pricing': 'Precios Competitivos',
    'home_pricing_desc': 'Ofrecemos precios transparentes y competitivos sin tarifas ocultas. Solicite una cotización para precios personalizados.',
    'home_shipping': 'Envío Rápido',
    'home_shipping_desc': 'Envío rápido y seguro con seguimiento en tiempo real. Envío gratuito en pedidos que cumplan los requisitos.',
    'home_support': 'Soporte Experto',
    'home_support_desc': 'Nuestro equipo de expertos está disponible para ayudarle a elegir los productos adecuados para sus necesidades.',
    'home_view_all': 'Ver Todos',
    'home_view_product': 'Ver Producto',
    'home_add_to_cart': 'Añadir al Carrito',
    'home_get_quote': 'Obtener Cotización',
    'home_learn_more': 'Más Información',
    'home_featured_title': 'Productos Destacados',
    'home_featured_desc': 'Explore nuestra selección de equipos de laboratorio de alta calidad.',
    'home_featured_subtitle': 'Los mejores productos elegidos para usted',
    'home_categories_title': 'Categorías Populares',
    'home_categories_desc': 'Encuentre exactamente lo que necesitaBrowse por categoría.',
    'home_about_title': 'Sobre Nosotros',
    'home_about_p1': 'LabProGlobal es un proveedor líder de equipos y suministros de laboratorio de alta calidad.',
    'home_about_p2': 'Con años de experiencia en la industria, nos especializamos en proporcionar instrumentos de precisión, soluciones de flujo y equipos de análisis para laboratorios farmacéuticos, de investigación, industriales y clínicos.',
    'home_about_p3': 'Nuestra misión es apoyar los avances científicos proporcionando productos confiables y un servicio excepcional a precios competitivos.',
    'home_about_btn': 'Más Información',
    'home_trust': 'Construyendo Confianza',
    'home_trust_p1': 'Miles de laboratorios en todo el mundo confían en LabProGlobal para sus necesidades de equipos.',
    'home_trust_p2': 'Nos comprometemos a la calidad, la transparencia y la satisfacción del cliente en cada pedido.',
    'home_trust_p3': 'Nuestro equipo dedicado está aquí para ayudarle en cada paso del camino.',
    'home_newsletter_title': 'Boletín',
    'home_newsletter_desc': 'Reciba las últimas novedades, ofertas especiales y consejos de laboratorio.',
    'home_newsletter_placeholder': 'Su correo electrónico',
    'home_newsletter_button': 'Suscribirse',
    'home_newsletter_success': '¡Gracias por suscribirse!',
    'home_cta_title': '¿Necesita una Cotización Personalizada?',
    'home_cta_subtitle': 'Contáctenos hoy y le responderemos en 24 horas',
    'home_cta_button': 'Solicitar Cotización',
    'home_trust_quality': 'Calidad',
    'home_trust_quality_desc': 'Productos de alta calidad garantizada',
    'home_trust_pricing': 'Precios',
    'home_trust_pricing_desc': 'Precios competitivos y transparentes',
    'home_trust_shipping': 'Envío',
    'home_trust_shipping_desc': 'Envío rápido y seguro',
    'home_trust_support': 'Soporte',
    'home_trust_support_desc': 'Asistencia experta 24/7',
    # About
    'about_title': 'Sobre Nosotros',
    'about_hero_title': 'Sobre Nosotros',
    'about_hero_subtitle': 'Conozca más sobre LabProGlobal y nuestra misión.',
    'about_mission_title': 'Nuestra Misión',
    'about_mission_p1': 'En LabProGlobal, notre dedicamos a empower laboratories worldwide with high-quality, reliable laboratory equipment and instruments.',
    'about_mission_p2': 'Our mission is to accelerate scientific discovery by providing researchers and professionals with the tools they need to succeed.',
    'about_vision_title': 'Nuestra Visión',
    'about_vision_p1': 'Our vision is to be the most trusted partner for laboratory equipment and supplies globally.',
    'about_vision_p2': 'We strive to continuously expand our product offerings and improve our service to meet the evolving needs of the scientific community.',
    'about_values_title': 'Nuestros Valores',
    'about_quality': 'Calidad',
    'about_quality_desc': 'Only products that meet our rigorous quality standards make it to our catalog.',
    'about_innovation': 'Innovación',
    'about_innovation_desc': 'We continuously seek new and improved products to serve our customers better.',
    'about_integrity': 'Integridad',
    'about_integrity_desc': 'Honest pricing, transparent policies, and ethical business practices guide everything we do.',
    'about_customers': 'Clientes Primero',
    'about_customers_desc': 'Your success is our priority. We are here to support you at every step.',
    'about_team_title': 'Nuestro Equipo',
    'about_team_p1': 'Our team brings together expertise in laboratory equipment, supply chain management, and customer service.',
    'about_team_p2': 'We are passionate about science and committed to helping our customers achieve their research and operational goals.',
    'about_contact_title': 'Contáctenos',
    'about_contact_p1': 'Have questions or need assistance? Our team is here to help.',
    'about_contact_p2': 'Reach out to us through our contact form or browse our frequently asked questions for quick answers.',
    # Search
    'search_title': 'Buscar',
    'search_results_for': 'Resultados de búsqueda para',
    'search_results_count': '{count} resultados',
    'search_no_results': 'No se encontraron resultados',
    'search_browse_all': 'Ver todos los productos',
    'search_placeholder_hint': 'Escriba para buscar...',
    # Categories
    'categories_title': 'Categorías',
    'categories_subtitle': 'Explore por categoría',
    'categories_all_label': 'Todos los productos',
    'categories_browse_all': 'Ver Todos',
    'categories_subcategories': 'Subcategorías',
    'categories_no_products': 'No se encontraron productos en esta categoría',
    'categories_prev': 'Anterior',
    'categories_next': 'Siguiente',
    'categories_products_count': '{count} productos',
    'categories_page_of': 'Página {current} de {total}',
    'categories_sort_bar': 'Ordenar por',
    # Brands
    'brands_title': 'Marcas',
    'brands_subtitle': 'Explore por marca',
    'brands_products': '{count} productos',
    'brands_no_products': 'No hay productos de esta marca',
    'brands_no_brands': 'No se encontraron marcas',
    'brands_browse_all': 'Ver Todas las Marcas',
    'brands_count': '{count} marcas',
    # Shipping
    'shipping_title': 'Política de Envíos',
    'shipping_subtitle': 'Información sobre nuestras opciones y políticas de envío',
    'shipping_options': 'Opciones de Envío',
    'shipping_processing': 'Procesamiento',
    'shipping_delivery_col': 'Entrega',
    'shipping_carriers': 'Transportistas',
    'shipping_carriers_desc': 'Usamos transportistas confiables como UPS, FedEx y DHL',
    'shipping_countries': 'Países',
    'shipping_countries_desc': 'Enviamos a más de 100 países',
    'shipping_tracking': 'Seguimiento',
    'shipping_tracking_desc': 'Reciba actualizaciones de seguimiento en tiempo real',
    'shipping_free_title': 'Envío Gratuito',
    'shipping_free_text': 'Disponible en pedidos que cumplan los requisitos',
    'shipping_quote': 'Cotización de Envío',
    'shipping_quote_text': 'Solicite una cotización de envío para pedidos grandes',
    'shipping_special': 'Pedidos Especiales',
    'shipping_instock': 'En stock',
    'shipping_notes_col': 'Notas',
    'shipping_carrier_col': 'Transportista',
    # Support
    'support_title': 'Soporte',
    'support_subtitle': '¿Cómo podemos ayudarle?',
    'support_contact_title': 'Contáctenos',
    'support_email': 'Correo electrónico',
    'support_email_label': 'Dirección de correo electrónico',
    'support_email_desc': 'Responderemos en 24 horas',
    'support_phone': 'Teléfono',
    'support_phone_desc': 'Lun-Vie 9am-6pm EST',
    'support_livechat': 'Chat en Vivo',
    'support_livechat_desc': 'Hable con un agente ahora',
    'support_faq': 'Preguntas Frecuentes',
    'support_faq1_q': '¿Cómo realizo un pedido?',
    'support_faq1_a': 'Puede realizar un pedido directamente a través de nuestro sitio web. Añada productos al carrito y proceda al pago.',
    'support_faq2_q': '¿Cuáles son sus opciones de envío?',
    'support_faq2_a': 'Ofrecemos envío estándar, urgente y expreso a través de UPS, FedEx y DHL.',
    'support_faq3_q': '¿Cuál es su política de devoluciones?',
    'support_faq3_a': 'Los artículos estándar pueden devolverse dentro de los 30 días. Consulte nuestra página de devoluciones para más detalles.',
    'support_faq4_q': '¿Cómo solicito una cotización?',
    'support_faq4_a': 'Haga clic en "Solicitar Cotización" en cualquier página de producto o utilicé el formulario de contacto.',
    'support_faq5_q': '¿Ofrecen descuentos por volumen?',
    'support_faq5_a': 'Sí, contáctenos para obtener precios especiales en pedidos grandes.',
    'support_name_label': 'Nombre',
    'support_subject_label': 'Asunto',
    'support_message_label': 'Mensaje',
    'support_send_btn': 'Enviar Mensaje',
    'support_sent_title': 'Mensaje Enviado',
    'support_sent_desc': 'Gracias por contactarnos. Le responderemos en 24 horas.',
    # Errors
    'error_title': 'Error',
    'error_generic': 'Ha ocurrido un error. Por favor, inténtelo de nuevo.',
    'error_404_title': 'Página No Encontrada',
    'error_404_desc': 'Lo sentimos, la página que está buscando no existe o ha sido movida.',
    'error_404_button': 'Volver al Inicio',
    'error_back_home': 'Volver al Inicio',
    # Accessibility
    'aria_language_options': 'Opciones de idioma',
    'aria_close_menu': 'Cerrar menú',
    'aria_open_menu': 'Abrir menú',
    'aria_remove_item': 'Eliminar artículo',
    'aria_increase_quantity': 'Aumentar cantidad',
    'aria_decrease_quantity': 'Disminuir cantidad',
    'aria_select_language': 'Seleccionar idioma',
    # Placeholders
    'placeholder_name_example': 'John Smith',
    'placeholder_company_example': 'Su Empresa S.A.',
    'placeholder_email_example': 'su@correo.com',
    'placeholder_phone_example': '+1 (555) 000-0000',
    'placeholder_notes_example': 'Añada notas adicionales aquí...',
    'placeholder_search_example': 'Buscar productos...',
    # Categories names
    'cat_Flow_Control': 'Control de Flujo',
    'cat_Environmental': 'Ambiental',
    'cat_General': 'General',
    'cat_Industrial_Measurement': 'Medición Industrial',
    'cat_Laboratory_Equipment': 'Equipos de Laboratorio',
    'cat_Pumps_Valves': 'Bombas y Válvulas',
    # Hero CTA
    'hero_title': 'Equipos de Laboratorio de Alta Calidad',
    'hero_subtitle': 'Encuentre todo lo que necesita para su laboratorio',
    'hero_cta_shop': 'Ver Productos',
    'hero_cta_quote': 'Solicitar Cotización',
}

with open(r'E:\novatech-store\lib\i18n\translations.ts', encoding='utf-8') as f:
    content = f.read()

es_start = content.find('const es: TranslationKeys = {')
if es_start == -1:
    print('ERROR: ES block not found!')
    sys.exit(1)

next_const = content.find('\nconst ', es_start + 10)
next_export = content.find('\nexport const', es_start + 10)
if next_const == -1 and next_export == -1:
    es_end = len(content)
elif next_const == -1:
    es_end = next_export
elif next_export == -1:
    es_end = next_const
else:
    es_end = min(next_const, next_export)

print(f'ES block: chars {es_start} to {es_end}')

# Build new ES block
new_es_lines = ['const es: TranslationKeys = {\n']
for key, value in sorted(ES.items()):
    new_es_lines.append(f"  {key}: '{value}',\n")
new_es_lines.append('}\n')

new_es = ''.join(new_es_lines)
new_content = content[:es_start] + new_es + content[es_end:]

with open(r'E:\novatech-store\lib\i18n\translations.ts', 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f'Done! ES block rebuilt with {len(ES)} keys')
