"""Rebuild ES language block from EN + Spanish translations."""
import sys
sys.stdout.reconfigure(encoding='utf-8')
import re

ES_TRANSLATIONS = {
    # Navigation
    'nav_search_placeholder': 'Buscar por nombre de producto, SKU o marca...',
    'nav_get_quote': 'Obtener Cotización',
    'nav_sign_in': 'Iniciar Sesión',
    'nav_my_account': 'Mi Cuenta',
    'nav_orders': 'Pedidos',
    'nav_sign_out': 'Cerrar Sesión',
    'nav_all_products': 'Todos los Productos',
    'nav_all_categories': 'Todas las Categorías',
    'nav_cart': 'Carrito',
    'nav_view_all': 'Ver Todo',
    # Cart
    'cart_title': 'Carrito de Compras',
    'cart_empty': 'Tu carrito está vacío',
    'cart_empty_desc': 'Explore nuestros productos y añada artículos a su carrito.',
    'cart_continue': 'Continuar Comprando',
    'cart_checkout': 'Proceder al Pago',
    'cart_subtotal': 'Subtotal',
    'cart_quantity': 'Cantidad',
    'cart_remove': 'Eliminar',
    'cart_item_added': 'Producto añadido al carrito',
    'cart_total': 'Total',
    'cart_request_quote': 'Solicitar Cotización',
    'cart_estimated_shipping': 'Envío estimado',
    'cart_free_shipping': 'GRATIS',
    'cart_final_total': 'Total Final',
    # Account
    'account_title': 'Mi Cuenta',
    'account_welcome': 'Bienvenido de nuevo',
    'account_sign_in': 'Iniciar Sesión',
    'account_register': 'Crear Cuenta',
    'account_email': 'Correo Electrónico',
    'account_password': 'Contraseña',
    'account_remember_me': 'Recuérdame',
    'account_forgot_password': '¿Olvidó su contraseña?',
    'account_no_account': '¿No tiene cuenta?',
    'account_have_account': '¿Ya tiene cuenta?',
    'account_sign_in_title': 'Iniciar Sesión en Su Cuenta',
    'account_register_title': 'Crear una Cuenta',
    'account_orders': 'Mis Pedidos',
    'account_quotes': 'Mis Cotizaciones',
    'account_addresses': 'Direcciones',
    'account_settings': 'Configuración',
    'account_logout': 'Cerrar Sesión',
    'account_first_name': 'Nombre',
    'account_last_name': 'Apellidos',
    'account_company': 'Empresa',
    'account_phone': 'Teléfono',
    'account_addresses_desc': 'Gestione sus direcciones de envío y facturación',
    'account_browse_products': 'Explorar Productos',
    'account_no_orders': 'Aún no hay pedidos',
    'account_order_date': 'Fecha del pedido',
    'account_order_status': 'Estado del pedido',
    'account_order_total': 'Total del pedido',
    'account_order_view': 'Ver pedido',
    # Checkout
    'checkout_title': 'Pago',
    'checkout_steps_title': 'Pasos de Pago',
    'checkout_step1': 'Carrito',
    'checkout_step2': 'Envío',
    'checkout_step3': 'Revisar',
    'checkout_back_cart': 'Volver al Carrito',
    'checkout_not_configured': 'El pago aún no está configurado. Por favor, solicite una cotización en su lugar.',
    'checkout_request_quote': 'Solicitar Cotización',
    # Address Book
    'addr_title': 'Direcciones',
    'addr_subtitle': 'Gestione sus direcciones de envío y facturación',
    'addr_add_address': 'Añadir dirección',
    'addr_new_address': 'Nueva dirección',
    'addr_label': 'Etiqueta de dirección',
    'addr_first_name': 'Nombre',
    'addr_last_name': 'Apellido',
    'addr_address1': 'Dirección línea 1',
    'addr_address2': 'Dirección línea 2',
    'addr_city': 'Ciudad',
    'addr_state': 'Estado / Provincia',
    'addr_zip': 'Código postal',
    'addr_country': 'País',
    'addr_phone_optional': 'Teléfono (opcional)',
    'addr_save': 'Guardar dirección',
    'addr_cancel': 'Cancelar',
    'addr_no_addresses': 'Sin direcciones guardadas',
    'addr_add_first': 'Añade tu primera dirección',
    'addr_add_first_desc': 'Añade una dirección de envío o facturación para un pago más rápido.',
    'addr_add_first_btn': 'Añadir dirección',
    'addr_default': 'Por defecto',
    'addr_edit': 'Editar',
    'addr_delete': 'Eliminar',
    'addr_loading': 'Cargando direcciones...',
    # Quotes
    'quotes_title': 'Mis Cotizaciones',
    'quotes_subtitle': 'Ver sus solicitudes de cotización enviadas',
    'quotes_loading': 'Cargando cotizaciones...',
    'quotes_no_quotes': 'Sin cotizaciones aún',
    'quotes_no_quotes_desc': 'Cuando envíe una solicitud de cotización, aparecerá aquí.',
    'quotes_request_new': 'Solicitar cotización',
    'quotes_request_quote': 'Solicitar cotización',
    'quotes_quote_number': 'Cotización #',
    'quotes_date': 'Fecha',
    'quotes_items': 'Artículos',
    'quotes_est_total': 'Total estimado',
    'quotes_status': 'Estado',
    'quotes_status_pending': 'Pendiente',
    'quotes_status_approved': 'Aprobada',
    'quotes_status_rejected': 'Rechazada',
    # Contact
    'contact_title': 'Contáctenos',
    'contact_desc': '¿Tiene preguntas? Estamos aquí para ayudar.',
    'contact_form_title': 'Envíenos un mensaje',
    'contact_name': 'Nombre completo',
    'contact_email': 'Correo electrónico',
    'contact_phone': 'Teléfono',
    'contact_company': 'Empresa',
    'contact_subject': 'Asunto',
    'contact_message': 'Mensaje',
    'contact_send': 'Enviar Mensaje',
    'contact_office_hours': 'Horario de oficina',
    'contact_response_time': 'Nos comprometemos a responder en 24 horas',
    'contact_address': 'Dirección',
    'contact_phone_label': 'Teléfono',
    'contact_email_label': 'Correo electrónico',
    # Auth
    'auth_login_title': 'Iniciar Sesión',
    'auth_login_desc': 'Inicie sesión para gestionar sus pedidos y solicitudes de cotización.',
    'auth_login_button': 'Iniciar Sesión',
    'auth_register_title': 'Crear Cuenta',
    'auth_register_desc': 'Cree su cuenta LabProGlobal para gestionar pedidos y solicitar cotizaciones.',
    'auth_email': 'Correo electrónico',
    'auth_password': 'Contraseña',
    'auth_confirm_password': 'Confirmar contraseña',
    'auth_forgot_password': '¿Olvidó su contraseña?',
    'auth_reset_title': 'Restablecer Contraseña',
    'auth_reset_desc': 'Ingrese su correo electrónico y le enviaremos un enlace para restablecer su contraseña.',
    'auth_reset_button': 'Enviar enlace',
    'auth_reset_success': 'Correo de restablecimiento enviado',
    'auth_reset_error': 'No se encontró ninguna cuenta con ese correo electrónico',
    'auth_no_account': '¿No tiene cuenta?',
    'auth_have_account': '¿Ya tiene cuenta?',
    'auth_create_account': 'Crear cuenta',
    'auth_login_google': 'Iniciar sesión con Google',
    'auth_or': 'o',
    'auth_min_password': 'Al menos 8 caracteres',
    'auth_invalid_credentials': 'Credenciales inválidas',
    'auth_email_required': 'El correo electrónico es obligatorio',
    'auth_password_required': 'La contraseña es obligatoria',
    'auth_passwords_match': 'Las contraseñas deben coincidir',
    'auth_invalid_email': 'Correo electrónico inválido',
    'auth_login_success': 'Inicio de sesión exitoso',
    'auth_logout_success': 'Sesión cerrada',
    # Footer
    'footer_company': 'LabProGlobal',
    'footer_tagline': 'Su socio de confianza en equipos de laboratorio',
    'footer_contact': 'Contacto',
    'footer_newsletter': 'Boletín',
    'footer_newsletter_desc': 'Reciba las últimas novedades y ofertas especiales.',
    'footer_email': 'Su correo electrónico',
    'footer_subscribe': 'Suscribirse',
    'footer_categories': 'Categorías',
    'footer_support': 'Soporte',
    'footer_about': 'Nosotros',
    'footer_help': 'Centro de Ayuda',
    'footer_returns': 'Devoluciones',
    'footer_shipping': 'Envíos',
    'footer_faq': 'Preguntas Frecuentes',
    'footer_contact_us': 'Contáctenos',
    'footer_legal': 'Legal',
    'footer_privacy': 'Política de Privacidad',
    'footer_terms': 'Términos de Servicio',
    'footer_returns_policy': 'Política de Devoluciones',
    'footer_copyright': '© 2024 LabProGlobal. Todos los derechos reservados.',
    'footer_all_rights': 'Todos los derechos reservados',
    # Terms
    'terms_title': 'Términos de Servicio',
    'terms_last_updated': 'Última actualización:',
    'terms_section1': '1. Aceptación de los Términos',
    'terms_section2': '2. Servicios y Productos',
    'terms_section3': '3. Cuentas de Usuario',
    'terms_section4': '4. Órdenes y Precios',
    'terms_section5': '5. Envío y Entrega',
    'terms_section6': '6. Devoluciones y Reembolsos',
    'terms_section7': '7. Responsabilidad',
    'terms_section8': '8. Propiedad Intelectual',
    'terms_section9': '9. Ley Aplicable',
    'terms_section10': '10. Contacto',
    'terms_item1': 'Al acceder o utilizar nuestro sitio web, usted acepta estar sujeto a estos Términos de Servicio.',
    'terms_item2': 'Ofrecemos equipos y suministros de laboratorio para diversas aplicaciones científicas e industriales.',
    'terms_item3': 'Usted es responsable de mantener la confidencialidad de su cuenta y contraseña.',
    'terms_item4': 'Los precios mostrados están en USD y pueden cambiar sin previo aviso. Nos reservamos el derecho de rechazar o cancelar pedidos.',
    'terms_item5': 'Los tiempos de envío son estimados. No somos responsables de retrasos causados por el transportista.',
    'terms_item6': 'Consulte nuestra Política de Devoluciones para obtener información detallada sobre devoluciones y reembolsos.',
    'terms_item7': 'En la máxima medida permitida por la ley, no somos responsables de daños indirectos o consecuentes.',
    'terms_item8': 'Todo el contenido de este sitio web es propiedad de LabProGlobal y está protegido por leyes de propiedad intelectual.',
    'terms_item9': 'Estos términos se rigen por las leyes del Estado de Delaware, EE.UU.',
    'terms_item10': 'Para cualquier pregunta sobre estos términos, contáctenos en legal@labproglobal.com',
    # Privacy
    'privacy_title': 'Política de Privacidad',
    'privacy_last_updated': 'Última actualización:',
    'privacy_section1': '1. Información que Recopilamos',
    'privacy_section2': '2. Cómo Utilizamos su Información',
    'privacy_section3': '3. Compartir Información',
    'privacy_section4': '4. Seguridad de Datos',
    'privacy_section5': '5. Cookies',
    'privacy_section6': '6. Sus Derechos',
    'privacy_section7': '7. Contacto',
    'privacy_item1a': 'Información de contacto (nombre, correo electrónico, teléfono, empresa)',
    'privacy_item1b': 'Direcciones de envío y facturación',
    'privacy_item1c': 'Historial de pedidos y detalles de transacciones',
    'privacy_item1d': 'Solicitudes de cotización e historial de comunicaciones',
    'privacy_item1e': 'Datos de uso y análisis',
    'privacy_item1f': 'Mejorar nuestro sitio web y servicios',
    'privacy_item2a': 'No vendemos su información personal. Compartimos datos solo con: proveedores de servicios que asisten nuestras operaciones, fuerzas del orden cuando la ley lo requiera, y socios comerciales con su consentimiento explícito.',
    'privacy_item2b': 'Implementamos medidas de seguridad estándar de la industria, incluyendo cifrado SSL, servidores seguros, controles de acceso y revisiones de seguridad periódicas para proteger su información personal.',
    'privacy_item2c': 'Utilizamos cookies y tecnologías similares para mantener su carrito de compras, recordar sus preferencias, analizar el tráfico del sitio y personalizar su experiencia. Puede controlar las cookies a través de la configuración de su navegador.',
    'privacy_item3': 'Tiene derecho a: acceder a sus datos personales, corregir información inexacta, solicitar la eliminación de sus datos, optar por no recibir comunicaciones de marketing y solicitar la portabilidad de datos. Contáctenos en privacy@labproglobal.com para ejercer estos derechos.',
    'privacy_item4': 'Para consultas relacionadas con la privacidad, contacte a nuestro Oficial de Protección de Datos en',
    'privacy_item5': 'Todos los datos se almacenan de forma segura en servidores cifrados.',
    'privacy_item6': 'Puede solicitar la eliminación de su cuenta y datos en cualquier momento.',
    'privacy_item7': 'Cumplimos con las leyes de protección de datos aplicables, incluyendo el RGPD.',
    # Returns
    'returns_title': 'Devoluciones y Reembolsos',
    'returns_subtitle': 'Queremos que esté completamente satisfecho con su compra.',
    'returns_30day': 'Devoluciones de 30 días',
    'returns_30day_desc': 'Los artículos estándar pueden devolverse dentro de los 30 días posteriores a la entrega',
    'returns_easy': 'Proceso Fácil',
    'returns_easy_desc': 'Solicite una devolución a través de su cuenta',
    'returns_full': 'Reembolso Completo',
    'returns_full_desc': 'Reembolso procesado en 5-7 días hábiles',
    'returns_policy': 'Política de Devoluciones',
    'returns_policy_standard': 'Productos Estándar: Reembolso completo dentro de 30 días en estado sin abrir y sin usar.',
    'returns_policy_special': 'Pedidos Especiales: No pueden devolverse a menos que estén defectuosos.',
    'returns_policy_defective': 'Productos Defectuosos: Contáctenos inmediatamente. Reemplazo o reembolso gratuito.',
    'returns_policy_shipping': 'Envío de Devolución: El cliente es responsable del envío estándar.',
    'returns_how': 'Cómo Devolver un Artículo',
    'returns_step1': 'Inicie sesión en su cuenta y vaya a Historial de Pedidos',
    'returns_step2': 'Seleccione el pedido y el artículo que desea devolver',
    'returns_step3': 'Elija un motivo de devolución y envíe su solicitud',
    'returns_step4': 'Recibirá una autorización de devolución y etiqueta de envío',
    'returns_step5': 'Empaque el artículo de forma segura y envíelo de vuelta',
    'returns_step6': 'Recibirá su reembolso una vez que procesemos la devolución',
    'returns_contact': 'Contactar Departamento de Devoluciones',
    'returns_need_help': '¿Necesita ayuda con una devolución?',
    # Products
    'products_page_title': 'Todos los Productos',
    'products_results_count': '{count} productos encontrados',
    'products_showing_range': 'Mostrando {from}–{to} de {total}',
    'products_no_results': 'No se encontraron productos',
    'products_prev': 'Anterior',
    'products_next': 'Siguiente',
    # Home
    'home_hero_title': 'Equipos de Laboratorio de Alta Calidad',
    'home_hero_subtitle': 'Encuentre todo lo que necesita para su laboratorio:instrumentos de precisión,soluciones de flujo,analizadores y más.',
    'home_hero_button': 'Explorar Productos',
    'home_hero_quote': 'Solicitar Cotización',
    'home_featured': 'Productos Destacados',
    'home_categories': 'Categorías Populares',
    'home_why': 'Por Qué Elegirnos',
    'home_quality': 'Calidad Garantizada',
    'home_quality_desc': 'Todos los productos cumplen con los estándares internacionales de calidad y están respaldados por garantía del fabricante.',
    'home_pricing': 'Precios Competitivos',
    'home_pricing_desc': 'Ofrecemos precios transparentes y competitivos sin tarifas ocultas. Solicite una cotización para precios personalizados.',
    'home_shipping': 'Envío Rápido',
    'home_shipping_desc': 'Envío rápido y seguro con seguimiento en tiempo real. Envío gratuito en pedidos que cumplan los requisitos.',
    'home_support': 'Soporte Experto',
    'home_support_desc': 'Nuestro equipo de expertos está disponible para ayudarle a elegir los productos adecuados para sus necesidades.',
    'home_view_all': 'Ver Todos',
    'home_view_product': 'Ver Producto',
    'home_add_to_cart': 'Añadir al Carrito',
    'home_get_quote': 'Obtener Cotización',
    'home_learn_more': 'Más Información',
    'home_featured_title': 'Productos Destacados',
    'home_featured_desc': 'Explore nuestra selección de equipos de laboratorio de alta calidad.',
    'home_categories_title': 'Categorías Populares',
    'home_categories_desc': 'Encuentre exactamente lo que necesitaBrowse por categoría.',
    'home_about_title': 'Sobre Nosotros',
    'home_about_p1': 'LabProGlobal es un proveedor líder de equipos y suministros de laboratorio de alta calidad.',
    'home_about_p2': 'Con años de experiencia en la industria, nos especializamos en proporcionarinstrumentos de precisión, soluciones de flujo y equipos de análisis para laboratorios farmacéuticos,de investigación, industriales y clínicos.',
    'home_about_p3': 'Nuestra misión es apoyar los avances científicos proporcionandoproductos confiables y un servicio excepcional a precios competitivos.',
    'home_about_btn': 'Más Información',
    'home_trust': 'Construyendo Confianza',
    'home_trust_p1': 'Miles de laboratorios en todo el mundoconfían en LabProGlobal para sus necesidades de equipos.',
    'home_trust_p2': 'Nos comprometemos a la calidad, la transparencia y la satisfacción del cliente en cadapedido.',
    'home_trust_p3': 'Nuestro equipo dedicado está aquí para ayudarle en cada paso del camino.',
    'home_newsletter_title': 'Boletín',
    'home_newsletter_desc': 'Reciba las últimas novedades, ofertas especiales y consejos de laboratorio.',
    'home_newsletter_placeholder': 'Su correo electrónico',
    'home_newsletter_button': 'Suscribirse',
    'home_newsletter_success': '¡Gracias por suscribirse!',
    # About
    'about_title': 'Sobre Nosotros',
    'about_hero_title': 'Sobre Nosotros',
    'about_hero_subtitle': 'Conozca más sobre LabProGlobal y nuestra misión.',
    'about_mission_title': 'Nuestra Misión',
    'about_mission_p1': 'En LabProGlobal, notre dedicamos a empower laboratories worldwide with high-quality, reliable laboratory equipment and instruments.',
    'about_mission_p2': 'Our mission is to accelerate scientific discovery by providing researchers and professionals with the tools they need to succeed.',
    'about_vision_title': 'Nuestra Visión',
    'about_vision_p1': 'Our vision is to be the most trusted partner for laboratory equipment and supplies globally.',
    'about_vision_p2': 'We strive to continuously expand our product offerings and improve our service to meet the evolving needs of the scientific community.',
    'about_values_title': 'Nuestros Valores',
    'about_quality': 'Calidad',
    'about_quality_desc': 'Only products that meet our rigorous quality standards make it to our catalog.',
    'about_innovation': 'Innovación',
    'about_innovation_desc': 'We continuously seek new and improved products to serve our customers better.',
    'about_integrity': 'Integridad',
    'about_integrity_desc': 'Honest pricing, transparent policies, and ethical business practices guide everything we do.',
    'about_customers': 'Clientes Primero',
    'about_customers_desc': 'Your success is our priority. We are here to support you at every step.',
    'about_team_title': 'Nuestro Equipo',
    'about_team_p1': 'Our team brings together expertise in laboratory equipment, supply chain management, and customer service.',
    'about_team_p2': 'We are passionate about science and committed to helping our customers achieve their research and operational goals.',
    'about_contact_title': 'Contáctenos',
    'about_contact_p1': 'Have questions or need assistance? Our team is here to help.',
    'about_contact_p2': 'Reach out to us through our contact form or browse our frequently asked questions for quick answers.',
    # Errors
    'error_title': 'Error',
    'error_generic': 'Ha ocurrido un error. Por favor, inténtelo de nuevo.',
    'error_404_title': 'Página No Encontrada',
    'error_404_desc': 'Lo sentimos, la página que está buscando no existe o ha sido movida.',
    'error_404_button': 'Volver al Inicio',
    'error_back_home': 'Volver al Inicio',
    # Accessibility
    'aria_language_options': 'Opciones de idioma',
    'aria_close_menu': 'Cerrar menú',
    'aria_open_menu': 'Abrir menú',
    'aria_remove_item': 'Eliminar artículo',
    'aria_increase_quantity': 'Aumentar cantidad',
    'aria_decrease_quantity': 'Disminuir cantidad',
    # Placeholders
    'placeholder_name_example': 'John Smith',
    'placeholder_company_example': 'Su Empresa S.A.',
    'placeholder_email_example': 'su@correo.com',
    'placeholder_phone_example': '+1 (555) 000-0000',
    'placeholder_notes_example': 'Añada notas adicionales aquí...',
    'placeholder_search_example': 'Buscar productos...',
}

with open(r'E:\novatech-store\lib\i18n\translations.ts', encoding='utf-8') as f:
    content = f.read()

# Find ES block boundaries
es_start = content.find('const es: TranslationKeys = {')
if es_start == -1:
    print('ERROR: ES block not found!')
    sys.exit(1)

# Find the end: either next const block or export const
next_const = content.find('\nconst ', es_start + 10)
next_export = content.find('\nexport const', es_start + 10)

if next_const == -1 and next_export == -1:
    es_end = len(content)
elif next_const == -1:
    es_end = next_export
elif next_export == -1:
    es_end = next_const
else:
    es_end = min(next_const, next_export)

print(f'ES block: chars {es_start} to {es_end} ({es_end - es_start} chars)')

# Build new ES block
new_es_lines = ['const es: TranslationKeys = {\n']
for key, value in sorted(ES_TRANSLATIONS.items()):
    new_es_lines.append(f"  {key}: '{value}',\n")
new_es_lines.append('}\n')

new_es = ''.join(new_es_lines)
new_content = content[:es_start] + new_es + content[es_end:]

with open(r'E:\novatech-store\lib\i18n\translations.ts', 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f'Done! Rebuilt ES block with {len(ES_TRANSLATIONS)} keys')
